<div class="container2">
	<style type="text/css">
		#canvas{
			border: 1px solid  #000;
			box-shadow: 2px 2px 10px #333;
		}
	</style>

	<h6 class="titulo" align="center" style = "font-size:35px; color:#2196f3">FICHA HOGAR</h6>
	<form action="<?php echo BASE_URL; ?>ficha_hogar/ingresar" id="hogar" method="POST" enctype="multipart/form-data" >
		
		<div class="row" align="right">
			<FONT COLOR="2196f3 ">Número de ficha <i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
				Responda la pregunta 2 y la pregunta 10 o pregunta 14 para obtener el número de la ficha
				">live_help</i></FONT>
				<div class="num blue">
					<div ><input id="codigo_hogar" name="codigo_hogar" type="text" readonly ></div>
				</div>
			</div>

			<ul class="collapsible" data-collapsible="accordion">
				<li>
					<div class="collapsible-header blue active ">Ficha Hogar</div>
					<div class="collapsible-body">
						<div class="container">
							<div class="row">
								<div class="input-field col l6">                              
									<?php if(isset($this->municipios)) : ?>
										<br><br>
										<label class="colorBlue">2. Municipio
											<i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
											Escoja un municipio para obtener el código del municipio 
											">live_help</i>
										</label>

										<select class="browser-default" name="municipio" required>
											<option value="" disabled selected>Seleccione una opción</option>
											<?php for($i = 0; $i < count($this->municipios); $i++): ?>											<option value="<?php echo $this->municipios[$i]['COD_DANE']; ?>"  ><?php echo $this->municipios[$i]['DES_MUNICIPIO']; ?></option>
											<?php endfor;?>
										</select>
									<?php endif; ?>

								</div> <br><br>

								<div class="input-field col l6">
									<label for="cod_municipio" class="colorWhite" >3. Codigo del municipio
										<i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
										Responda  la pregunta 2 para obtener el código del municipio">live_help</i>
									</label> 
									<input  name="codigo_municipio" placeholder="Código del municipio"  type="number"  class="validate" id="cod" readonly>
								</div>
							</div>

							<div class="row">
								<div class="input-field col l4" class="browser-default" id="tipoHogar" >
									<label class="colorBlue">4. <?php echo $this->preguntas[0]['DES_PREGUNTA']; ?></label><br><br>
									<select class="browser-default" name="tipoHogar"   required >
										<option value="" disabled selected>Seleccione una opción</option>
										<option value="54">1 | Nuclear</option>
										<option value="55">2 | Extenso</option>
										<option value="56">3 | Monopaternal</option>
										<option value="57">4 | Unipersonal</option>
									</select>
								</div>

								<div class="input-field col l4">
									<label class="colorBlue">5. Jefe de hogar</label><br><br>
									<select class="browser-default" name="jefeHogar" required>
										<option value="" disabled selected>Seleccione una opción</option>
										<option value="58">1 | Padre</option>
										<option value="59">2 | Madre</option>
										<option value="60">3 | Hijo</option>
										<option value="63">4 | Hermano</option>
										<option value="64">5 | Abuelo(a)</option>
										<option value="65">6 | Otro familiar</option>
										<option value="66">7 | Personas no pariente</option>
									</select>
								</div>

								<br><br>
								<div class="input-field col l4">
									<input name="telefono_jefe_hogar" placeholder="Télefono"  type="number" class="validate" required>
									<br>
									<label for="codHogar" class="colorWhite" >6. Télefono jefe del hogar</label>
								</div>
							</div>


							<div class="collapsible-header blue ">
								<label for="" class="colorWhite" > 7. UBICACIÓN HOGAR</label>
							</div>
							<br>
							<input name="ubicacion" type="radio" id="urbana" value="1"  required />
							<label for="urbana" class="colorBlue">8. Zona urbana</label>
							<input name="ubicacion" type="radio" id="rural" value="2"  />
							<label for="rural" class="colorBlue">9. Zona rural</label>

							<br>
							<div  id="datosUrbano">
								<div class="row">
									
									<br><br>
									<div class="input-field col l6">	<br><br>
										<label for="codHogar" class="colorWhite" >11. Código del barrio</label>
										<input name="codigo_barrio" placeholder="Código del Barrio" disabled type="text" class="validate">
									</div>
									<div class="input-field col l6">                              
										<?php if(isset($this->barrios)) : ?>
											<br><br>
											<select class="browser-default" name="nombreBarrio" id="barrio">
												<option value="" disabled selected>Seleccione una opción</option>
												<?php for($i = 0; $i < count($this->barrios); $i++): ?>		
													<li><?php echo $this->barrios[$i]['ID_BARRIO']; ?></li>
													<option value="<?php echo $this->barrios[$i]['ID_BARRIO']; ?>"><?php echo $this->barrios[$i]['DES_BARRIO']; ?></option>
												<?php endfor;?>
											</select>
											<label class="colorBlue">10. Barrio</label>
										<?php endif; ?>
									</div>

                            </div>
                            <div class="row">
									<div>
										<div class="input-field col s6 nomenclaturaBarrio">
											<input name="nomenclaturaBarrio" placeholder="Ejemplo: Carrera 13 # 26 – 18, apartamento 203" type="text" class="validate">
											<label for="nomenclaturaBarrio" class="colorWhite" >12. Nomenclatura </label>
										</div>
										<div class="input-field col s6">
											<input name="noAplicaBarrio" type="checkbox" class="filled-in" id="noAplicaBarrio"  />
											<label for="noAplicaBarrio">13. No aplica <i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
												Marque esta casilla en el caso de que la vivienda no cuente con una nomenclatura establecida">live_help</i></label>
											</div>
										</div>
									</div>
								</div>

								<br>
								<div  id="datosRural">
								       <div class="row">
								       
											<div class="input-field col s6">
											 <br><br>                         
												<?php if(isset($this->veredas)) : ?>
													<select name="nombreVereda" id="barrio" class="browser-default">
														<option value="" disabled selected></option>
														<?php for($i = 0; $i < count($this->veredas); $i++): ?>		
															<li><?php echo $this->veredas[$i]['ID_BARRIO']; ?></a></li>										  
			<option value="<?php echo $this->veredas[$i]['ID_BARRIO']; ?>"><?php echo $this->veredas[$i]['DES_BARRIO']; ?></option>													   									 
														<?php endfor;?>
													</select>
													<label class="colorBlue">14. Vereda
                                      <i class=" tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
Seleccione  una vereda para obtener el código del vereda
">live_help</i>
 
													</label>	 
												<?php endif; ?>

											</div><br><br>
											<div class="input-field col s6">
												<label for="nomVereda" class="colorWhite" >15. Codigo Vereda


   <i class=" tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
Responda la pregunta 14 para obtener el código del barrio
">live_help</i>
												</label>
												<input name="numVereda" placeholder="Nombre Vereda o inspección " readonly type="text" class="validate">

											</div>
								       </div>
								       <div class="row ">
								    
											<div class="input-field col s6 nomenclaturaVereda"><br>
												<input name="nomenclaturaVereda" placeholder="Nomenclatura" type="text" class="validate">
												<label for="nomenclaturaVereda" class="colorWhite" >16. Nomenclatura</label>
											</div>
											<div class="input-field col s6">
												<p>
								      			    <input name="noAplicavereda" type="checkbox" class="filled-in" id="noAplicavereda"  />
								      				<label for="noAplicavereda">17. No Aplica .</label>
								      			</p>
											</div>
								       </div>

								</div>

							</div>

									</div>

									<li>
										<div class="collapsible-header blue">Identificar miembros del hogar </div>
										<div class="collapsible-body" style="overflow:auto;">
											<div class="row">
												<table class="centered bordered" id="tabla-hogar" style="width:2000px;">
													<thead>
														<tr>
															<th class="colorBlue">18. Documento de identidad <i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
																Escriba únicamente el número del documento que aparece en la cedula, en el registro civil o en la tarjeta de identidad. No se permite otro tipo de identificación como pasaporte o número del pase o del carnet de la EPS, etc">live_help</i></th>
																<th class="colorBlue">19. Nombres  <i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
																	Escriba los nombres completos  de cada uno de los miembros del hogar, preferiblemente como aparecen en el documento de identificación">live_help</i></th>
																<th class="colorBlue">20.Apellidos  <i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
																	Escriba los nombres   apellidos completos de cada uno de los miembros del hogar, preferiblemente como aparecen en el documento de identificación">live_help</i></th>
																	<th class="colorBlue">20. Fecha nacimiento</th>
																	<th class="colorBlue">21. Edad
																		<i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
																		Seleccione la fecha de nacimiento para obtener la edad
																		">live_help</i>
																	</th>
																	<th class="colorBlue">22. Genero</th>
																	<th class="colorBlue">23. Vinculación familiar con respecto al jefe del hogar

																		<i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
																		Seleccione como primer miembro el jefe de hogar
																		">live_help</i>			              </th>
																	</tr>
																</thead>

																<tbody id="ts">
																	<tr>
																		<td WIDTH="600"><input id="ficha_doc" name="docIdentidad[]" placeholder="Documento Identidad"  type="number" class="validate" required></td>

																		<td WIDTH="600"><input  name="nomApe[]" class="name1" placeholder="Nombres"  type="text" class="validate" required></td>

																		<td WIDTH="600"><input  name="Apellido[]" placeholder="Apellidos"  type="text" class="validate" required></td>

																		<td WIDTH="400"><input id="dateNacimiento" class="datepicker" name="dateNacimiento[]" placeholder="Fecha de nacimiento"  type="date" class="validate" required></td>

																		<td WIDTH="300"><input class="edad" name="edad[]" placeholder="Edad" type="text"   class="validate"  required readonly></td>

																		<td WIDTH="400">  
																			<select class="browser-default" name="sexo[] " required>
																				<option value="" disabled selected>Genero</option>
																				<option value="M">Masculino</option>
																				<option value="F">Femenino</option>
																			</select>    
																		</td>

																		<td WIDTH="700">  <select class="browser-default"  name="vinculacionJefe[]" required>
																			<option value="" disabled selected>Vinculación familiar con respecto al jefe del hogar</option>
																			<option value="285">1 | Jefe de hogar</option>
																			<option value="286">2 | Cónyuge</option>
																			<option value="287">3 | Madre</option>
																			<option value="288">4 | Padre</option>
																			<option value="289">5 | Hijo(a)</option>
																			<option value="290">6 | Hermano(a)</option>
																			<option value="291">7 | Abuelos(as)</option>
																			<option value="292">8 | Sobrinos</option>
																			<option value="293">9 | Madrastra</option>
																			<option value="294">10 | Padrastro</option>
																			<option value="295">11 | Otros parientes</option>
																			<option value="296">12 | Otros miembros no parientes</option>
																		</select>      
																	</td>
																</tr>
															</tbody>
														</table>
														<br>
														<h6 align="left">
															<a class="btn green waves-effect waves-light" type="submit" id="agregarFamiliar">Agregar familiar
															</a>
															<a class="btn red waves-effect waves-light" type="submit" id="eliminarFamiliar">Eliminar familiar
															</a>
														</h6 >
														<br>
													</div>
												</li>

												<li>
													<div class="collapsible-header blue ">Características socioeconómicas del hogar </div>
													<div class="collapsible-body" style="overflow:auto;">
														<table class="centered bordered" id="tablaSocioeconomica" style="width:3000px;">
															<thead>
																<tr>
																	<th></th>
																	<th></th>
																	<th colspan="3"><FONT COLOR="2196f3 ">26. Ocupación</th>
																	<th colspan="3"><FONT COLOR="2196f3 ">29. Vinculación al SGSSS</th>
																</tr>
																<tr>
																	<th ><FONT COLOR="2196f3 ">Nombre
																		<i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
																		Si desea cambiar el nombre vuelva a la sección  Identificar miembros del hogar
																		">live_help</i>		
																	</th>
																	<th ><FONT COLOR="2196f3 ">24. Escolaridad</th>
																	<th ><FONT COLOR="2196f3 ">25. Tipo</th>
																	<th ><FONT COLOR="2196f3 ">27. Recibe pago</th>
																	<th ><FONT COLOR="2196f3 ">28. Aporta al hogar</th>
																	<th ><FONT COLOR="2196f3 ">30. Regimen</th>
																	<th ><FONT COLOR="2196f3 ">31. Tipo de vinculación</th>
																	<th ><FONT COLOR="2196f3 ">32. Nombre EPS</th>
																</tr>
															</thead>
															<tbody>

																<tr>
																	<td width="600"600 style="vertical-align:top;"><input disabled placeholder="Nombre" class="name2" type="text" class="validate"></td>
																	<td width="600" style="vertical-align:top;">  
																		<select class="browser-default" name="escolaridad[]" required>
																			<option value="" disabled selected>Escolaridad</option>
																			<option value="297">1 | No sabe leer ni escribir</option>
																			<option value="298">2 | Nunca fue a la escuela pero sabe leer y escribir</option>
																			<option value="299">3 | Preescolar</option>
																			<option value="300">4 | Primaria completa</option>
																			<option value="301">5 | Primaria incompleta</option>
																			<option value="302">6 | Secundaria completa</option>
																			<option value="303">7 | Secundaria incompleta</option>
																			<option value="304">8 | Técnico o Tecnológico</option>
																			<option value="305">9 | Universitario</option>
																		</select>      
																	</td>

																	<td width="600" style="vertical-align:top;">  <select class="browser-default" name="tipoOcupacion[]" required>
																		<option value="" disabled selected>Tipo</option>
																		<option value="306">1 | Agricultura</option>
																		<option value="307">2 | Minería</option>
																		<option value="308">3 | Ganadería</option>
																		<option value="309">4 | Pesca</option>
																		<option value="310">5 | Oficios del hogar</option>
																		<option value="311">6 | Estudiando</option>
																		<option value="312">7 | Jubilado / Pensionado</option>
																		<option value="313">8 | Empleado sector público</option>
																		<option value="314">9 | Empleado sector privado</option>
																		<option value="315">10 | Prestador servicios técnicos, tecnológicos o profesionales</option>
																		<option value="316">11 | No aplica por condición física o mental</option>
																		<option value="317">12 | No aplica por edad</option>
																		<option value="318">13 | Sin ocupación</option>
																		<option value="319">14 | Otro</option>
																	</select>
																	<div class="input-fiel otratipoOcupacion">
																		<input name="otratipoOcupacions[]" placeholder="¿Cuál?" type="text" class="validate">
																	</div>
																</td>

																<td width="600" style="vertical-align:top;">  
																	<select class="browser-default" name="recivepago[]" required>
																		<option value="" disabled selected>Recibe pago</option>
																		<option value="320">1 | Si</option>
																		<option value="321">2 | No</option>
																		<option value="322">3 | No aplica</option>
																	</select>      
																</td>

																<td width="600" style="vertical-align:top;">  
																	<select class="browser-default" name="aportaHogar[]" required>
																		<option value="" disabled selected>Aporta al hogar</option>
																		<option value="323">1 | Si</option>
																		<option value="324">2 | No</option>
																		<option value="325">3 | No aplica</option>
																	</select>      
																</td>

																<td width="600" style="vertical-align:top;">  
																	<select class="browser-default" name="regimen[]" >
																		<option value="" disabled selected>Regimen</option>
																		<option value="326">1 | Contributivo</option>
																		<option value="327">2 | Subsidiado</option>
																		<option value="328">3 | Población pobre no asegurada (Vinculado)</option>
																		<option value="329">3 | Régimen especial</option>
																	</select>      
																</td >

																<td width="500" style="vertical-align:top;">  
																	<select class="browser-default" name="tipoVincuacion[]" >
																		<option value="" disabled selected>Tipo de vinculación</option>
																		<option value="330">1 | Cotizante</option>
																		<option value="331">2 | Beneficiario</option>
																		<option value="332">3 | No aplica</option>
																	</select>      
																</td>

																<td width="500" style="vertical-align:top;">
																	<select class="browser-default eps" name="nomEps[]" >
																		<option value="" disabled selected>EPS</option>
																	</select>
																</td>
								
															</tr>
														</tbody>
													</table>
												</div>
											</li>

											<li>
												<div class="collapsible-header blue">Condiciones de vulnerabilidad social del hogar </div>
												<div class="collapsible-body" style="overflow-x:scroll;">
													<table class="centered bordered" id="tabla-vulnerabilidad" style="width:3000px;">
														<thead>
															<tr>
																<th><FONT COLOR="2196f3 ">33. Nombre<i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="Si desea cambiar el nombre vuelva a la sección  Identificar miembros del hogar">live_help</i>
																</th>
																<!--<th><FONT COLOR="2196f3 ">34. Etapa del ciclo vital</th>-->
																<th><FONT COLOR="2196f3 ">35. Condición de discapacidad</th>
																<th><FONT COLOR="2196f3 ">36. Grupo étnico</th>
																<th><FONT COLOR="2196f3 ">37. Vinculación con el conflicto armado</th>
																<th><FONT COLOR="2196f3 ">38. Población LGBTI</th>
																<th><FONT COLOR="2196f3 ">39. Adolescentes en embarazo dependientes <i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
																	Mujeres entre los 10 y los 19 años que se encuentran en estado de embarazo. Tener presente que las menores entre 10 y 14 años que se encuentren en embarazo se consideran como víctimas de abuso">live_help</i></th>
																	<th><FONT COLOR="2196f3 ">40. Menor trabajador<i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
																		Todos los menores de 18 años que trabajan">live_help</i></th>
																		<th><FONT COLOR="2196f3 ">41. Menores en deserción escolar<i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
																			Todos los menores de 18 años que han iniciado sus estudios y los han abandonado">live_help</i></th>
													
																		</tr>
																	</thead>
																	<tbody>
																		<tr>
																			<td width="600" style="vertical-align:top;"><input disabled placeholder="Nombre" class="name3" type="text" class="validate"></td>
																

																				<td width="600" style="vertical-align:top;">
																					<select class="browser-default" name="condicionDiscapacidad[]" required>
																						<option value="" disabled selected>Condición discapacidad</option>
																						<option value="339">1 | Motora</option>
																						<option value="340">3 | Auditiva</option>
																						<option value="341">4 | Visual</option>
																						<option value="342">5 | Cognitiva o mental</option>
																						<option value="343">5 | No aplica</option>
																						<option value="343" >6 | Otros </option>
																					</select>
																					<div class="input-field col s12 otracondicionDiscapacidad ">
																						<input name="otracondicionDiscapacidad[]" placeholder="¿Cuál?" type="text" class="validate">
																					</div> 
																				</td>

																				<td width="600" style="vertical-align:top;">
																					<select class="browser-default" name="grupoEtnico[]" required>
																						<option value="" disabled selected>Grupo étnico</option>
																						<option value="344">1 | Indígena</option>
																						<option value="345">2 | Afrodescendiente</option>
																						<option value="346">3 | Mulato</option>
																						<option value="347">4 | Gitano ROM</option>
																						<option value="348">5 | No aplica</option>
																						<option value="348">6 | Otros </option>
																					</select>
																					<div class="input-field otragrupoEtnico">
																						<input name="otragrupoEtnico[]" placeholder="¿Cuál?" type="text" class="validate">
																					</div>  
																				</td>

																				<td width="600" style="vertical-align:top;">
																					<select class="browser-default" name="victimaConflicto[]" required>
																						<option value="" disabled selected>Vinculación conflicto armado</option>
																						<option value="349">1 | Víctima de desplazamiento forzado</option>
																						<option value="350">2 | Víctima Herido o agredido en cualquier condición</option>
																						<option value="351">3 | Víctima de familiares asesinados y/o desaparecidos</option>
																						<option value="352">4 | Víctima despojada de tierras</option>
																						<option value="353">5 | Víctimas amenazado(a)</option>
																						<option value="354">6 | Desmovilizado(a) </option>
																						<option value="355">7 | No aplica</option>
																					</select></td>

																					<td width="600" style="vertical-align:top;">
																						<select class="browser-default" name="poblacionLGBT[]" required>
																							<option value="" disabled selected>Población LGBTI</option>
																							<option value="356">1 | Lesbiana</option>
																							<option value="357">2 | Gay</option>
																							<option value="358">3 | Bisexual</option>
																							<option value="359">4 | Transexual</option>
																							<option value="360">5 | Intersexual</option>
																							<option value="361">6 | Varias de las anteriores </option>
																							<option value="362">7 | No aplica</option>
																						</select></td>

																						<td width="600" style="vertical-align:top;"><select class="browser-default" name="adolecentesEmbarazadas[]" required>
																							<option value="" disabled selected> Adolescentes en embarazo dependientes</option>
																							<option value="363">1 | Adolescente menor de 15 años embarazada sin control prenatal</option>
																							<option value="364">2 | Adolescente menor de 15 años embarazada con control prenatal </option>
																							<option value="365">3 | Adolescente entre 15 y 19 años embarazada sin control prenatal</option>
																							<option value="366">4 | Adolescente entre 15 y 19 años embarazada con control prenatal</option>
																							<option value="367">5 | Adolescente entre 15 y 19 años embarazada con control prenatal catalogada de alto riesgo</option>
																							<option value="368">6 | No aplica</option>
																						</select></td>

																						<td width="600" style="vertical-align:top;"><select class="browser-default" name="menorTrabajador[]" required>
																							<option value="" disabled selected>Menor trabajador</option>
																							<option value="369">1 | Menor trabajador estudiando</option>
																							<option value="370">2 | Menor trabajador que no está estudiando </option>
																							<option value="371">3 | No aplica</option>
																						</select></td>

																						<td width="600" style="vertical-align:top;"><select class="browser-default" name="menoresDesercioescolar[]" required>
																							<option value="" disabled selected>Menores en deserción escolar</option>
																							<option value="372">1 | Desertor escolar por trabajar</option>
																							<option value="373">2 | Desertor escolar por violencia escolar</option>
																							<option value="374">3 | Desertor escolar por condiciones económicas</option>
																							<option value="375">4 | Desertor escolar por desmotivación personal</option>
																							<option value="376">5 | Desertor escolar por distancia al centro educativo</option>
																							<option value="377">6 | Desertor escolar por otros motivos</option>
																							<option value="378">7 | No aplica</option>
																						</select></td>
																					</tr>
																				</tbody>
																			</table>
																			<br>
																			<div class="input-field col s12 ">
																				<input name="otrasCondicionesdeVulnerabilidad" placeholder=" " type="text" class="validate">
																				<label for="">Otras condiciones de vulnerabilidad identificadas</label>
																			</div>
																		</div>
																	</li>

																	<li>
																		<div class="collapsible-header blue ">Consumo e higiene</div>
																		<div class="collapsible-body" style="overflow-x:auto;">
																			<div class="row">
																				<table id="tabla-adiccionHigiene" class="centered bordered" style="width:2000px;">
																					<thead >
																						<tr>
																							<th><FONT COLOR="2196f3 ">Nombre
																								<i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
																								Si desea cambiar el nombre vuelva a la sección  Identificar miembros del hogar
																								">live_help</i>
																							</th>
																							<th><FONT COLOR="2196f3 ">42. Consumo de alcohol</th>
																							<th><FONT COLOR="2196f3 ">43. Consumo de cigarrillo</th>
																							<th><FONT COLOR="2196f3 ">44. Consumo de psicoactivos</th>
																							<th><FONT COLOR="2196f3 ">45. Higiene corporal</th>
																							<th><FONT COLOR="2196f3 ">46. Higiene bucal</th>
																							<th><FONT COLOR="2196f3 ">47. Actividad física</th>
																							<th><FONT COLOR="2196f3 ">48. Mujer gestación</th>
																							<th><FONT COLOR="2196f3 ">49. Diabetes e Hipertencion</th>
																						</tr>
																					</thead>

																					<tbody>
																						<tr>
																							<td width="600"><input disabled placeholder="Nombre" class="name4" type="text" class="validate"></td>
																							<td width="600">
																								<select class="browser-default" name="consumeAlcohol[]" required>
																									<option value="" disabled selected>Consumo de alcohol</option>
																									<option value="379">1 | Todos los días.</option>
																									<option value="380">2 | Entre 5 y 6 días por semana.</option>
																									<option value="381">3 | Entre 3 y 4 días por semana</option>
																									<option value="382">4 | Entre 1 y 2 días por semana.</option>
																									<option value="383">5 | Entre 1 y 3 días por mes</option>
																									<option value="384">6 | Menos de una vez al mes</option>
																									<option value="385">7 | No aplica</option>
																								</select>

																							</td>

																							<td width="600"><select class="browser-default" name="consumeCigarrillo[]" required>
																								<option value="" disabled selected>Consumo de cigarrillo</option>
																								<option value="386">1 | Consume un cigarrillo diario.</option>
																								<option value="387">2 | Consume más de un cigarrillo diario.</option>
																								<option value="388">3 | Consume entre 1 y 6 cigarrillos en una semana corriente</option>
																								<option value="389">4 | No consume cigarrillo</option>

																							</select></td>

																							<td width="600"><select class="browser-default" name="consumePsicoactivos[]" required>
																								<option value="" disabled selected>Consumo de psicoactivos</option>
																								<option value="390">1 | Consume psicoactivos entre 1 y más veces al día</option>
																								<option value="391">2 | Consume psicoactivos con más de una vez en una semana corriente</option>
																								<option value="392">3 | Consume psicoactivos menos de una vez en una semana corriente</option>
																								<option value="393">4 | No consume psicoactivos</option>
																							</select></td>

																							<td width="600"><select class="browser-default" name="higieneCorporal[]" required>
																								<option value="" disabled selected>Higiene corporal</option>
																								<option value="394">1 | Se realiza el baño de su cuerpo 1 vez al mes</option>
																								<option value="395">2 | Se realiza el baño de su cuerpo 1 vez a la semana</option>
																								<option value="396">3 | Se realiza el baño de su cuerpo 2 veces a la semana</option>
																								<option value="397">4 | Se realizan el baño de su cuerpo a diario.</option>
																							</select></td>
																							<td width="600"><select class="browser-default" name="higieneBucal[]" required>
																								<option value="" disabled selected>Higiene bucal</option>
																								<option value="398">1 | Se lava los dientes al menos una vez al día con agua, crema y cepillo</option>
																								<option value="399">2 | Se lava los dientes al menos dos veces al día con agua, crema y cepillo</option>

																								<option value="400">2 | Se lava los dientes tres veces al día con agua, crema y cepillo</option>
																								<option value="401">3 | Solo se enjuga con agua los dientes.</option>
																								<option value="402">4 | No de lava los dientes.</option>						
																							</select></td>
																							<td width="600"><select class="browser-default" name="actividadFisica[]" required>
																								<option value="" disabled selected>Actividad física</option>
																								<option value="403">1 | No realiza</option>
																								<option value="404">2 | 1 día a la semana</option>
																								<option value="405">3 | 2 y 3 a la semana</option>
																								<option value="406">4 | 4 y 5 a la semana</option>
																								<option value="407">5 | 6 y 7 a la semana</option>
																							</select></td>
																							<td width="600"><select class="browser-default" name="mujerGestacion[]" required>
																								<option value="" disabled selected>Mujer gestación</option>
																								<option value="412">1 | Mujer en gestación con control prenatal</option>
																								<option value="413">2 | Mujer en gestación sin control prenatal</option>
																								<option value="414">3 | No aplica</option>
																							</select></td>
																							<td  width="600">
																						<select class="browser-default"  name="efermedadCardioVacular[]" required>
																						            <option value="" disabled  selected></option>
																							    	<option value="538">1 | Diabetes</option>
																							    	<option value="539">2 | Hipertensión </option>
																							    	<option value="540">3 | Diabetes e Hipertensión.</option>
																							        <option value="541" >4 | No aplica.</option>	   
																						</select></td>
																						</tr>
																					</tbody>
																				</table>
																			</div>
																		</div>
																	</li>

																	<li>	
																		<div class="collapsible-header blue ">Condiciones de vulnerabilidad por vivienda del hogar</div>
																		<div class="collapsible-body" style="overflow-x:auto;">
																			<div class="row">
																				<div class="input-field col l4">
																					<br><br>
																					<select class="browser-default" name="tenenciaVivienda" required>
																						<option value="" disabled selected>Seleccione una opción</option>
																						<option value="83">1 | Propia</option>
																						<option value="84">2 | Arrendada </option>
																						<option value="85">3 | Vivienda familiar</option>
																						<option value="86">4 | Otra </option>
																					</select>
																					<label class="colorBlue">49. Tenencia de vivienda <i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="La tenencia de la vivienda hace referencia a las condiciones de propiedad o no del lugar donde se habita">live_help</i></label>
																					<div class="input-field otratenenciaVivienda">
																						<input name="otratenenciaVivienda" placeholder="¿Cuál?" type="text" class="validate">
																					</div> 

																				</div>
																				<div  class="input-field col l4">
																					<br><br>
																					<select class="browser-default" name="zonaVivienda" required>
																						<option value="" disabled selected>Seleccione una opción</option>
																						<option value="91">1 | En zona habitable predefinida por ordenamiento territorial</option>
																						<option value="92">2 | En zona habitable del sector rural</option>
																						<option value="93">3 | En zona no determinada como habitable</option>
																						<option value="94">4 | Zona inundable </option>
																						<option value="95">5 | Margen de ríos (orilla)</option>
																						<option value="96">6 | Zona de ladera o deslizamiento</option>
																						<option value="97">7 | Falda de la montaña</option>
																						<option value="98">8 | Relleno</option>
																						<option value="99">9 | Otra</option>
																					</select>
																					<label class="colorBlue">50. Ubicación de la vivienda</label>
																					<div class="input-field otrazonaVivienda">
																						<input name="otrazonaVivienda" placeholder="¿Cuál?" type="text" class="validate">
																					</div> 
																				</div>

																				<div  class="input-field col l4">
																					<br><br>
																					<select class="browser-default" name="tipoVivienda" required>
																						<option value="" disabled selected>Seleccione una opción</option>
																						<option value="87">1 | Casa</option>
																						<option value="88">2 | Apartamento</option>
																						<option value="89">3 | Habitación única dentro de una casa o apartamento</option>
																						<option value="90">4 | Otra</option>
																					</select>
																					<label class="colorBlue">51. Tipo de vivienda</label>
																					<div class="input-field otratipoVivienda ">
																						<input name="otratipoVivienda" placeholder="¿Cuál?" type="text" class="validate">
																					</div> 
																				</div>
																			</div>

																			<div class="row">
																				<table class="bordered centered" style="width:2000px;">
																					<thead class="colorBlue">
																						<tr >
																							<th class="titulo-tabla" colspan="3"><center>52. Materiales de la vivienda <i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="Hace referencia a los materiales que componen la estructura principal de la vivienda">live_help</i></center></th>
																							<th class="titulo-tabla" colspan="3"><center>56. Abastecimiento de água</center></th>

																						</tr >
																						<tr >
																							<th>53. Techo</th>
																							<th>54. Paredes</th>
																							<th>55. Piso</th>
																							<th>57. Fuente </th>
																							<th>58. Tratamiento</th>
																							<th>59. Almacenamiento</th>
																						</tr>
																					</tr>
																				</thead>

																				<tbody>
																					<tr >
																					</tr>
																					<tr>
																						<td style="vertical-align:top;"><select class="browser-default" name="materialTecho" required>
																							<option value="" disabled selected>Seleccione una opción</option>
																							<option value="100">1 | Teja de Eternit</option>
																							<option value="101">2 | Teja de zinc</option>
																							<option value="102">3 | Teja de barro</option>
																							<option value="103">4 | Placa de concreto</option>
																							<option value="104">5 | Paja y/u otros materiales naturales (bahareque)</option>
																							<option value="105">6 | Cartón y/o plástico</option>
																							<option value="106">7 | Otro</option>
																						</select>
																						<div class="input-field otramaterialTecho">
																							<input name="otramaterialTecho" placeholder="¿Cuál?" type="text" class="validate">
																						</div> 
																					</td>
																					<td style="vertical-align:top;"><select class="browser-default" name="materialParedes" required>
																						<option value="" disabled selected>Seleccione una opción</option>
																						<option value="107">1 | Ladrillo</option>
																						<option value="108">2 | Madera</option>
																						<option value="109">3 | Adobe</option>
																						<option value="110">3 | Bahareque</option>
																						<option value="111">4 | Plástico/cartón</option>
																						<option value="112">5 | Desechos</option>
																						<option value="113">5 | Otro</option>
																					</select>
																					<div class="input-field otramaterialParedes ">
																						<input name="otramaterialParedes" placeholder="¿Cuál?" type="text" class="validate">
																					</div> 
																				</td>
																				<td style="vertical-align:top;"><select class="browser-default" name="materialPiso" required>
																					<option value="" disabled selected>Seleccione una opción</option>
																					<option value="114">1 | Tierra</option>
																					<option value="115">2 | Madera</option>
																					<option value="116">3 | Cemento</option>
																					<option value="117">4 | Baldosa</option>
																					<option value="118">5 | Otro</option>
																				</select>
																				<div class="input-field otramaterialPiso">
																					<input name="otramaterialPiso" placeholder="¿Cuál?" type="text" class="validate">
																				</div>
																			</td>
																			<td style="vertical-align:top;"><select class="browser-default" name="abastecimientoFuente" required>
																				<option value="" disabled selected>Seleccione una opción</option>
																				<option value="119">1 | Acueducto</option>
																				<option value="120">2 | Pila </option>
																				<option value="121">3 | Pozo</option>
																				<option value="122">4 | Rio</option>
																				<option value="123">5 | Lluvia</option>
																				<option value="124">5 | Otro</option>
																			</select>
																			<div class="input-field  otraabastecimientoFuente">
																				<input name="otraabastecimientoFuente" placeholder="¿Cuál?" type="text" class="validate">
																			</div>
																		</td>
																		<td style="vertical-align:top;"><select class="browser-default" name="abastecimientoTratamiento" required>
																			<option value="" disabled selected>Seleccione una opción</option>
																			<option value="125">1 | Tratada</option>
																			<option value="126">2 | Filtrada</option>
																			<option value="127">3 | Hervida</option>
																			<option value="128">4 | Ninguno</option>
																			<option value="129">5 | Otro</option> </select>
																			<div class="input-field otraabastecimientoTratamiento">
																				<input name="otraabastecimientoTratamiento" placeholder="¿Cuál?" type="text" class="validate">
																			</div>
																		</td>
																		<td style="vertical-align:top;"><select class="browser-default" name="abastecimientoAlmacenamiento" required>
																			<option value="" disabled selected>Seleccione una opción</option>
																			<option value="130">1 | Tanque con tapa</option>
																			<option value="131">2 | Tanque sin tapa</option>
																			<option value="132">3 | Alberca</option>
																			<option value="133">4 | Caneca</option>
																			<option value="134">5 | Otro</option> </select>
																			<div class="input-field otraabastecimientoAlmacenamiento">
																				<input name="otraabastecimientoAlmacenamiento" placeholder="¿Cuál?" type="text" class="validate">
																			</div>
																		</td>
																	</tr>
																</tbody>
															</table>
														</div>

														<div class="row">
															<table class="bordered centered" style="width:2000px;">
																<thead class="colorBlue">
																	<tr>
																		<th colspan="2">60. Dispocicion de escretas</th>
																		<th colspan="4">63. Tratamiento de basuras</th>
																	</tr>
																	<tr>
																		<th>61. Mecanismo</th>
																		<th>62. Disposición</th>
																		<th>64. Recolección</th>
																		<th>65. Dispocición</th>
																		<th>66. Energía<i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="Hace referencia al tipo de energía que se utiliza para alumbrado">live_help</i></th>
																		<th>67. Combustible <i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="Se refiere al combustible utilizado para cocinar">live_help</i></th>				
																	</tr>
																</thead>
																<tbody>
																	<tr>
																		<td style="vertical-align:top;"><select class="browser-default" name="disposicionMecanismo" required>
																			<option value="" disabled selected>Seleccione una opción</option>
																			<option value="135">1 | Unidad sanitaria</option>
																			<option value="136">2 | Letrina</option>
																			<option value="137">3 | Campo abierto</option>
																			<option value="138">4 | Otro</option>
																		</select>
																		<div class="input-field otradisposicionMecanismo ">
																			<input name="otradisposicionMecanismo" placeholder="¿Cuál?" type="text" class="validate">
																		</div>
																	</td>
																	<td style="vertical-align:top;"><select class="browser-default" name="disposicionDispocicion" required>
																		<option value="" disabled selected>Seleccione una opción</option>
																		<option value="139">1 | Alcantarillado</option>
																		<option value="140">2 | Pozo séptico</option>
																		<option value="141">3 | Campo de infiltración</option>
																		<option value="142">4 | Incineración</option>
																		<option value="143">5 | Otro</option>

																	</select> 
																	<div class="input-field otradisposicionDispocicion">
																		<input name="otradisposicionDispocicion" placeholder="¿Cuál?" type="text" class="validate">
																	</div>
																</td>
																<td style="vertical-align:top;"><select class="browser-default" name="disposicionRecolecion" required>
																	<option value="" disabled selected>Seleccione una opción</option>
																	<option value="144">1 | Recolectada en recipiente dentro del hogar</option>
																	<option value="145">2 | Recolectada en recipiente fuera del hogar</option>
																	<option value="146">3 | Recolectada en abasto comunitario</option>
																	<option value="147">3 | No se recolecta</option>
																	<option value="148">4 | Otro</option>

																</select> 
																<div class="input-field otradisposicionRecolecion">
																	<input name="otradisposicionRecolecion" placeholder="¿Cuál?" type="text" class="validate">
																</div>
															</td>
															<td style="vertical-align:top;"><select class="browser-default" name="disposicionDisposicionbasuras" required>
																<option value="" disabled selected>Seleccione una opción</option>
																<option value="149">1 | Recolectada por servicio de aseo municipal</option>
																<option value="150">2 | Enterrada</option>
																<option value="151">3 | Quemada</option>
																<option value="152">3 | Campo Abierto</option>
																<option value="153">4 | Otro</option>

															</select> 
															<div class="input-field otradisposicionDisposicionbasuras">
																<input name="otradisposicionDisposicionbasuras" placeholder="¿Cuál?" type="text" class="validate">
															</div>
														</td>
														<td style="vertical-align:top;" ><select class="browser-default" name="Energia" required>
															<option value="" disabled selected>Seleccione una opción</option>
															<option value="154">1 | Eléctrica</option>
															<option value="155">2 | Vela de cera</option>
															<option value="156">3 | Lámpara de petróleo</option>
															<option value="157">3 | Energía solar</option>
															<option value="158">3 | Planta Generadora</option>
															<option value="159">4 | Otro</option>

														</select> 
														<div class="input-field otraEnergia">
															<input name="otraEnergia" placeholder="¿Cuál?" type="text" class="validate">
														</div>
													</td>
													<td style="vertical-align:top;"><select class="browser-default" name="Combustible" required>
														<option value="" disabled selected>Seleccione una opción</option>
														<option value="160">1 | Gas natural</option>
														<option value="161">2 | Gasolina</option>
														<option value="162">3 | Leña</option>
														<option value="163">3 | Electricidad</option>
														<option value="164">3 | Gas propano</option>
														<option value="165">4 | Carbón mineral</option>
														<option value="166">4 | Otro</option>
													</select> 
													<div class="input-field otraCombustible">
														<input name="otraCombustible" placeholder="¿Cuál?" type="text" class="validate">
													</div>
												</td>
											</tr>

										</tbody>
									</table>
								</div>
								<div class="row">
									<table class="bordered centered" style="width:2000px;">
										<thead class="colorBlue">
											<tr>
												<th class="titulo-tabla" colspan="3"><center>68. Estructura de la vivienda<i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="Hace referencia a la forma como está dispuesta la vivienda con respecto a las personas que la habitan">live_help</i></center></th>
												<th class="titulo-tabla" colspan="6"><center>72. Riegos de la vivienda<i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="Hace referencia a las condiciones encontradas que ponen en riesgo la vivienda y por tanto el hogar">live_help</i></center></th>
											</tr >
											<tr>
												<th>69. Cocina separada de dormitorios</th>
												<th>70. Número de dormitorios</th>
												<th>71. Personas por dormitorio</th>
												<th>73. Fisicos </th>
												<th>74. Químicos</th>
												<th>75. Biológicos</th>
												<th>76. Sociales</th>
											</tr>
										</tr>
									</thead>

									<tbody>
										<tr >	
										</tr>
										<tr>
											<td style="vertical-align:top;">
												<select class="browser-default" name="cocinaSeparada" required>
													<option value="" disabled selected>Seleccione una opción</option>
													<option value="167">1 | Si</option>
													<option value="168">2 | No</option>
													<option value="169">3 | No cuenta con cocina</option>
												</select>
											</td>
											<td style="vertical-align:top;">
												<div>
													<input name="numDormitorios"  placeholder="Número de dormitorios" type="number" class="validate" required>
												</div>
											</td>
											<td  style="vertical-align:top;">
												<div>
													<input name="numPersonaDormitorio" placeholder="Número de personas" type="number" class="validate" required>
												</div> 
											</td>
											<td style="vertical-align:top;"><select class="browser-default" name="riegosFisicos" required>
												<option value="" disabled selected>Seleccione una opción</option>
												<option value="170">1 | Por ubicación en zona de riesgo</option>
												<option value="171">2 | Por debilidad de la estructura general de la vivienda </option>
												<option value="172">3 | Por deterioro y antigüedad de la estructura.</option>
												<option value="173">4 | Por ruidos dentro y fuera de la vivienda.</option>
												<option value="174">5 | Por Iluminación inadecuada</option>
												<option value="175">6 | Por ventilación inadecuada</option>
												<option value="176">7 | Otro</option>
												<option value="177">8 | No aplica</option>
											</select><div class="input-field otrariegosFisicos">
											<input name="otrariegosFisicos" placeholder="¿Cuál?" type="text" class="validate">
										</div></td>

										<td style="vertical-align:top;"><select class="browser-default" name="riesgosQuimicos" required>
											<option value="" disabled selected>Seleccione una opción</option>
											<option value="178">1 | Almacenamiento de químicos utilizados en agricultura</option>
											<option value="179">2 | Almacenamiento de pólvora</option>
											<option value="180">3 | Combustible de cocina de alta combustión</option>
											<option value="181">4 | Almacenamiento de otro tipo de químicos</option>
											<option value="182">5 | Otro</option>
											<option value="183">5 | No aplica</option>
										</select><div class="input-field otrariesgosQuimicos">
										<input name="otrariesgosQuimicos" placeholder="¿Cuál?" type="text" class="validate">
									</div></td>


									<td style="vertical-align:top;"><select class="browser-default" name="riesgosBiologicos" required>
										<option value="" disabled selected>Seleccione una opción</option>
										<option value="184">1 | Alimentos sin refrigeración</option>
										<option value="185">2 | Mala manipulación de alimentos.</option>
										<option value="186">3 | Presencia de vectores (roedores e insectos)</option>
										<option value="187">4 | Dormitorios compartidos con animales</option>
										<option value="188">5 | Otro</option>
										<option value="189">6 | No aplica</option>
									</select><div class="input-field otrariesgosBiologicos ">
									<input name="otrariesgosBiologicos" placeholder="¿Cuál?" type="text" class="validate">
								</div>
							</td>

							<td style="vertical-align:top;"><select class="browser-default" name="riesgosSociales" required>
								<option value="" disabled selected>Seleccione una opción</option>
								<option value="190">1 | Cercanía o amenaza de presencia de grupos armados ilegales.</option>
								<option value="191">2 | Personas que realizan actividades ilícitas en cercanía a la vivienda</option>
								<option value="192">3 | Prácticas inadecuadas de los miembros del hogar que alteran la estructura de la vivienda</option>
								<option value="193">4 | Otro</option>
								<option value="194">5 | No aplica</option></select>
								<div class="input-field otrariesgosSociales">
									<input name="otrariesgosSociales" placeholder="¿Cuál?" type="text" class="validate">
								</div>
							</td>
						</tr>
					</tbody>
				</table>
				<br>
				<div class="input-field ">
					<input name="otrasCondicionesdeVulnerabilidadVivienda" placeholder="" id="" type="text" class="validate">
					<label for="textarea1">Otras condiciones de vulnerabilidad identificadas</label>
				</div>
			</div>
		</div>
	</li>

	<li>
		<div class="collapsible-header blue ">Condiciones de vulnrabilidad por el entorno de la vivienda y el hogar</div>
		<div class="collapsible-body">

			<div class="row">
				<div class="input-field col l4">
					<br><br>
					<select class="browser-default" name="viasAcceso" required>
						<option value="" disabled selected>Seleccione una opción</option>
						<option value="195">1 | Cuenta con vía de acceso tipo carretera o calle pavimentada a menos de 300 metros de la vivienda.</option>
						<option value="196">2 | Cuenta con vía de acceso tipo carretera o calle no pavimentada a menos de 300 metros de la vivienda</option>
						<option value="197">3 | Cuenta con vía de acceso tipo camino veredal a menos de 300 metros de la vivienda.</option>
						<option value="198">4 | Cuenta con vía de acceso tipo fluvial a menos de 300 metros de la vivienda (mar, rio o quebrada)</option>
						<option value="199">5 |  Otro tipo de acceso</option>
						<option value="200">6 |  No cuenta con ningún tipo de acceso</option>
					</select>
					<label class="colorBlue">77. Vías de acceso a la vivienda<i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="Hace referencia a la calidad, cantidad y distancia de las vías de acceso con que cuenta el hogar">live_help</i></label>
					<div class="input-field otraviasAcceso">
						<input name="otraviasAcceso" placeholder="¿Cuál?" type="text" class="validate">
					</div>
				</div>

				<div class="input-field col l4">
					<br><br>
					<select class="browser-default" name="transportePublico" required>
						<option value="" disabled selected>Seleccione una opción</option>
						<option value="201">1 | Cuenta con algún tipo de transporte público tipo bus, colectivo o similar que lo deje a menos de 300 metrosde la vivienda.</option>
						<option value="202">2 | Cuenta con algún tipo de servicio público tipo motocicleta, caballar o similar que lo deje a menos de 300
							metros de la vivienda.</option>
							<option value="203">3 | Cuenta con algún tipo de servicio público tipo ferri, yate, lancha o similar que lo deje a menos de 300
								metros de la vivienda.</option>
								<option value="204">5 |  Otro tipo de transporte con el que cuenta</option>
								<option value="205">6 |  No cuenta con ningún tipo de transporte público</option>
							</select>
							<label class="colorBlue">78. Transporte público</label>
							<div class="input-field otratransportePublico">
								<input name="otratransportePublico" placeholder="¿Cuál?" type="text" class="validate">
							</div>
						</div>

						<div class="input-field col l4">
							<br><br>
							<select class="browser-default" name="telefono_publico" required>
								<option value="" disabled selected>Seleccione una opción</option>
								<option value="206">1 | Cuenta con algún teléfono público pago en funcionamiento a menos de 300 metros de la vivienda.</option>
								<option value="207">2 | Cuenta con algún tipo de teléfono público gratuito en funcionamiento a menos de 300 metros de la vivienda.</option>
								<option value="208">3 | No cuenta con ningún tipo de teléfono público en funcionamiento.</option>
							</select>
							<label class="colorBlue">79. Teléfono público</label>
						</div>
					</div>

					<div class="row">
						<div class="input-field col l4">
							<br><br>
							<select class="browser-default" name="hogares_infantiles" required>
								<option value="" disabled selected>Seleccione una opción</option>
								<option value="209">1 | Cuenta con jardín infantil u hogar inicial para menores de cinco años en funcionamiento localizado a menos de 500 metros de distancia de la vivienda.</option>
								<option value="210">2 | Cuenta con jardín infantil u hogar inicial para menores de cinco años en funcionamiento, localizado entre 600 metros a 1 kilómetro de distancia de la vivienda.</option>
								<option value="211">3 | No cuenta con jardines infantiles u hogar inicial en funcionamiento localizado a menos de un kilómetro de distancia de la vivienda.</option>
							</select>
							<label class="colorBlue">80. Hogares infantiles</label>
						</div>

						<div class="input-field col l4">
							<br><br>
							<select class="browser-default" name="ecuelas" required>
								<option value="" disabled selected>Seleccione una opción</option>
								<option value="212">1 | Cuenta con escuela de educación básica y/o secundaria en funcionamiento localizada a menos de un kilómetro de distancia de la vivienda.</option>
								<option value="213">2 |Cuenta con escuela de educación básica y/o secundaria en funcionamiento localizada a una distancia entre 1 y 2 kilómetros de la vivienda.</option>
								<option value="214">3 | No cuenta con escuela en funcionamiento localizada a menos de un kilómetro de la vivienda</option>
							</select>
							<label class="colorBlue">81. Escuelas</label>
						</div>

						<div class="input-field col l4">
							<br><br>
							<select class="browser-default" name="centroSalud" required>
								<option value="" disabled selected>Seleccione una opción</option>
								<option value="215">1 | Cuenta con Centro de atención de primer nivel y de urgencias en funcionamiento localizado a menos de 1 kilómetro de distancia de la vivienda.</option>
								<option value="216">2 | Cuenta con centro de atención de primer nivel o de urgencias en funcionamiento localizado a una distancia entre 1 y 2 kilómetros de la vivienda.</option>
								<option value="217">3 | No cuenta con Centro de atención de primer nivel y de urgencias en funcionamiento a menos de dos kilómetros de distancia de la vivienda.</option>
							</select>
							<label class="colorBlue">82.  Centro de salud</label>
						</div>
					</div>

					<div class="row">
						<div class="input-field col l4">
							<br><br>
							<select class="browser-default" name="bomberos" required>
								<option value="" disabled selected>Seleccione una opción</option>
								<option value="218">1 | Cuenta con estación de bomberos en funcionamiento localizada a menos de 1 kilómetro de distancia de la vivienda.</option>
								<option value="219">2 | Cuenta con estación de bomberos en funcionamiento localizada a una distancia entre 1 y 2 kilómetros de la vivienda.</option>
								<option value="220">3 | La estación de bomberos en funcionamiento está localizada a más de 2 kilómetros de distancia de la vivienda..</option>
								<option value="221">4 | No cuenta con estación de bomberos en funcionamiento en el municipio.</option>
							</select>
							<label class="colorBlue"> 83. Centro de salud</label>
						</div>

						<div class="input-field col l4">
							<br><br>
							<select class="browser-default" name="comisariaFamilia" required>
								<option value="" disabled selected>Seleccione una opción</option>
								<option value="222">1 | Cuenta con comisaria de familia localizada a menos de 1 kilómetro de distancia de la vivienda.</option>
								<option value="223">2 | Cuenta con comisaria de familia localizada a una distancia entre 1 y 2 kilómetros de la vivienda.</option>
								<option value="224">3 | La comisaria de familia queda localizada a más de 2 kilómetros de distancia de la vivienda.</option>
								<option value="225">4 | No cuenta con comisaria de familia en el municipio.</option>
							</select>
							<label class="colorBlue">84.  Comisaria de familia</label>
						</div>

						<div class="input-field col l4">
							<br><br>
							<select class="browser-default" name="centroReligioso" required>
								<option value="" disabled selected>Seleccione una opción</option>
								<option value="226">1 | Cuenta con centro religioso localizado a menos de 1 kilómetro de distancia de la vivienda.</option>
								<option value="227">2 | Cuenta con centro religioso localizado a una distancia entre 1 y 2 kilómetros de la vivienda.</option>
								<option value="228">3 | El centro religioso está localizado a una distancia mayor a 2 kilómetros de la vivienda.</option>
								<option value="229">4 | No cuenta con centro religioso en el municipio</option>
							</select>
							<label class="colorBlue">85.  Centro religioso</label>
						</div>
					</div>

					<div class="row">
						<div class="input-field col l4">
							<br><br>
							<select class="browser-default" name="centroDeportivo" required>
								<option value="" disabled selected>Seleccione una opción</option>
								<option value="230">1 | Cuenta con centro o espacio deportivo localizado a menos de 1 kilómetro de distancia de la vivienda.</option>
								<option value="231">2 | Cuenta con centro o espacio deportivo localizado a una distancia entre 1 y 2 kilómetros de la vivienda.</option>
								<option value="232">3 | El centro deportivo está localizado a una distancia mayor a 2 kilómetros de la vivienda.</option>
								<option value="233">4 | No cuenta con centro deportivo en el municipio.</option>
							</select>
							<label class="colorBlue">86. Centro  deportivo</label>	
						</div>

						<div class="input-field col l4">
							<br><br>
							<select class="browser-default" name="centroCultural" required>
								<option value="" disabled selected>Seleccione una opción</option>
								<option value="234">1 |  Cuenta con centro cultural localizado a menos de 1 kilómetro de distancia de la vivienda.</option>
								<option value="235">2 | Cuenta con centro cultural localizado a una distancia entre 1 y 2 kilómetros de la vivienda.</option>
								<option value="236">3 | El centro cultural está localizado a una distancia mayor a 2 kilómetros de la vivienda. </option>
								<option value="237">4 | No cuenta con centro cultural en el municipio.</option>
							</select>
							<label class="colorBlue">87. Centro  cultural</label>
						</div>

						<div class="input-field col l4">
							<br><br>
							<select class="browser-default" name="mercadoBasico" required>
								<option value="" disabled selected>Seleccione una opción</option>
								<option value="238">1 | Cuenta con expendio de mercado básico localizado a menos de 1 kilómetro de distancia de la vivienda.</option>
								<option value="239">2 | Cuenta con expendio de mercado básico localizado a una distancia entre 1 y 2 kilómetros de la vivienda.</option>
								<option value="240">3 | El expendio de mercado básico está localizado a una distancia mayor a 2 kilómetros de la vivienda </option>
								<option value="241">4 | No cuenta con mercado básico en el municipio.</option>
							</select>
							<label class="colorBlue">88. Mercado básico</label>
						</div>
					</div>

					<div class="row">
						<div class="input-field col l6">
							<br><br><br>
							<select class="browser-default" name="presenciaVectores" required>
								<option value="" disabled selected>Seleccione una opción</option>
								<option value="250">1 | Zancudos (ya sea especie Aedes o especie Anopheles, u otros)</option>
								<option value="251">2 | Palomilla, manta blanca, quemador, pringador, jején, pito (flebótomos que causan la leishmaniasis)</option>
								<option value="252">3 |  Chinches (triatómidos, parasito que causa enfermedad de Chagas) </option>
								<option value="253">4 | Pulgas y/o piojos</option>
								<option value="254">5 | Garrapatas, cucarachas, hematófagos (murciélagos)</option>
								<option value="255">6 | Otros</option>
								<option value="256">7 | No aplica</option>
							</select>
							<label class="colorBlue">89. Presencia de vectores o plagas cerca o dentro de la vivienda</label>
							<div class="input-field otrapresenciaVectores">
								<input name="otrapresenciaVectores" placeholder="¿Cuál?" type="text" class="validate">
							</div>
						</div>

						<div class="input-field col l6">
							<br><br><br>
							<select class="browser-default" name="presenciaCentros" required>
								<option value="" disabled selected>Seleccione una opción</option>
								<option value="242">1 | Cerca de la vivienda se encuentran expendios de drogas y/o otros psicoactivos</option>
								<option value="243">2 | Cerca de la vivienda se encuentran lugares de prostitución</option>
								<option value="244">3 | Cerca de vivienda se encuentran lugares de proxenetismo y pornografía </option>
								<option value="245">4 | Cerca de la vivienda se encuentran expendios de armas</option>
								<option value="246">5 | Cerca de la vivienda se encuentran lugares de acopio masivo de personas (estadios, discotecas, casinos,etc.)</option>
								<option value="247">6 | Cerca de la vivienda se encuentran fábricas o expendidos de pólvora</option>
								<option value="248">7 | Otro </option>
								<option value="249">8 | Ningún lugar de los anteriores que represente riesgo para el hogar</option>
							</select>
							<label class="colorBlue">90. Centros o zonas que representan riesgos para el hogar</label>
							<div class="input-field otrapresenciaCentros">
								<input name="otrapresenciaCentros" placeholder="¿Cuál?" type="text" class="validate">
							</div>
						</div>
					</div>

					<br>
					<div class="row">
						<div class="input-field ">
							<input name="otrasCondicionesdeVulnerabilidadViviendaHogar" placeholder="" id="" type="text" class="validate">
							<label for="textarea1">Otras condiciones de vulnerabilidad identificadas</label>
						</div>
					</div>
				</li>


				<li>	
					<div class="collapsible-header blue ">Condiciones de vulnerabilidad por los hábitos y costumbres de los miembros del hogar</div>
					<div class="collapsible-body" style="overflow-x:auto;">
						<div class="row">
							<div class="input-field col l6">
								<br><br>
								<select class="browser-default" name="convivencia" required><br>
									<option value="" disabled selected>Seleccione una opción</option>
									<option value="257">1 | Se presentan malos tratos verbales entre algunos miembros del hogar</option>
									<option value="258">2 | Se presentan malos tratos físicos entre algunos miembros del hogar</option>
									<option value="259">3 | Las dos anteriores se presentan con alguna frecuencia en el hogar </option>
									<option value="260">4 | En el hogar no se presenta ningún tipo de malos tratos ni físicos ni verbales.</option>
								</select>
								<label class="colorBlue">91. Convivencia</label>
							</div>

							<div class="input-field col l6">
								<br><br>
								<select class="browser-default" name="hijieneVivienda" required><br>
									<option value="" disabled selected>Seleccione una opción</option>
									<option value="261">1 | La vivienda es barrida, trapeada y/o lavada todos los días</option>
									<option value="262">2 | La vivienda es barrida, trapeada y/o lavada algunos días de la semana</option>
									<option value="263">3 | La vivienda es barrida, trapeada y/o lavada alguna vez por semana </option>
									<option value="264">4 | La vivienda es barrida, trapeada y/o lavada al menos una vez al mes</option>
									<option value="265">5 | La vivienda pasa más de un mes sin realizarle aseo de ningún tipo.</option>
								</select>	
								<label class="colorBlue">92. Higiene vivienda</label>
								<div class="input-field otrahijieneVivienda">
									<input name="otrahijieneVivienda" placeholder="¿Cuál?" type="text" class="validate">
								</div>
							</div>
						</div>

						<div class="row">	
							<div class="input-field col l6">	
								<br><br>	
								<select class="browser-default" name="riesgosLaborales" required>
									<option value="" disabled selected>Seleccione una opción</option>
									<option value="266">1 | Algún miembro del hogar desempeña sus labores bajo algún riesgo físico como altas temperaturas, bajas temperaturas, baja iluminación, exceso de ruido, en alturas sin protección, cargas pesadas, y demás trabajos que representen riesgos físicos</option>
									<option value="267">2 | Algún miembro del hogar desempeña sus labores bajo algún riesgo químico como: manipulación de químicos para la agricultura, manipulación de pinturas, pegantes y o sellantes de alta concentración en olor, maneja algunos químicos usados en salud y belleza, trabaja en la industria de producción de químicos, trabajos en la producción de pólvoras y otros explosivos, otros trabajos con químicos.</option>
									<option value="268">3 | Algún miembro del hogar desempeña sus labores bajo algún riesgo biológico como: manipulación de alimentos, cárnicos y/o bebidas, manipulación de residuos sólidos hospitalarios, manipulación de residuos provenientes de hogares, trabajos en limpieza de canteras, alcantarillados y cloacas, manipulación de cadáveres, otros trabajos que representen riesgos biológicos. </option>
									<option value="269">3 | Ningún miembro del hogar está expuesto a riesgos laborales. </option>
								</select>
								<label class="colorBlue">93. Riesgos laborales</label>
							</div>

							<div class="input-field col l6">
								<br><br>
								<select class="browser-default" name="consumoAlimentos" required><br>
									<option value="" disabled selected>Seleccione una opción</option>
									<option value="408">1 | Algún miembro del hogar consume solo carbohidratos al día</option>
									<option value="409">2 | Algún miembro del hogar consume solo carbohidratos a la semana</option>
									<option value="410">3 | Algún miembro del hogar consume solo carbohidratos al mes. </option>
									<option value="411">4 | Todos los miembros del hogar consumen carbohidratos, verduras y proteínas diariamente.</option>
								</select>
								<label class="colorBlue">91. Consumo de alimentos</label>
							</div>

							<div class="input-field col l6">
								<br><br>
								<select class="browser-default" name="animalesCasa" required>
									<option value="" disabled selected>Seleccione una opción</option>
									<option value="1">1 | Si</option>
									<option value="0">2 | No</option>
								</select>
								<label class="colorBlue">94. Tenencia de animales <i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="Hace referencia a los animales que se tienen como mascotas. Se excluye la tenencia de animales para sustento como vacuno, avícola, caprino y porcino">live_help</i></label>

								<div id="animales">
									<p>
										<input name="animalesCasaTipo1" type="checkbox" class="filled-in" id="animalesCasaTipo1"  />
										<label for="animalesCasaTipo1">95. En el hogar tienen caninos vacunados</label>

									</p>
									<div class="input-field  animalesCasaTipo1">
										<input name="otraanimalesCasaTipo1" placeholder="Cantidad" type="text" class="validate">
										<label for="" class="colorWhite" >96. ¿Cuántos animales tiene?</label>
									</div>

									<p>
										<input name="animalesCasaTipo2" type="checkbox" class="filled-in" id="animalesCasaTipo2"  />
										<label for="animalesCasaTipo2">97. En el hogar tienen felinos vacunados</label>
									</p>

									<div class="input-field animalesCasaTipo2 ">
										<input name="otraanimalesCasaTipo2" placeholder="Cantidad" type="text" class="validate">
										<label for="" class="colorWhite" >98. ¿Cuántos animales tiene?</label>
									</div>


									<p>
										<input name="animalesCasaTipo3" type="checkbox" class="filled-in" id="animalesCasaTipo3"  />
										<label for="animalesCasaTipo3">99. En el hogar tienen caninos no vacunados</label>
									</p>

									<div class="input-field animalesCasaTipo3 ">
										<input name="otraanimalesCasaTipo3" placeholder="Cantidad" type="text" class="validate">
										<label for="" class="colorWhite" >100. ¿Cuántos animales tiene?</label>
									</div>


									<p>
										<input name="animalesCasaTipo4" type="checkbox" class="filled-in" id="animalesCasaTipo4"  />
										<label for="animalesCasaTipo4">101. En el hogar tienen felinos no vacunados</label>
									</p>

									<div class="input-field  animalesCasaTipo4">
										<input name="otraanimalesCasaTipo4" placeholder="Cantidad" type="text" class="validate">
										<label for="" class="colorWhite" >102. ¿Cuántos animales tiene?</label>
									</div>


									<p>
										<input name="animalesCasaTipo5" type="checkbox" class="filled-in" id="animalesCasaTipo5"  />
										<label for="animalesCasaTipo5">103. En el hogar tienen otro tipo de animales como pájaros, peces, conejos o tortugas entre otros</label>
									</p>

									<div  class="input-field animalesCasaTipo5 ">
										<input name="otraanimalesCasaTipo5" placeholder="Cantidad" type="text" class="validate">
										<label for="" class="colorWhite" >104. ¿Cuántos animales tiene?</label>
									</div>

									<p>
										<input name="animalesCasaTipo6" type="checkbox" class="filled-in" id="animalesCasaTipo6"  />
										<label for="animalesCasaTipo6">105. En el hogar tienen otro tipo de animales</label>
									</p>

									<div  class="input-field animalesCasaTipo6 ">
										<input name="otraanimalesCasaTipo6" placeholder="Cantidad" type="text" class="validate">
										<label for="" class="colorWhite" >106. ¿Cuántos animales tiene?</label>
									</div>
								</div>
							</div>
						
						</div>
							<div class="input-field ">
							    <input name="otrasCondicionesdeVulnerabilidadMiembrosHabitos" placeholder="" id="" type="text" class="validate">
							    <label for="textarea1">Otras condiciones de vulnerabilidad identificadas</label>
						    </div>
					</div>
				</li>

				<li>
					<div class="collapsible-header blue ">Condiciones de vulnerabilidad por situación de salud de los miembros del hogar</div>
					<div class="collapsible-body">
						<div class="row">
							<div class="input-field col l4">
								<br><br><br>
								<select class="browser-default" name="menoresEsquemaincompleto" required>
									<option value="" disabled selected>Seleccione una opción</option>
									<option value="270">1 | En el hogar hay algún(os) menor(es) con esquema de vacunación incompleto</option>
									<option value="271">2 | En el hogar no hay menores con esquema de vacunación incompleto</option>
									<option value="272">2 | En el hogar no hay menores de 5 años</option>
								</select>
								<label class="colorBlue">107. Menores de cinco años con esquema de vacunación incompleto</label>
							</div>

							<div class="input-field col l4">
								<br><br><br>
								<select class="browser-default" name="adultosEnfermedadcronica" required>
									<option value="" disabled selected>Seleccione una opción</option>
									<option value="273">1 | En el hogar hay adultos con diagnóstico de enfermedad crónica no controlada</option>
									<option value="274">2 | En el hogar hay adultos con diagnóstico de enfermedad crónica controlada</option>
									<option value="275">2 | En el hogar no hay adultos con diagnóstico de enfermedad crónica</option>
								</select>
								<label class="colorBlue">108. Adultos con diagnóstico de enfermedad crónica</label>
							</div>

							<div class="input-field col l4">
								<br><br><br>
								<select class="browser-default" name="miembrosSincontrolsexual" required>
									<option value="" disabled selected>Seleccione una opción</option>
									<option value="276">1 | Miembros del hogar en edad reproductiva que no han asistido a asesoría de salud sexual y reproductiva en el último año</option>
									<option value="277">2 | Miembros del hogar en edad reproductiva que no han asistido a asesoría de salud sexual y reproductiva en los últimos seis meses.</option>
								</select>
								<label class="colorBlue">109. Miembros del hogar sin control de salud sexual y reproductiva</label>
							</div>
						</div>

						<div class="row">	
							<div class="input-field col l4">
								<br><br><br><br><br>
								<select class="browser-default" name="alteracionesNutricionales" required>
									<option value="" disabled selected>Seleccione una opción</option>
									<option value="278">1 | Algún miembro del hogar aparenta o relata estar con bajo peso para la edad.</option>
									<option value="279">2 | Algún miembro del hogar aparenta o relata estar en sobrepeso para la edad.</option>
									<option value="280">3 | Algún miembro de la edad relata disminución del apetito.</option>
									<option value="281">4 | Algún miembro del hogar relata preocupación excesiva por el peso actual.</option>
									<option value="282">5 | Algún miembro del hogar ingiere productos no comestibles (plástico, papel, metal, lápices, etc.).</option>
									<option value="283">6 | Algún miembro del hogar aparenta o relata alguna de las situaciones anteriores.</option>
									<option value="284">7 | Ningún miembro del hogar aparenta o relata alteraciones nutricionales.</option>
								</select>
								<label class="colorBlue">110. Signos de alteraciones nutricionales en alguno de los miembros del hogar</label>
							</div>

							<div class="input-field col l4">
								<br><br><br><br><br>
								<select class="browser-default" name="consultaPorEnfermedad" required>
									<option value="" disabled selected>Seleccione una opción</option>
									<option value="1">1 | Si.</option>
									<option value="0">2 | No.</option>				
								</select>
								<label class="colorBlue">111. Algún miembro del hogar consulto en el último mes por enfermedad transmitida por vectores</label>
							</div>

							<div class="input-field col l4">
								<br><br><br><br><br>
								<select class="browser-default" name="lesionesPiel" required>
									<option value="" disabled selected>Seleccione una opción</option>
									<option value="1">1 | Si.</option>
									<option value="0">2 | No.</option>				
								</select>
								<label class="colorBlue">112. Algún miembro del hogar presenta lesiones en la piel
								</label>
							</div>
						</div>

						<div class="row">	
							<div class="input-field col l4">
								<br><br><br><br><br>
								<select class="browser-default" name="violenciaMiembros" required>
									<option value="" disabled selected>Seleccione una opción</option>
									<option value="1">1 | Si.</option>
									<option value="0">2 | No.</option>				
								</select>

								<label class="colorBlue">113. Signos de violencia en alguno de los miembros del hogar
								</label>
							</div>

							<div class="input-field col l4">
								<br><br><br><br><br>
								<select class="browser-default" name="sinControlbucal" required>
									<option value="" disabled selected>Seleccione una opción</option>
									<option value="1">1 | Si.</option>
									<option value="0">2 | No.</option>				
								</select>
								<label class="colorBlue">114. Miembros del hogar sin control de salud bucal en los últimos seis meses
								</label>
							</div>

							<div class="input-field col l4">
								<br><br><br><br><br>
								<select class="browser-default" name="sinAsistenciamedico" required>
									<option value="" disabled selected>Seleccione una opción</option>
									<option value="1">1 | Si.</option>
									<option value="0">2 | No.</option>				
								</select>
								<label class="colorBlue">115. Algún miembro del hogar sin asistencia a control médico en los últimos tres meses o más
								</label>
							</div>
						</div>
						<br>

						<input value="<?php echo BASE_URL; ?>ficha_hogar/consultar" name="oculto" placeholder="" id="oculto" type="hidden" class="validate">
						<div class="input-field ">
							<input name="otrasCondicionesdeVulnerabilidadMiembros" placeholder="" id="" type="text" class="validate">
							<label for="textarea1">Otras condiciones de vulnerabilidad identificadas</label>
						</div>
					</div>
				</li>
				 <div class="row">
		      <div class="row"><br>
		        <div class="input-field col s12">
		          <textarea id="textarea1" class="materialize-textarea" name="observaciones"></textarea>
		          <label for="textarea1">Observaciones</label>
		        
		      </div>
		  </div>
			</ul>
			<br>

                    <div class="row">
                    <div class="input-field col l2">
                    </div>
                    	  <div class="input-field col l3">
                    	<br>
                    	<br>
                    	<br>
                    	  	<select class="browser-default miembroFirma" name="miembroFirma" required >
					          <option value="" disabled selected>Miembro del Hogar que firma</option>
														</select>
														  <label for="">Miembro del hogarque firma <i class=" small tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
				Escoja el miembro que firma la ficha Hogar - Debe diligenciar al menos un miembro 
				">live_help</i></label>
                    	  </div>
                    </div>
															
			<div class="container">
				<div class="row">
					<div class="input-field col s6 ">   
						<input id="firma" type="hidden" name="firma">
						<label for="firma" class="colorBlue">Firma:  <i class=" tiny tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
							Active, dibuje y guarde la firma
							">live_help</i></label>
							<br>    <br>

							<canvas id="canvas" width="400" height="200"></canvas>
						</div>

						<div class="col l6">
							<img id="imagenFirma" src="" alt="">  
						</div>
					</div>

					<div class="row">
						<div class="col l6">

							<div class="switch">
								<label>
									Desactivar
									<input name="1" type="checkbox" id="canvasSwitch" onchange="OnChangeCheckbox()">
									<span class="lever"></span>
									Activar
								</label>

								<br><br>
								<input name="2" class="waves-effect waves-light btn" type="button" value="Guardar" onclick="openNewWindow();">

								<input name="3" class="waves-effect waves-light btn" type="button" value="Limpiar" onclick="limpiar();">
							</div>
						</div>
					</div>
				</div>
			</div>
          
			<center>
				
	<input class="btn-large blue" id="create_account" type="submit" value="Enviar Formulario"> </input> 
			<FONT COLOR="2196f3 "><i class=" small tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="
				Guarde la  firma antes de enviar el formato 
				">live_help</i></FONT>
			</center>

			
		</form>
	</div>

	<script type="text/javascript">


		$(' #ts > tr:eq(0) input[name="dateNacimiento[]"]').change(function(){ 

			var myDate = new Date();
			arreglo = $(this).val().split('/');
			var ano =arreglo[2];
			var mes =arreglo[1];
			var dia =arreglo[0];


			var x=0;
			x=edad(ano,mes,dia);
//alert(x);
$('#ts > tr:eq(0) .edad ').val(x);

});

		$('.datepicker').pickadate({
			selectYears: 200 , 
			selectMonths: true,
			monthsFull: [ 'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre' ],
			monthsShort: [ 'ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic' ],
			weekdaysFull: [ 'domingo', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado' ],
			weekdaysShort: [ 'dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb' ],
			weekdaysLetter:["D","L","M","M","J","V","S"],
			today: 'Hoy',
			clear: 'Borrar',
			close: 'Aceptar',
			firstDay: 1,
			format: 'dd/mm/yyyy',
			min: new Date(1900,01,01),
			max: new Date()



		});



		function edad($var1,$var2,$var3){
			var myDate = new Date();
			$anos =  (myDate.getFullYear()) - $var1;  
			$meses = (myDate.getMonth()+(1)) - $var2; 
			$dias =  (myDate.getDate()) - $var3; 


			if ($dias < 0) 
			{ 
				--$meses; 

				switch ((myDate.getMonth()+(1))) { 
					case 1:     $dias_mes_anterior=31; break; 
					case 2:     $dias_mes_anterior=31; break; 
					case 3:  
					if (bisiesto( (myDate.getFullYear()) )) 
					{ 
						$dias_mes_anterior=29; break; 
					} else { 
						$dias_mes_anterior=28; break; 
					} 
					case 4:     $dias_mes_anterior=31; break; 
					case 5:     $dias_mes_anterior=30; break; 
					case 6:     $dias_mes_anterior=31; break; 
					case 7:     $dias_mes_anterior=30; break; 
					case 8:     $dias_mes_anterior=31; break; 
					case 9:     $dias_mes_anterior=31; break; 
					case 10:     $dias_mes_anterior=30; break; 
					case 11:     $dias_mes_anterior=31; break; 
					case 12:     $dias_mes_anterior=30; break; 
				} 

				$dias=$dias + $dias_mes_anterior; 
			} 


			if ($meses < 0) 
			{ 
				--$anos; 
				$meses=$meses + 12; 
			} 

			if ($anos != 0) {
				return  $anos+" Años";
			}else if ($meses != 0) {
				return  $meses+" Meses";
			}else{
				return  $dias+" Dias";
			}


		}


firma1();
function firma1(){

 $(".name1").change(function(){
 	 var documento= Array();
     $(".miembroFirma option").remove();
     $('.miembroFirma ').append('<option value="" disabled selected>Miembro del Hogar que firma</option>');
 
      $("input[name='docIdentidad[]'").each(function(indice, elemento) {
      	
      	 documento[indice]=$(this).val();

      });

      $(".name1").each(function(indice, elemento) {
      	
      	$('.miembroFirma ').append('<option value="'+documento[indice]+'" >'+$(this).val()+'</option>');

      });

 });


 $("input[name='docIdentidad[]'").change(function(){
 	 var documento= Array();
     $(".miembroFirma option").remove();
     $('.miembroFirma ').append('<option value="" disabled selected>Miembro del Hogar que firma</option>');
 
      $("input[name='docIdentidad[]'").each(function(indice, elemento) {
      	
      	 documento[indice]=$(this).val();

      });

      $(".name1").each(function(indice, elemento) {
      	
      	$('.miembroFirma ').append('<option value="'+documento[indice]+'" >'+$(this).val()+'</option>');

      });

 });


}
		function bisiesto($anio_actual){ 
			$bisiesto=false; 
			if (isValidDate(2,29,$anio_actual)) 
			{ 
				$bisiesto=true; 
			} 
			return $bisiesto; 
		} 

		Eps("<?php echo BASE_URL; ?>ficha_hogar/consultar");

   //		$(document).ready(function() {
   /* $('#create_account').click(function(){

				var dataString = $('#hogar').serialize();

				alert('Datos serializados: '+dataString);

				$.ajax({
					type: "POST",
					url: "/ProyectoAps/ficha_hogar/ingresar",
					data: dataString,
					success: function(data) {

						alert("Datos Enviados con exito"+data);
					}
				});
			});
			*/

	//	});

jQuery.validator.setDefaults({
  debug: true,
  success: "valid",
  ignore: []
});

$("#hogar").validate({
  submitHandler: function(form) {
   
    form.submit();
  }

});
	</script>
