<input type="text" hidden="true" value="<?php echo count($this->ficha_hogar);?>" id="datosFicha">
<input type="text" hidden="true" value="<?php echo count($this->aiepi);?>" id="datosAiepi">
<input type="text" hidden="true" value="<?php echo count($this->kardex);?>" id="datosKardes">
<input type="text" hidden="true" value="<?php echo count($this->cancer_mama);?>" id="datosCancer">
<input type="text" hidden="true" value="<?php echo count($this->findrisk);?>" id="datosFindrisk">
<input type="text" hidden="true" value="<?php echo count($this->demanda_inducida);?>" id="datosDemanda">

<h2>INDICADORES</h2>