<center><p class="titulo">Cancer de Mama</p></center>
      
<form action="u.html" id="hogar">
	<div class="row">

		<div class="input-field col s12 l6">

			<div class="input-field ">
				<input placeholder="Nombre" id="" type="text" class="validate">
				<label for="">Nombre</label>
			</div>
			<div class="input-field ">
				<input placeholder="ID" id="" type="text" class="validate">
				<label for="">ID</label>
			</div>
			<div class="input-field ">
				<input placeholder="Email" id="" type="email" class="validate">
				<label for="">Email</label>
			</div>	


		</div>
		<div class="input-field col s12 l6">

			<br>

			<label for="" class="preguntas cancerMama0">Tipo de afiliación al sistema de salud  * <i class="material-icons  mensage" id='p0'>live_help</i>
			
			</label>	
			
				<div class="ventana p0">
		
			</div>
			
			<br>				
			<p>
				<input name="cancerMama0" type="radio" id="t1"  value="0"/>
				<label class="respuestas" for="t1">Contributivo	</label>
                     <br class="contributivo"> <br class="contributivo">
				<div class="input-field  contributivo">
					<input placeholder="" name="" id="" type="text" class="validate">
					<label for="">Cual?</label>

				</div>

			</p>


			<p>
				<input name="cancerMama0" type="radio" id="t2" value="3" />
				<label class="respuestas" for="t2"> Subsidiado      </label>
				     <br class="subsidiado"> <br class="subsidiado">
				<div class="input-field subsidiado">
					<input placeholder="" name="" id="" type="text" class="validate">
					<label for="">Cual?</label>

				</div>


			</p>
			<p>
				<input name="cancerMama0" type="radio" id="t3"  value="5"/>
				<label class="respuestas" for="t3"> No tengo afiliación </label>
			</p>
			<p>
				<input name="cancerMama0" type="radio" id="t4"  value="5"/>
				<label class="respuestas" for="t4"> Vinculado </label>
			</p>

		</div>

	</div>

	<p id='respuestaRiesgo'></p>

	<div class="row">
		<div class="input-field col s12 l6">

			<br>

			<label for="" class="preguntas  cancerMama1">1.Edad en años cumplidos  *</label>	<br>				
			<div class="input-field">
				<input id="" type="text" class="validate">
				<label for=""></label>
			</div>


		</div>
		<div class="input-field col s12 l6">

			<br>

			<label for="" class="preguntas findrisk2">2.¿Ha tenido Cáncer de Seno su mamá? *</label>	
			<br>				
			<p>
				<input name="cancerMama2" type="radio" id="t5"  value="si"/>
				<label class="respuestas" for="t5">SI </label>
			</p>
			<p>
				<input name="cancerMama2" type="radio" id="t6" value="no" />
				<label class="respuestas" for="t6">No </label>
			</p>
			<p>
				<input name="cancerMama2" type="radio" id="t7" value="noSabe"  />
				<label class="respuestas" for="t7">No sabe </label>
			</p>


		</div>

	</div>


	<div class="row">
		<div class="input-field col s12 l6">

			<br>

			<label for="" class="preguntas  cancerMama1">3.¿Le han practicado biopsia  en el seno? *</label>	<br>				
			<p>
				<input name="cancerMama3" type="radio" id="t8"  value="si"/>
				<label class="respuestas" for="t8">SI </label>
			</p>
			<p>
				<input name="cancerMama3" type="radio" id="t9" value="no" />
				<label class="respuestas" for="t9">No </label>
			</p>


		</div>
		<div class="input-field col s12 l6">

			<br>

			<label for="" class="preguntas findrisk2">4. ¿ Ha tenido Cáncer de mama su  hermana(o) ? *</label>	
			<br>				
			<p>
				<input name="cancerMama4" type="radio" id="t10"  value="si"/>
				<label class="respuestas" for="t10">SI </label>
			</p>
			<p>
				<input name="cancerMama4" type="radio" id="t11" value="no" />
				<label class="respuestas" for="t11">No </label>
			</p>
			<p>
				<input name="cancerMama4" type="radio" id="t12" value="noSabe"  />
				<label class="respuestas" for="t12">No sabe </label>
			</p>


		</div>

	</div>


	<div class="row">
		<div class="input-field col s12 l6">

			<br>

			<label for="" class="preguntas  cancerMama1">5. ¿ Si tiene más de 50 años le han praticado alguna vez una mamografía? *</label>	<br>				
			<p>
				<input name="cancerMama5" type="radio" id="t13"  value="no"/>
				<label class="respuestas" for="t13">No </label>
			</p>
			<p>
				<input name="cancerMama5" type="radio" id="t14" value="Si-hace-menos-de-dos-años" />
				<label class="respuestas" for="t14">Si, hace menos de dos años </label>
			</p>
			<p>
				<input name="cancerMama5" type="radio" id="t15" value="Sí-hace-mas-de-dos-años" />
				<label class="respuestas" for="t15">Sí, hace mas de dos años </label>
			</p>


		</div>
		<div class="input-field col s12 l6">

			<br>

			<label for="" class="preguntas findrisk2">6. De los signos descritos a continuación se le ha presentado: *</label>	
			<br>				
			<p>
				<input name="cancerMama6" type="radio" id="t16"  value="si"/>
				<label class="respuestas" for="t16">Aparición de un bulto o masas en los senos </label>
			</p>
			<p>
				<input name="cancerMama6" type="radio" id="t17" value="no" />
				<label class="respuestas" for="t17">Aumento en el tamaño de un bulto o masas en los senos </label>
			</p>
			<p>
				<input name="cancerMama6" type="radio" id="t18" value="noSabe"  />
				<label class="respuestas" for="t18">Secreción o sangrado en los senos </label>
			</p>
			<p>
				<input name="cancerMama6" type="radio" id="t19" value="noSabe"  />
				<label class="respuestas" for="t19">Aumento en el tamaño de los senos</label>
			</p>
			<p>
				<input name="cancerMama6" type="radio" id="t20" value="noSabe"  />
				<label class="respuestas" for="t20">Cambio de posición del pezón</label>
			</p>
			<p>
				<input name="cancerMama6" type="radio" id="t21" value="noSabe"  />
				<label class="respuestas" for="t21">Ninguno</label>
			</p>


		</div>

	</div>

</form>
<br><br>
