<div class="container">
		<h6 class="titulo" align="center" style = "font-size:35px; color:#2196f3">CÁNCER DE MAMA</h6>

		<form action="<?php echo BASE_URL.'cancer_mama/nuevo/'.$this->datos['ID_TAREA'];?>" method="post" id="hogar" name="hogar" onsubmit="return(ValidaForm());">
			<input type="hidden" name="guardar" value="1" />

			<div class="row">
				<div class="input-field col s12 l6">

					<div class="input-field col s6">
						<input id="nombre" type="text" class="validate" name="nombre" value="<?php echo $this->datosMiembro['NOMBRE_MIEMBRO']; ?>" disabled>
						<label for="nombre">Nombres</label>
					</div>

					<div class="input-field col s6">
						<input id="apellido" type="text" class="validate" name="apellido" value="<?php echo $this->datosMiembro['APELLIDO_MIEMBRO']; ?>">
						<label for="">Apellidos</label>
					</div>

					<div class="input-field col s12">
						<input id="documento" type="text" class="validate" name="documento" value="<?php echo $this->datosMiembro['IDENTIFICACION_MIEMBRO_HOGAR']; ?>" disabled pattern="[0-9]*" title="Solo se aceptan números">
						<label for="">N. documento de identidad</label>
					</div>
					<div class="input-field col s12">
						<input id="email" type="email" class="validate" name="email">
						<label for="">Email</label>
					</div>	
						

					<div class="input-field col s6">
						<input id="barrio" type="text" class="validate" name="barrio" value="<?php echo $this->datosMiembro['DES_BARRIO']; ?>" disabled>
						<label for="">Barrio</label>
					</div>	

					<div class="input-field col s6">
						<input id="municipio" type="text" class="validate" name="municipio" value="<?php echo $this->datosMiembro['DES_MUNICIPIO']; ?>" disabled>
						<label for="">Municipio</label>
					</div>	
				</div>

				<div class="input-field col s12 l6">

					<br>
					<label for="" class="preguntas cancerMama0">Tipo de afiliación al sistema de salud* 
						<i id='p0' class="tooltipped material-icons" data-delay="50" data-tooltip="Ayuda" data-position="right">help</i>
					</label>	

					<br>				
					<p>
						<input name="cancerMama0" type="radio" id="t1"  value="1"/>
						<label class="respuestas" for="t1">Contributivo	</label>
						<br class="contributivo"> <br class="contributivo">
						<div class="input-field  contributivo">
							<input placeholder="" name="contributivo" id="contributivo" type="text" class="validate">
							<label for="">¿Cual?</label>
						</div>
					</p>

					<p>
						<input name="cancerMama0" type="radio" id="t2" value="2" />
						<label class="respuestas" for="t2"> Subsidiado      </label>
						<br class="subsidiado"> <br class="subsidiado">
						<div class="input-field subsidiado">
							<input placeholder="" name="subsidiado" id="subsidiado" type="text" class="validate">
							<label for="">¿Cual?</label>
						</div>
					</p>

					<p>
						<input name="cancerMama0" type="radio" id="t3"  value="3"/>
						<label class="respuestas" for="t3"> No tengo afiliación </label>
					</p>
					<p>
						<input name="cancerMama0" type="radio" id="t4"  value="4"/>
						<label class="respuestas" for="t4"> Vinculado </label>
					</p>
				</div>
			</div>

			<br>

			<hr style="color:#2196f3">

			<div class="row">
				<div class="input-field col s12 l6">
					<br>
					<label for="" class="preguntas  cancerMama1">1. Edad en años cumplidos*</label>	<br>				
					<div class="input-field">
						<input placeholder="Edad" id="name" type="text" class="validate" name="edad" value="<?php echo $this->datosMiembro['EDAD']; ?>" disabled pattern="[0-9]*" title="Solo se aceptan números">
					</div>
				</div>

				<div class="input-field col s12 l6">
					<br>
					<label for="" class="preguntas findrisk2">2.¿Ha tenido cáncer de seno su mamá?*</label>	
					<br>				
					<p>
						<input name="cancerMama2" type="radio" id="t5"  value="1"/>
						<label class="respuestas" for="t5">Si </label>
					</p>
					<p>
						<input name="cancerMama2" type="radio" id="t6" value="0" />
						<label class="respuestas" for="t6">No </label>
					</p>
					<p>
						<input name="cancerMama2" type="radio" id="t7" value="2"  />
						<label class="respuestas" for="t7">No sabe </label>
					</p>
				</div>
			</div>

			<div class="row">
				<div class="input-field col s12 l6">
					<br>
					<label for="" class="preguntas  cancerMama1">3. ¿Le han practicado biopsia en el seno?*</label>	<br>				
					<p>
						<input name="cancerMama3" type="radio" id="t8"  value="1"/>
						<label class="respuestas" for="t8">Si </label>
					</p>
					<p>
						<input name="cancerMama3" type="radio" id="t9" value="0" />
						<label class="respuestas" for="t9">No </label>
					</p>
				</div>

				<div class="input-field col s12 l6">
					<br>
					<label for="" class="preguntas findrisk2">4. ¿ Ha tenido cáncer de mama su hermana(o)?*</label>	
					<br>				
					<p>
						<input name="cancerMama4" type="radio" id="t10"  value="1"/>
						<label class="respuestas" for="t10">Si </label>
					</p>
					<p>
						<input name="cancerMama4" type="radio" id="t11" value="0" />
						<label class="respuestas" for="t11">No </label>
					</p>
					<p>
						<input name="cancerMama4" type="radio" id="t12" value="2"  />
						<label class="respuestas" for="t12">No sabe </label>
					</p>
				</div>
			</div>

			<div class="row">
				<div class="input-field col s12 l6">
					<br>
					<label for="" class="preguntas  cancerMama1">5. ¿Si tiene más de 50 años le han praticado alguna vez una mamografía?*</label>	
					<br><br>	<br>			
					<p>
						<input name="cancerMama5" type="radio" id="t13"  value="0"/>
						<label class="respuestas" for="t13">No </label>
					</p>
					<p>
						<input name="cancerMama5" type="radio" id="t14" value="l" />
						<label class="respuestas" for="t14">Si, hace menos de dos años </label>
					</p>
					<p>
						<input name="cancerMama5" type="radio" id="t15" value="2" />
						<label class="respuestas" for="t15">Sí, hace mas de dos años </label>
					</p>
				</div>

				<div class="input-field col s12 l6">
					<br>
					<label for="" class="preguntas findrisk2">6. De los signos descritos a continuación se le ha presentado:*</label>	
					<br>				
					<p>
						<input name="cancerMama6-1" type="checkbox" id="t16"  value="48" class="group1" />
						<label class="respuestas" for="t16">Aparición de un bulto o masas en los senos </label>
					</p>
					<p>
						<input name="cancerMama6-2" type="checkbox" id="t17" value="49" class="group1">
						<label class="respuestas" for="t17">Aumento en el tamaño de un bulto o masas en los senos </label>
					</p>
					<p>
						<input name="cancerMama6-3" type="checkbox" id="t18" value="50" class="group1">
						<label class="respuestas" for="t18">Secreción o sangrado en los senos </label>
					</p>
					<p>
						<input name="cancerMama6-4" type="checkbox" id="t19" value="51" class="group1">
						<label class="respuestas" for="t19">Aumento en el tamaño de los senos</label>
					</p>
					<p>
						<input name="cancerMama6-5" type="checkbox" id="t20" value="52" class="group1">
						<label class="respuestas" for="t20">Cambio de posición del pezón</label>
					</p>
					<p>
						<input name="cancerMama6-6" type="checkbox" id="t21" value="53">
						<label class="respuestas" for="t21">Ninguno</label>
					</p>
				</div>
			</div>

			<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
				<a class="floating "><img src="<?php echo $_layoutParams['ruta_img']; ?>cangura.png"></a>
			</div>

			<br><br>

			<center>
				<button class="btn-large waves-effect waves-light blue " type="submit" name="action" onClick="validarFormulario()">ENVIAR
				<i class="material-icons right">send</i>
				</button>
			</center>
		</form>
		</div>

