<center><p class="titulo" style = "font-size:35px; color:#2196f3" >CONSULTAS</p></center>

<div class="container">
	<div class="row">
		<div class="card">
			<div class="card-content">
				<span class="card-title blue-text">Opciones de búsqueda:</span>
				<form action="<?php echo BASE_URL; ?>consultas/consultar" method="Post" name="consultForm" id="consultForm">
					<div class="row">
						<div class="input-field col l3">
							<input class="with-gap" name="opConsulta" type="radio" id="opDoc"  value="1" />
							<label for="opDoc">Número de documento</label>
						</div>

						<div class="input-field col l2">
							<input class="with-gap" name="opConsulta" type="radio" id="opNombre" value="2" />
							<label for="opNombre">Nombre</label>
						</div>

						<div class="input-field col l2">
							<input class="with-gap" name="opConsulta" type="radio" id="opApellido" value="3" />
							<label for="opApellido">Apellido</label>
						</div>

						<div class="input-field col l2">
							<input class="with-gap" name="opConsulta" type="radio" id="opRangoFechas"  value="4" />
							<label for="opRangoFechas">Rango de fechas</label>
						</div>

						<div class="input-field col l2">
							<input class="with-gap" name="opConsulta" type="radio" id="opNumFicha" value="5"  />
							<label for="opNumFicha">Número de ficha</label>
						</div>
					</div>

					<br>

					<div class="row">
						<div class="input-field col l6  offset-l3" id="divOpDoc">
							<i class="material-icons prefix">search</i>
							<input type="text" id="docBuscarFormato" placeholder="Buscar" name="docBuscarFormato" >
							<label for="docBuscarFormato">Documento de identificación</label>
						</div>

						<div class="input-field col l6  offset-l3" id="divOpNombre">
							<i class="rSmall material-icons prefix">search</i>
							<input type="text" id="nomBuscarFormato" placeholder="Buscar" name="nomBuscarFormato">
							<label for="nomBuscarFormato">Nombre de la persona</label>
						</div>

						<div class="input-field col l6  offset-l3" id="divOpApellido">
							<i class="small material-icons prefix">search</i>
							<input type="text" id="apeBuscarFormato" placeholder="Buscar" name="apeBuscarFormato">
							<label for="apeBuscarFormato">Apellido de la persona</label>
						</div>

						<div class="input-field col l12" id="divOpRangoFechas">
							<div class="input-field col l6">
								<i class="material-icons prefix">search</i>
								<input type="text" id="fechaInicioBuscFormato" placeholder="Fecha" name="fechaInicioBuscFormato" class="datepicker">
								<label for="fechaInicioBuscFormato">Fecha inicial</label>
							</div>

							<div class="input-field col l6">
								<i class="material-icons prefix">search</i>
								<input type="text" id="fechaFinBuscarFormato" placeholder="Fecha" name="fechaFinBuscarFormato" class="datepicker">
								<label for="fechaFinBuscarFormato">Fecha final</label>
							</div>
						</div>

						<div class="input-field col l6  offset-l3" id="divOpNumFicha">
							<i class="small material-icons prefix">search</i>
							<input type="text" id="numFichaBuscarFormato" placeholder="Buscar" name="numFichaBuscarFormato">
							<label for="numFichaBuscarFormato">Número de la ficha</label>
						</div>
					</div>

					<center>
						<button class="btn-large waves-effect waves-light blue" type="submit" name="action">CONSULTAR
							<i class="material-icons right">search</i>
						</button>
					</center>

				</form>
			</div>
		</div>

		<?php if (isset($this->fichaHogar)) {?>

			<div class="row">
				<div class="input-field s12">
					<table class="centered bordered">
						<thead>
							<tr>
								<th data-field="id"><FONT COLOR="2196f3 ">Identificación<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="De clic en el número de documento de identidad para ver los formatos asociados">live_help</i></FONT></th>
								<th data-field="name"><FONT COLOR="2196f3 ">Nombre</FONT></th>
								<th data-field="price"><FONT COLOR="2196f3 ">EPS</FONT></th>
								<th data-field="price"><FONT COLOR="2196f3 ">Ficha hogar</FONT></th>
							</tr>
						</thead>
						<?php
						for ($i=0; $i < count($this->fichaHogar); $i++) { ?>
							<tbody>
								<tr>
									<td>
										<button class="waves-effect btn blue modal-trigger" href="#modal1" id="h<?php echo $i;?>" value="<?php echo $this->fichaHogar[$i]['IDENTIFICACION_MIEMBRO_HOGAR'];?>"><?php echo $this->fichaHogar[$i]['IDENTIFICACION_MIEMBRO_HOGAR'];?>
										</button>
									</td>
									<td><?php echo $this->fichaHogar[$i]['NOMBRE_MIEMBRO'];?></td>
									<td><?php echo $this->fichaHogar[$i]['DES_EPS'];?></td>
									<td>
										<button class="waves-effect waves-light btn blue" id="fichaHogarSearch<?php echo $i;?>" value="<?php echo $this->fichaHogar[$i]['FICHA_HOGAR_ID_FIC_HOGAR'];?>"><?php echo $this->fichaHogar[$i]['ID_HOGAR'];?>
										</button>
									</td>
								</tr>
							</tbody>
							<?php 
			} 
			?>
						</table>
					</div>
				</div>

				
			<?php 
		} 
		?>
<input type="text" hidden="true" id="contador" value="<?php echo $i;?>">
		<div class="row">
			<div id="modal1" class="modal">
				<div class="modal-content" id="contFormatos">
				</div>
				<div class="modal-footer">
					<a href="#!" class=" modal-action modal-close btn-flat white-text red">Cerrar</a>
				</div>
			</div>
		</div>

	</div>
</div>