<div class="container">
	<br><br>	
	<h6 class="titulo" align="center" style = "font-size:55px; color:#2196f3"><font face="GillSans, Calibri, Trebuchet, sans-serif">BIENVENIDO</font></h6>
	<h5 class="card-title blue-text" align="center" style= "font-size:20px; font-weight: normal; color:#2196f3"">Inicie sesión para ingresar al sistema<i class="tooltipped material-icons" data-position="top" data-delay="50" data-tooltip="Para iniciar sesión haga clic en la imágen"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></h5 align="center">
		<br><br>

		<div class="card hoverable">
		<br><br>
			<div class="card-image waves-effect waves-block waves-light">
				<img class="activator" src="<?php echo $_layoutParams['ruta_img']; ?>familia.jpg">
			</div>
			<br><br><br>
			<div class="card-reveal hoverable">
				<div class="row">
					<div class="col s12">
						<span class="card-title blue-grey-text text-darken-4"> <i class="small material-icons right"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>close.png"></i></span>
						<br><br><br>

						<h4 align="center" style="font-size: 45px; font-weight: normal; color:#2196f3">Iniciar sesi&oacute;n</h4>
						<br>
						<form name="form1" method="post" action="<?php echo BASE_URL; ?>login">
							<br>
							<input type="hidden" value="1" name="enviar" />
							<div class="row">

								<div class="input-field col s6 offset-s3">
									<label for="usuario">Usuario</label>
									<input type="text" placeholder=" " name="usuario" value="<?php if(isset($this->datos)) echo $this->datos['usuario'];?>">
								</div>

								<br><br><br><br>

								<div class="input-field col s6 offset-s3">
									<label for="pass">Contraseña</label>
									<input type="password" placeholder=" " name="pass">
								</div>

								<br><br> <br> <br>

								<div class="input-field col s6 offset-s3">
									<center>
										<button class="waves-effect waves-light btn-large blue" type="submit" name="action">Ingresar</button>
									</center>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>

<!-- 		<h4>Así vamos:</h4>
		<ul>
			<li>
				<a href="<?php echo BASE_URL?>ficha_hogar">Ficha Hogar</a>
				<div class="progress">
					<div class="determinate" style="width: 10%"></div>
				</div>
			</li>
			<li>
				<a href="<?php echo BASE_URL?>findrisk">Findrisk</a>
				<div class="progress">
					<div class="determinate" style="width: 75%"></div>
				</div>
			</li>
			<li>
				<a href="<?php echo BASE_URL?>cancer_mama">Cancer de mama</a>
				<div class="progress">
					<div class="determinate" style="width: 65%"></div>
				</div>
			</li>
			<li>
				<a href="<?php echo BASE_URL?>aiepi">Ficha AIEPI</a>
				<div class="progress">
					<div class="determinate" style="width: 20%"></div>
				</div>
			</li>
			<li>
				<a href="<?php echo BASE_URL?>demanda_inducida">Demanda Inducida</a>
				<div class="progress">
					<div class="determinate" style="width: 75%"></div>
				</div>
			</li>
			<li>
				<a href="<?php echo BASE_URL?>kardes">Kardex de Gestantes</a>
				<div class="progress">
					<div class="determinate" style="width: 60%"></div>
				</div>
			</li>
		</ul> -->
	</div>



