<div class="container">
	<h2>Bienvenido </h2>
	<h4>Así vamos:</h4>
	<ul>
		<li>
			<a href="<?php echo BASE_URL?>ficha_hogar">Ficha Hogar</a>
			<div class="progress">
		      	<div class="determinate" style="width: 10%"></div>
		  	</div>
		</li>
		<li>
			<a href="<?php echo BASE_URL?>findrisk">Findrisk</a>
			<div class="progress">
		      	<div class="determinate" style="width: 75%"></div>
		  	</div>
		</li>
		<li>
			<a href="<?php echo BASE_URL?>cancer_mama">Cancer de mama</a>
			<div class="progress">
		      	<div class="determinate" style="width: 65%"></div>
		  	</div>
		</li>
		<li>
			<a href="<?php echo BASE_URL?>aiepi">Ficha AIEPI</a>
			<div class="progress">
		      	<div class="determinate" style="width: 20%"></div>
		  	</div>
		</li>
		<li>
			<a href="<?php echo BASE_URL?>demanda_inducida">Demanda Inducida</a>
			<div class="progress">
		      	<div class="determinate" style="width: 75%"></div>
		  	</div>
		</li>
		<li>
			<a href="<?php echo BASE_URL?>kardes">Kardex de Gestantes</a>
			<div class="progress">
		      	<div class="determinate" style="width: 60%"></div>
		  	</div>
		</li>
	</ul>
</div>



