<h2>Bienvenido </h2>
<h4>Así vamos:</h4>
<ul>
	<li>
		<a href="<?php echo BASE_URL?>ficha_hogar">Ficha Hogar</a>
		<div class="progress">
	      	<div class="determinate" style="width: 10%"></div>
	  	</div>
	</li>
	<li>
		<a href="<?php echo BASE_URL?>findrisk">Find Risk</a>
		<div class="progress">
	      	<div class="determinate" style="width: 25%"></div>
	  	</div>
	</li>
	<li>
		<a href="<?php echo BASE_URL?>cancer_mama">Cancer de mama</a>
		<div class="progress">
	      	<div class="determinate" style="width: 30%"></div>
	  	</div>
	</li>
	<li>
		<a href="<?php echo BASE_URL?>aiepi">Ficha AIEPI</a>
		<div class="progress">
	      	<div class="determinate" style="width: 20%"></div>
	  	</div>
	</li>
	<li>
		<a href="<?php echo BASE_URL?>demanda_inducida">Demanda Inducida</a>
		<div class="progress">
	      	<div class="determinate" style="width: 10%"></div>
	  	</div>
	</li>
	<li>
		<a href="<?php echo BASE_URL?>">Kardex de Gestantes</a>
		<div class="progress">
	      	<div class="determinate" style="width: 0%"></div>
	  	</div>
	</li>
</ul>


