;<div class="container">
	<h2 class="center" style="color:#2196f3" >FORMATOS PENDIENTES</h2>
	<br><br>
	<div class="row">
		<div class="input-field col s12 m12">
				<table class="bordered centered bordered">
					<thead>
						<tr>
							<th>N&uacute;mero Ficha Hogar</th>
							<th>Kardex de Gestantes</th>
							<th>Cancer de mama</th>
							<th>Ficha AIEPI</th>
							<th>Test Findrisk</th>
							<th>Demanda Inducida</th>
						</tr>
					</thead>
					
					<tbody class="center">
						<?php $cero = 'blue lighten-4';
							$masdeuno = 'pink lighten-3' ?>
						<?php if(isset($this->pendientes)) : ?>
							<?php for($i = 0; $i < count($this->pendientes); $i++):?>
								<tr>
									<td class="center">
										<a href="<?php echo BASE_URL.'hoja_trabajo/editar/'.$this->pendientes[$i][0]['FICHA_HOGAR_ID_FIC_HOGAR']; ?>"><?php echo $this->pendientes[$i][0]['ID_HOGAR']; ?></a>
									</td>
									
									<?php if ($this->pendientes[$i][0]['KARDES'] != 0) { $color = $masdeuno;
									}else{	$color = $cero; } ?>

									<td class="center <?php echo $color; ?>">
										<a class="black-text" href="<?php echo BASE_URL.'hoja_trabajo/editar/'.$this->pendientes[$i][0]['FICHA_HOGAR_ID_FIC_HOGAR']; ?>"><?php echo $this->pendientes[$i][0]['KARDES']; ?></a>
									</td>
									
									<?php if ($this->pendientes[$i][0]['CANCER_MAMA'] != 0) { $color = $masdeuno;
									}else{	$color = $cero; } ?>

									<td class="center <?php echo $color; ?>">
										<a class="black-text" href="<?php echo BASE_URL.'hoja_trabajo/editar/'.$this->pendientes[$i][0]['FICHA_HOGAR_ID_FIC_HOGAR']; ?>"><?php echo $this->pendientes[$i][0]['CANCER_MAMA']; ?></a>
									</td>

									<?php if ($this->pendientes[$i][0]['AIEPI'] != 0) { $color = $masdeuno;
									}else{	$color = $cero; } ?>

									<td class="center <?php echo $color; ?>">
										<a class="black-text" href="<?php echo BASE_URL.'hoja_trabajo/editar/'.$this->pendientes[$i][0]['FICHA_HOGAR_ID_FIC_HOGAR']; ?>"><?php echo $this->pendientes[$i][0]['AIEPI']; ?></a>
									</td>

									<?php if ($this->pendientes[$i][0]['FINDRISK'] != 0) { $color = $masdeuno;
									}else{	$color = $cero; } ?>

									<td class="center <?php echo $color; ?>">
										<a class="black-text" href="<?php echo BASE_URL.'hoja_trabajo/editar/'.$this->pendientes[$i][0]['FICHA_HOGAR_ID_FIC_HOGAR']; ?>"><?php echo $this->pendientes[$i][0]['FINDRISK']; ?></a>
									</td>

									<?php if ($this->pendientes[$i][0]['DEMANDA_INDUCIDA'] != 0) { $color = $masdeuno;
									}else{	$color = $cero; } ?>

									<td class="center <?php echo $color; ?>">
										<a class="black-text" href="<?php echo BASE_URL.'hoja_trabajo/editar/'.$this->pendientes[$i][0]['FICHA_HOGAR_ID_FIC_HOGAR']; ?>"><?php echo $this->pendientes[$i][0]['DEMANDA_INDUCIDA']; ?></a>
									</td>
									
								</tr>
							<?php endfor;?>
						<?php endif; ?>
					</tbody>
				</table>		
			</div>
	</div>

	<br>
	<br>
	<br>
	<br>
	<br>
	<br>

	
</div>
