<div class="container">
	<center><p class="titulo" style = "font-size:45px; color:#2196f3" >SINCRONIZACIÓN</p>
	<p>Recuerda que para poder sincronizar desbes estar conectado</p>
	<div class="row">
		<div class="col l6">
			<form action="<?php echo BASE_URL; ?>sincronizar/sincronizarm" method="Post">
				<button class="btn-large waves-effect waves-light blue">Sincronizar con el servidor</button>
	
			</form>
		</div>
		<div class="col l6">
			<form action="<?php echo BASE_URL; ?>sincronizar/sincronizarBajarm" method="Post">
				<button class="btn-large waves-effect waves-light blue " >Descargar localmente</button>
				
			</form>
		</div>
	</div>
	</center>
</div>

<script type="text/javascript">
	/*
	$(document).ready(function() {

    $('#create_account').click(function(){

          var dataString ="Sincronizar";

        alert('Datos serializados: '+dataString);

        $.ajax({
            type: "POST",
             url: "/ProyectoAps/sincronizar/sincronizarm",
            data: dataString,
            success: function(data) {

         alert("Datos Enviados con exito"+data);
            }
        });
    });

});
*/
</script>