<div class="container">
	<div class="row">
		<div class="col l6">
			<form action="<?php echo BASE_URL; ?>sincronizar/sincronizarm" method="Post">
				<button>Sincronizar al servidor</button>
	
			</form>

			<form action="<?php echo BASE_URL; ?>sincronizar/sincronizarBajarm" method="Post">
				<button>Sincronizar Al local</button>
				<p class="bnt" id="create_account">dfsdf	</p>
			</form>


		</div>
	</div>
</div>

<script type="text/javascript">
	/*
	$(document).ready(function() {

    $('#create_account').click(function(){

          var dataString ="Sincronizar";

        alert('Datos serializados: '+dataString);

        $.ajax({
            type: "POST",
             url: "/ProyectoAps/sincronizar/sincronizarm",
            data: dataString,
            success: function(data) {

         alert("Datos Enviados con exito"+data);
            }
        });
    });

});
*/
</script>