<div class="container">
	<center><p class="titulo" style = "font-size:45px; color:#2196f3" ></p></center>
	
	<?php if (Session::get('level') == 'USUARIO'): ?>
		<div class="row">
			<div class="col s4">
				<div class="card indigo darken-2">
					<div class="card-image">
						<img src="<?php echo $_layoutParams['ruta_img']; ?>2.jpg">
					</div>
					<div class="card-content white-text">
						<span class="card-title">FICHA HOGAR</span>
						<p>Aquí podrá registar nuevos usuarios en el sistema.</p>
					</div>
					<div class="card-action">
						<a class="white-text" href="<?php echo BASE_URL?>ficha_hogar">Clic aquí para ir</a>
					</div>
				</div>
			</div>		

			<div class="col s4">
				<div class="card blue-grey darken-2">
					<div class="card-image">
						<img src="<?php echo $_layoutParams['ruta_img']; ?>3.jpg">
					</div>
					<div class="card-content white-text">
						<span class="card-title">PENDIENTES</span>
						<p>Aquí podra ver los formatos que hacen falta por diligenciar.</p>
					</div>
					<div class="card-action">
						<a class="white-text" href="<?php echo BASE_URL?>hoja_trabajo/">Clic aquí para ir</a>
					</div>
				</div>
			</div>

			<div class="col s4">
				<div class="card pink darken-2">
					<div class="card-image">
						<img src="<?php echo $_layoutParams['ruta_img']; ?>1.jpg">
					</div>
					<div class="card-content white-text">
						<span class="card-title">CONSULTAS</span>
						<p>Aquí podrá registar nuevos usuarios en el sistema.</p>
					</div>
					<div class="card-action">
						<a class="white-text" href="<?php echo BASE_URL?>consultas">Clic aquí para ir</a>
					</div>
				</div>
			</div>
		</div>

	<?php else: ?>
		<div class="row">
			<div class="col s6">
				<div class="card indigo darken-2">
					<div class="card-image">
						<img src="<?php echo $_layoutParams['ruta_img']; ?>2.jpg">
					</div>
					<div class="card-content white-text">
						<span class="card-title">FICHA HOGAR</span>
						<p>Aquí podrá registar nuevos usuarios en el sistema.</p>
					</div>
					<div class="card-action">
						<a class="white-text" href="<?php echo BASE_URL?>ficha_hogar">Clic aquí para ir</a>
					</div>
				</div>
			</div>

			<div class="col s6">
				<div class="card teal darken-2">
					<div class="card-image">
						<img src="<?php echo $_layoutParams['ruta_img']; ?>4.jpg">
					</div>
					<div class="card-content white-text">
						<span class="card-title">INDICADORES</span>
						<p>Aquí podrá ir a los indicadores.</p>
					</div>
					<div class="card-action">
						<a class="white-text" href="<?php echo BASE_URL?>indicadores">Clic aquí para ir</a>
					</div>
				</div>
			</div>

			
			<div class="col s4">
				<div class="card orange darken-2">
					<div class="card-image">
						<img src="<?php echo $_layoutParams['ruta_img']; ?>0.png">
					</div>
					<div class="card-content white-text">
						<span class="card-title">REGISTRO DE USUARIOS</span>
						<p>Aquí podrá registar nuevos usuarios en el sistema.</p>
					</div>
					<div class="card-action">
						<a class="white-text" href="<?php echo BASE_URL?>registro/">Clic aquí para ir</a>
					</div>
				</div>
			</div>
			

			<div class="col s4">
				<div class="card blue-grey darken-2">
					<div class="card-image">
						<img src="<?php echo $_layoutParams['ruta_img']; ?>3.jpg">
					</div>
					<div class="card-content white-text">
						<span class="card-title">FORMATOS PENDIENTES</span>
						<p>Aquí podra ver los formatos que hacen falta por diligenciar.</p>
					</div>
					<div class="card-action">
						<a class="white-text" href="<?php echo BASE_URL?>hoja_trabajo/">Clic aquí para ir</a>
					</div>
				</div>
			</div>

			<div class="col s4">
				<div class="card pink darken-2">
					<div class="card-image">
						<img src="<?php echo $_layoutParams['ruta_img']; ?>1.jpg">
					</div>
					<div class="card-content white-text">
						<span class="card-title">CONSULTAS</span>
						<p>Aquí podrá registar nuevos usuarios en el sistema.</p>
					</div>
					<div class="card-action">
						<a class="white-text" href="<?php echo BASE_URL?>consultas">Clic aquí para ir</a>
					</div>
				</div>
			</div>
		</div>

	<?php endif ?>		
</div>