<div>			
	<h5 class="center-align teal lighten-2 ">Formulario Ficha AIEPI</h5>
</div>


<form action="" class="col s12">
	<ul class="collapsible" data-collapsible="accordion">
		<li>
			<div class="collapsible-header teal darken-2 white-text text-white white-text text-white">Datos De Ubicacion</div>
			<div class="collapsible-body">
				<div class="row">
					<div class="input-field col s2">
						<input type="text" name="fechaEncuestaAiepi" id="fechaEncuestaAiepi" class="datepicker">
						<label for="fechaEncuestaAiepi">Fecha</label>
					</div>
					<div class="input-field col s5">
						<input type="text" name="nombreInstitucion" id="nombreInstitucion" class="validate">
						<label for="nombreInstitucion">Institucion</label>
					</div>
					<div class="input-field col s5">
						<select name="nombreMunicipio" id="nombreMunicipio">
							<option value="" disabled selected>Seleccione Un Municipio</option>
							<option value="">Fusagasuga</option>
						</select>
						<label>Municipio</label>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s6">
						<input type="text" name="aseguradorAiepi" id="aseguradorAiepi" class="validate">
						<label for="aseguradorAiepi">Asegurador (EPS)</label>
					</div>
					<!-- Los Tipos De Usuarios Se Traen De La Base De Datos -->
					<div class="input-field col s6">
						<select name="tipoDeUsuarioAiepi" id="tipoDeUsuarioAiepi">
							<option value="" disabled selected>Seleccion Tipo De Usuario</option>
							<option value="">Usuario1</option>
						</select>
						<label for="aseguradorAiepi">Tipo De Usuario</label>
					</div>
				</div>
			</div>
		</li>
		<li>
			<div class="collapsible-header teal darken-2 white-text text-white">Datos Del Niño</div>
			<div class="collapsible-body">
				<div class="row">
					<div class="input-field col s12">
						<input type="text" name="nombreNiño" id="nombreNiño" class="validate">
						<label for="nombreNiño">Nombres Y Apellidos</label>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s4">
						<input type="text" name="rcNiño" id="rcNiño" class="validate">
						<label for="rcNiño">RC</label>
					</div>
					<div class="input-field col s4">
						<input type="text" name="fechNacimientoNiño" id="fechNacimientoNiño" class="datepicker">
						<label for="fechNacimientoNiño">Fecha De Nacimiento</label>
					</div>
					<div class="input-field col s4">
						<input class="with-gap" type="radio"  name="generoEncuestaAiepi" id="masculinoGeneroAiepi">
						<label for="masculinoGeneroAiepi">Masculino</label>
						<br>
						<input class="with-gap" type="radio"  name="generoEncuestaAiepi" id="femeninoGeneroAiepi">
						<label for="femeninoGeneroAiepi">Femenino</label>
					</div>
				</div>
				<div class="row">
					<!-- Los Datos Se Traen De La Base De Datos -->
					<div class="input-field col s6">
						<select name="procedenciaAiepi" id="procedenciaAiepi">
							<option value="" disabled selected>Seleccione una procedencia</option>
							<option value="">Urbana</option>
							<option value="">Rural</option>
							<option value="">Centros Poblados</option>
						</select>
						<label>Procedencia</label>
					</div>
					
					<!-- Los Datos Se Traen De La Base De Datos -->
					<div class="input-field col s6">
						<select name="tipoPoblacionAiepi" id="tipoPoblacionAiepi">
							<option value="" disabled selected>Seleccione Tipo De Poblacion</option>
							<option value="">Desplazado</option>
							<option value="">Indigena</option>
							<option value="">ETC</option>
						</select>
						<label>Tipo De Poblacion</label>
					</div>
				</div>
			</div>
		</li>
		<li>
			<div class="collapsible-header teal darken-2 white-text text-white">Datos Del Acompañante</div>
			<div class="collapsible-body">
				<div class="row">
					<div class="input-field col s12">
						<input type="text" name="nombreAcompañanteAiepi" id="nombreAcompañanteAiepi">
						<label for="nombreAcompañanteAiepi">Nombres Y Apellidos Del Acompañante</label>
					</div>
				</div>
				<div class="row">
					<!-- Los Datos Se Traen De La Base De Datos -->
					<div class="input-field col s3">
						<select name="parentescoAiepi" id="parentescoAiepi">
							<option value="" disabled selected>Seleccione Parentesco</option>
							<option value="">Padre</option>
							<option value="">Madre</option>
							<option value="">Etc</option>
						</select>
					</div>
					<div class="input-field col s3">
						<input type="text" name="direccionAiepi" id="direccionAiepi">
						<label for="direccionAiepi">Direccion</label>
					</div>
					<div class="input-field col s3">
						<input type="text" name="TelefonoAiepi" id="TelefonoAiepi">
						<label for="TelefonoAiepi">Telefono</label>
					</div>
					<div class="input-field col s3">
						<select name="evaluacionRealizadaAiepi" id="evaluacionRealizadaAiepi">
							<option value="" disabled selected>Seleccione Evaluacion Realizada</option>
							<option value="">Primera Vez</option>
							<option value="">Seguimiento</option>
							<option value="">Por Alto Riesgo De La Familia</option>
							<option value="">Enfermedad De Alto Riesgo</option>
						</select>
					</div>
				</div>
				
			</div>
		</li>
		<li>
			<div class="collapsible-header teal darken-2 white-text text-white">Primera Parte: Identificacion De Signos Generales De Riesgo</div>
			<div class="collapsible-body">
				<div class="row">
					<div class="input-field col s5">
						<table class="bordered">
							<tbody>
								<tr>
									<td>
										Identificacion De Signos Generales De Riesgo
									</td>
								</tr>
								<tr>
									<td>
										<input type="checkbox" class="filled-in" name="tipSelecSignoRiesgoOp1" id="tipSelecSignoRiesgoOp1">
										<label for="tipSelecSignoRiesgoOp1" class="black-text text-black"> No Puede Beber O Tomar El pecho</label>
									</td>
								</tr>
								<tr>
									<td>
										<input type="checkbox" class="filled-in" name="tipSelecSignoRiesgoOp2" id="tipSelecSignoRiesgoOp2">
										<label for="tipSelecSignoRiesgoOp2" class="black-text text-black"> Letargico</label>
									</td>
								</tr>
								<tr>
									<td>
										<input type="checkbox" class="filled-in" name="tipSelecSignoRiesgoOp3" id="tipSelecSignoRiesgoOp3">
										<label for="tipSelecSignoRiesgoOp3" class="black-text text-black"> Inconsciente</label>
									</td>
								</tr>
								<tr>
									<td>
										<input type="checkbox" class="filled-in" name="tipSelecSignoRiesgoOp4" id="tipSelecSignoRiesgoOp4">
										<label for="tipSelecSignoRiesgoOp4" class="black-text text-black"> Vomita Todo</label>
									</td>
								</tr>
								<tr>
									<td>
										<input type="checkbox" class="filled-in" name="tipSelecSignoRiesgoOp5" id="tipSelecSignoRiesgoOp5">
										<label for="tipSelecSignoRiesgoOp5" class="black-text text-black"> Convulsiones</label>
									</td>
								</tr>
								<tr>
									<td>
										<input type="checkbox" class="filled-in" name="tipSelecSignoRiesgoOp6" id="tipSelecSignoRiesgoOp6">
										<label for="tipSelecSignoRiesgoOp6" class="black-text text-black"> Ninguna De Las anteriores</label>
									</td>
								</tr>
							</tbody>
						</table>
						
					</div>
					<div class="input-field col s7">
						<table class="bordered">
							<tbody>
								<tr>
									<td>
										<br>
									</td>
								</tr>
								<tr>
									<td>Tiene el Niño o Niña Problemas De Salud Bucal?</td>
									<td>
										<input class="with-gap" class="with-gap" type="radio" name="opProblemaSaludBocal" id="opProblemaSaludBocalSi">
										<label for="opProblemaSaludBocalSi">Si</label>
										<input class="with-gap" class="with-gap" type="radio" name="opProblemaSaludBocal" id="opProblemaSaludBocalNo">
										<label for="opProblemaSaludBocalNo">No</label>
									</td>
								</tr>
								<tr>
									<td>¿Tiene Dolor o Molestia Al Comer?</td>
									<td>
										<input class="with-gap" class="with-gap" class="with-gap" type="radio" name="opDolorAlComer" id="opDolorAlComerSi">
										<label for="opDolorAlComerSi">Si</label>
										<input class="with-gap" class="with-gap" type="radio" name="opDolorAlComer" id="opDolorAlComerNo">
										<label for="opDolorAlComerNo">No</label>
									</td>
								</tr>
								<tr>
									<td>¿Ha tenido Algun Golpe En La Boca?</td>
									<td>
										<input class="with-gap" class="with-gap" type="radio" name="opGolpeBoca" id="opGolpeBocaSi">
										<label for="opGolpeBocaSi">Si</label>
										<input class="with-gap" class="with-gap" type="radio" name="opGolpeBoca" id="opGolpeBocaNo">
										<label for="opGolpeBocaNo">No</label>
									</td>
								</tr>
								<tr>
									<td>¿Durante La Noche Duerme Sin Cepillarse Los Dientes?</td>
									<td>
										<input class="with-gap" class="with-gap" type="radio" name="opDuermeSinCepillarse" id="opDuermeSinCepillarseSi">
										<label for="opDuermeSinCepillarseSi">Si</label>
										<input class="with-gap" class="with-gap" type="radio" name="opDuermeSinCepillarse" id="opDuermeSinCepillarseNo">
										<label for="opDuermeSinCepillarseNo">No</label>
									</td>
								</tr>
								<tr>
									<td>¿Le Subervisa El Cepillado De Dientes?</td>
									<td>
										<input class="with-gap" class="with-gap" type="radio" name="opSupervisaCepillado" id="opSupervisaCepilladoSi">
										<label for="opSupervisaCepilladoSi">Si</label>
										<input class="with-gap" class="with-gap" type="radio" name="opSupervisaCepillado" id="opSupervisaCepilladoNo">
										<label for="opSupervisaCepilladoNo">No</label>
									</td>
								</tr>
								<tr>
									<td>¿Le Sangra La Encia Cuando Se Cepilla?</td>
									<td>
										<input class="with-gap" class="with-gap" type="radio" name="opSangraCuandoCepilla" id="opSangraCuandoCepillaSi">
										<label for="opSangraCuandoCepillaSi">Si</label>
										<input class="with-gap" class="with-gap" type="radio" name="opSangraCuandoCepilla" id="opSangraCuandoCepillaNo">
										<label for="opSangraCuandoCepillaNo">No</label>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s2">
						
						<input type="number" value="0" min="0" name="numValOdontologicasAño" id="numValOdontologicasAño">
						<label for="numValOdontologicasAño">¿N° De Valoraciones Odontologicas En El Ultimo Año?</label>
					</div>
					<div class="input-field col s2">
						
						<input type="number" value="0" min="0" name="numHigieneOralDia" id="numHigieneOralDia">
						<label for="numHigieneOralDia">¿Cuantas Veces Hace Higiene Oral Al Dia?</label>
					</div>
					<div class="input-field col s8">
						<input type="text" name="dascHigOral" id="dascHigOral">
						<label for="dascHigOral">¿Con Que Hace La Higienizacion Oral?</label>
					</div>
				</div>
			</div>
		</li>
		<li>
			<div class="collapsible-header teal darken-2 white-text text-white">Segunda Parte: Identificacion De Signos Generales De Riesgo</div>
			<div class="collapsible-body">
				<div class="row">
					<div class="input-field col s6">
						
						¿Tiene el Niño o Niña Tos?
						<br>
						<input class="with-gap" class="with-gap" type="radio" name="opNiñoConTos" id="opNiñoConTosSi">
						<label for="opNiñoConTosSi">Si</label>
						<input class="with-gap" class="with-gap" type="radio" name="opNiñoConTos" id="opNiñoConTosNo">
						<label for="opNiñoConTosNo">No</label>
						
					</div>
					<!-- Inicio De Validacion, Si la Respuesta Anterios es SI -->
					<div class="input-field col s6">
						
						<input type="number" min="0" value="0" name="numDiasConTos" id="numDiasConTos">
						<label for="numDiasConTos">Numero De Dias Que lleva Con Tos</label>
						
					</div>
				</div>
				<div class="row">
					<div class="input-field col s6">
						¿Tiene El Niño(a) Dificultado Para Respirar?
						<br>
						<input class="with-gap" class="with-gap" type="radio" name="opDificultadParaRespirar" id="opDificultadParaRespirarSi">
						<label for="opDificultadParaRespirarSi">Si</label>
						<input class="with-gap" class="with-gap" type="radio" name="opDificultadParaRespirar" id="opDificultadParaRespirarNo">
						<label for="opDificultadParaRespirarNo">No</label>
						
					</div>
					<!-- Inicio De Validacion, Si la Respuesta Anterios es SI -->
					<div class="input-field col s6">
						
						<input type="number" min="0" value="0" name="numDiasConDificultadParaRespirar" id="numDiasConDificultadParaRespirar">
						<label for="numDiasConDificultadParaRespirar">Numero De Dias Con Dificultad Para Respirar</label>
						
					</div>
				</div>
				<div class="row">
					<!-- Posible Primera Parte Para Finalizar Validacion -->
					<div class="input-field col s6">
						<P>
							¿Tiene Tiraje Sucostal?
							<br>
							<input class="with-gap" class="with-gap" type="radio" name="opTirajeSucostal" id="opTirajeSucostalSi">
							<label for="opTirajeSucostalSi">Si</label>
							<input class="with-gap" class="with-gap" type="radio" name="opTirajeSucostal" id="opTirajeSucostalNo">
							<label for="opTirajeSucostalNo">No</label>
						</p>
						
					</div>
					<!-- Posible Primera Parte Para Finalizar Validacion hacia arriba-->
					<!--Inicio De Validacion-->
					<div class="input-field col s6">
						<p>
							¿Tiene Estridor?
							<br>
							<input class="with-gap" class="with-gap" type="radio" name="opTieneEstridor" id="opTieneEstridorSi">
							<label for="opTieneEstridorSi">Si</label>
							<input class="with-gap" class="with-gap" type="radio" name="opTieneEstridor" id="opTieneEstridorNo">
							<label for="opTieneEstridorNo">No</label>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s4">
						<p>
							<input type="number" min="0" value="0" name="numRespiracionesPorMin" id="numRespiracionesPorMin">
							<label for="numRespiracionesPorMin">Numero De Respiraciones Por Minuto</label>
							Freciencia Respiratoria Rapida - Tabla De Referencia
							<br>
							Menor De 2 meses ||--|| Mayor De 60 RPM
							<br>
							Menor De 2 meses a 11 meses ||--|| Mayor De 50 RPM
							<br>
							Menor De 12 meses  5 años||--|| Mayor De 40 RPM
							<!--Validar Si Teine O No Respiracion Rapida-->
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							¿Tiene Respiracion Rapida?
							<br>
							<input class="with-gap" class="with-gap" type="radio" name="opRespiracionRapida" id="opRespiracionRapidaSi">
							<label for="opRespiracionRapidaSi">Si</label>
							<input class="with-gap" class="with-gap" type="radio" name="opRespiracionRapida" id="opRespiracionRapidaNo">
							<label for="opRespiracionRapidaNo">No</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							¿Tiene Sibilancias?
							<br>
							<input class="with-gap" type="radio" name="opTieneSibilancias" id="opTieneSibilanciasSi">
							<label for="opTieneSibilanciasSi">Si</label>
							<input class="with-gap" type="radio" name="opTieneSibilancias" id="opTieneSibilanciasNo">
							<label for="opTieneSibilanciasNo">No</label>
						</p>
					</div>
				</div>
			</div>
		</li>
		<li>
			<div class="collapsible-header teal darken-2 white-text text-white">Tercera Parte: Identificacion De Signos Generales De Riesgo</div>
			<div class="collapsible-body">
				<div class="row">
					<div class="input-field col s6">
						<p>
							¿El Niño(a) Ha Estado en Contacto Con personas con TB?
							<br>
							<input class="with-gap" type="radio" name="opContactoConPerTb" id="opContactoConPerTbSi">
							<label for="opContactoConPerTbSi">Si</label>
							<input class="with-gap" type="radio" name="opContactoConPerTb" id="opContactoConPerTbNo">
							<label for="opContactoConPerTbNo">No</label>
						</p>
					</div>
					<div class="input-field col s6">
						<p>
							¿El Niño(a) Ha Estado En contacto con Personas Sintomaticas Respiratorias?
							<br>
							<input class="with-gap" type="radio" name="opContactoConPerSintomaticasResp" id="opContactoConPerSintomaticasRespSi">
							<label for="opContactoConPerSintomaticasRespSi">Si</label>
							<input class="with-gap" type="radio" name="opContactoConPerSintomaticasResp" id="opContactoConPerSintomaticasRespNo">
							<label for="opContactoConPerSintomaticasRespNo">No</label>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s6">
						<p>
							¿Tos Persistente con Mas De 21 Dias?
							<br>
							<input class="with-gap" type="radio" name="opTosPersistenteMasDe21Dias" id="opTosPersistenteMasDe21DiasSi">
							<label for="opTosPersistenteMasDe21DiasSi">Si</label>
							<input class="with-gap" type="radio" name="opTosPersistenteMasDe21Dias" id="opTosPersistenteMasDe21DiasNo">
							<label for="opTosPersistenteMasDe21DiasNo">No</label>
						</p>
					</div>
					<div class="input-field col s6">
						<p>
							¿Perdida O Ganancia De Perso En Los Ultimos Tres Meses?
							<br>
							<input class="with-gap" type="radio" name="opPerdidaOGananciaPesoUlt3Meses" id="opPerdidaOGananciaPesoUlt3MesesSi">
							<label for="opPerdidaOGananciaPesoUlt3MesesSi">Si</label>
							<input class="with-gap" type="radio" name="opPerdidaOGananciaPesoUlt3Meses" id="opPerdidaOGananciaPesoUlt3MesesNo">
							<label for="opPerdidaOGananciaPesoUlt3MesesNo">No</label>
						</p>
					</div>
				</div>
			</div>
		</li>
		<li>
			<div class="collapsible-header teal darken-2 white-text text-white">Cuarta Parte: Identificacion De Signos Generales De Riesgo</div>
			<div class="collapsible-body">
				<div class="row">
					<div class="input-field col s4">
						<p>
							¿Tiene El Niño(a) Diarrea?
							<br>
							<input class="with-gap" type="radio" name="opTieneDiarrea" id="opTieneDiarreaSi">
							<label for="opTieneDiarreaSi">Si</label>
							<input class="with-gap" type="radio" name="opTieneDiarrea" id="opTieneDiarreaNo">
							<label for="opTieneDiarreaNo">No</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							<!--Inicio De Validacion, Si la respuesta Anterior es SI-->
							<input type="number" min="0" value="0" name="numDiasConDiarrea" id="numDiasConDiarrea">
							<label for="numDiasConDiarrea">Numero De Dias Que El Niño(a) Tiene Diarrea</label>
						</p>
					</div>
					
					<div class="input-field col s4">
						<p>
							Fontanela O Molleja Hundida
							<br>
							<input class="with-gap" type="radio" name="opFontanelaOMollejaHundida" id="opFontanelaOMollejaHundidaSi">
							<label for="opFontanelaOMollejaHundidaSi">Si</label>
							<input class="with-gap" type="radio" name="opFontanelaOMollejaHundida" id="opFontanelaOMollejaHundidaNo">
							<label for="opFontanelaOMollejaHundidaNo">No</label>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s4">
						<p>
							Intranquilo O Irritable
							<br>
							<input class="with-gap" type="radio" name="opIntranquiloOIrritable" id="opIntranquiloOIrritableSi">
							<label for="opIntranquiloOIrritableSi">Si</label>
							<input class="with-gap" type="radio" name="opIntranquiloOIrritable" id="opIntranquiloOIrritableNo">
							<label for="opIntranquiloOIrritableNo">No</label>
						</p>
					</div>
					
					<div class="input-field col s4">
						<p>
							¿Hay Sangre En las Heces?
							<br>
							<input class="with-gap" type="radio" name="opSangreEnHeces" id="opSangreEnHecesSi">
							<label for="opSangreEnHecesSi">Si</label>
							<input class="with-gap" type="radio" name="opSangreEnHeces" id="opSangreEnHecesNo">
							<label for="opSangreEnHecesNo">No</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							Boca Seca O Mucha Sed
							<br>
							<input class="with-gap" type="radio" name="opBocaSecaOMuchaSed" id="opBocaSecaOMuchaSedSi">
							<label for="opBocaSecaOMuchaSedSi">Si</label>
							<input class="with-gap" type="radio" name="opBocaSecaOMuchaSed" id="opBocaSecaOMuchaSedNo">
							<label for="opBocaSecaOMuchaSedNo">No</label>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s4">
						<p>
							Ojos Undidos
							<br>
							<input class="with-gap" type="radio" name="opOjosUndidos" id="opOjosUndidosSi">
							<label for="opOjosUndidosSi">Si</label>
							<input class="with-gap" type="radio" name="opOjosUndidos" id="opOjosUndidosNo">
							<label for="opOjosUndidosNo">No</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							Pliegue Cutaneo - Muy Lento Mayor a 2 seg
							<br>
							<input class="with-gap" type="radio" name="opPliegueCutaneoMuyLento" id="opPliegueCutaneoMuyLentoSi">
							<label for="opPliegueCutaneoMuyLentoSi">Si</label>
							<input class="with-gap" type="radio" name="opPliegueCutaneoMuyLento" id="opPliegueCutaneoMuyLentoNo">
							<label for="opPliegueCutaneoMuyLentoNo">No</label>
						</p>
					</div>
					
					<div class="input-field col s4">
						<p>
							Pliegue Cutaneo - Lento 2 seg o menor
							<br>
							<input class="with-gap" type="radio" name="opPliegueCutaneoMuyLento" id="opPliegueCutaneoLentoSi">
							<label for="opPliegueCutaneoLentoSi">Si</label>
							<input class="with-gap" type="radio" name="opPliegueCutaneoMuyLento" id="opPliegueCutaneoLentoNo">
							<label for="opPliegueCutaneoLentoNo">No</label>
						</p>
					</div>
				</div>
			</div>
		</li>
		<li>
			<div class="collapsible-header teal darken-2 white-text text-white">Quinta Parte: Identificacion De Signos Generales De Riesgo</div>
			<div class="collapsible-body">
				<div class="row">
					<div class="input-field col s4">
						<p>
							¿El Niño(a) tiene fiebre?
							<br>
							<input class="with-gap" type="radio" name="opNiñoConFiebre" id="opNiñoConFiebreSi">
							<label for="opNiñoConFiebreSi">Si</label>
							<input class="with-gap" type="radio" name="opNiñoConFiebre" id="opNiñoConFiebreNo">
							<label for="opNiñoConFiebreNo">No</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							<input type="number" min="0" value="0" name="numDiasConFiebre" id="numDiasConFiebre">
							<label for="numDiasConFiebre">Numero De Dias Que El Niño(a) Tiene Fiebre</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							<!--Inicio De Validacion, Si la respuesta Anterior es SI-->
							Fiebre De Mas De 5 Dias Todos Los Dias
							<br>
							<input class="with-gap" type="radio" name="opFiebreMasDe5DiasTodosLosDias" id="opFiebreMasDe5DiasTodosLosDiasSi">
							<label for="opFiebreMasDe5DiasTodosLosDiasSi">Si</label>
							<input class="with-gap" type="radio" name="opFiebreMasDe5DiasTodosLosDias" id="opFiebreMasDe5DiasTodosLosDiasNo">
							<label for="opFiebreMasDe5DiasTodosLosDiasNo">No</label>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s3">
						<p>
							Vive O Visito Zona De Riesgo De Malaria
							<br>
							<input class="with-gap" type="radio" name="opViveOVisitoZonaMalaria" id="opViveOVisitoZonaMalariaSi">
							<label for="opViveOVisitoZonaMalariaSi">Si</label>
							<input class="with-gap" type="radio" name="opViveOVisitoZonaMalaria" id="opViveOVisitoZonaMalariaNo">
							<label for="opViveOVisitoZonaMalariaNo">No</label>
						</p>
					</div>
					<div class="input-field col s3">
						<p>
							Vive O Visito Zona De Riesgo De Dengue
							<br>
							<input class="with-gap" type="radio" name="opViveOVisitoZonaDengue" id="opViveOVisitoZonaDengueSi">
							<label for="opViveOVisitoZonaDengueSi">Si</label>
							<input class="with-gap" type="radio" name="opViveOVisitoZonaDengue" id="opViveOVisitoZonaDengueNo">
							<label for="opViveOVisitoZonaDengueNo">No</label>
						</p>
					</div>
					<div class="input-field col s3">
						<p>
							<select name="zonaVive" id="zonaVive">
								<option value="" disabled selected>Zona</option>
								<option value="">Urbana</option>
								<option value="">Rural</option>
								<option value="">Centros Poblados</option>
							</select>
							
						</p>
					</div>
					<div class="input-field col s3">
						<p>
							Rigidez De Nuca
							<br>
							<input class="with-gap" type="radio" name="opRigidezDeNuca" id="opRigidezDeNucaSi">
							<label for="opRigidezDeNucaSi">Si</label>
							<input class="with-gap" type="radio" name="opRigidezDeNuca" id="opRigidezDeNucaNo">
							<label for="opRigidezDeNucaNo">No</label>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s3">
						<p>
							Manifestacion De Sangrado
							<br>
							<input class="with-gap" type="radio" name="opManifiestaSangrado" id="opManifiestaSangradoSi">
							<label for="opManifiestaSangradoSi">Si</label>
							<input class="with-gap" type="radio" name="opManifiestaSangrado" id="opManifiestaSangradoNo">
							<label for="opManifiestaSangradoNo">No</label>
						</p>
					</div>
					<div class="input-field col s3">
						<p>
							Piel Humeda Y Fria
							<br>
							<input class="with-gap" type="radio" name="opPielHumedaYFria" id="opPielHumedaYFriaSi">
							<label for="opPielHumedaYFriaSi">Si</label>
							<input class="with-gap" type="radio" name="opPielHumedaYFria" id="opPielHumedaYFriaNo">
							<label for="opPielHumedaYFriaNo">No</label>
						</p>
					</div>
					
					<div class="input-field col s3">
						<p>
							Inquieto o Irritable
							<br>
							<input class="with-gap" type="radio" name="opInquitoOIrritable" id="opInquitoOIrritableSi">
							<label for="opInquitoOIrritableSi">Si</label>
							<input class="with-gap" type="radio" name="opInquitoOIrritable" id="opInquitoOIrritableNo">
							<label for="opInquitoOIrritableNo">No</label>
							
						</p>
					</div>
					<div class="input-field col s3">
						<p>
							
							Fiebre Mayor De 39°C
							<br>
							<input class="with-gap" type="radio" name="opFiebreMayorDe39C" id="opFiebreMayorDe39CSi">
							<label for="opFiebreMayorDe39CSi">Si</label>
							<input class="with-gap" type="radio" name="opFiebreMayorDe39C" id="opFiebreMayorDe39CNo">
							<label for="opFiebreMayorDe39CNo">No</label>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s3">
						<p>
							Tos
							<br>
							<input class="with-gap" type="radio" name="opTieneTos" id="opTieneTosSi">
							<label for="opTieneTosSi">Si</label>
							<input class="with-gap" type="radio" name="opTieneTos" id="opTieneTosNo">
							<label for="opTieneTosNo">No</label>
						</p>
					</div>
					<div class="input-field col s3">
						<p>
							Coriza
							<br>
							<input class="with-gap" type="radio" name="opCoriza" id="opCorizaSi">
							<label for="opCorizaSi">Si</label>
							<input class="with-gap" type="radio" name="opCoriza" id="opCorizaNo">
							<label for="opCorizaNo">No</label>
						</p>
					</div>
					<div class="input-field col s3">
						<p>
							Ojos Rojos
							<br>
							<input class="with-gap" type="radio" name="opOjosRojos" id="opOjosRojosSi">
							<label for="opOjosRojosSi">Si</label>
							<input class="with-gap" type="radio" name="opOjosRojos" id="opOjosRojosNo">
							<label for="opOjosRojosNo">No</label>
						</p>
					</div>
					<div class="input-field col s3">
						<p>
							Aspecto Toxico
							<br>
							<input class="with-gap" type="radio" name="opAspectoToxico" id="opAspectoToxicoSi">
							<label for="opAspectoToxicoSi">Si</label>
							<input class="with-gap" type="radio" name="opAspectoToxico" id="opAspectoToxicoNo">
							<label for="opAspectoToxicoNo">No</label>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s4">
						<p>
							Dolor Abdominal Continuo o Intenso
							<br>
							<input class="with-gap" type="radio" name="opDolorAbdominalContOInt" id="opDolorAbdominalContOIntSi">
							<label for="opDolorAbdominalContOIntSi">Si</label>
							<input class="with-gap" type="radio" name="opDolorAbdominalContOInt" id="opDolorAbdominalContOIntNo">
							<label for="opDolorAbdominalContOIntNo">No</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							Pulso Rapido Y Debil
							<br>
							<input class="with-gap" type="radio" name="opPulsoRapidoYDebil" id="opPulsoRapidoYDebilSi">
							<label for="opPulsoRapidoYDebilSi">Si</label>
							<input class="with-gap" type="radio" name="opPulsoRapidoYDebil" id="opPulsoRapidoYDebilNo">
							<label for="opPulsoRapidoYDebilNo">No</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							Erupcion Cutanea Y Generalizada
							<br>
							<input class="with-gap" type="radio" name="opErupcionCutaneaYGeneral" id="opErupcionCutaneaYGeneralSi">
							<label for="opErupcionCutaneaYGeneralSi">Si</label>
							<input class="with-gap" type="radio" name="opErupcionCutaneaYGeneral" id="opErupcionCutaneaYGeneralNo">
							<label for="opErupcionCutaneaYGeneralNo">No</label>
						</p>
					</div>
				</div>
			</div>
		</li>
		<li>
			<div class="collapsible-header teal darken-2 white-text text-white">Riesgo Para Cancer Infantil/Leucemias</div>
			<div class="collapsible-body">
				<div class="row">
					<div class="input-field col s4">
						<p>
							Fiebre Por Mas De 14 Dias Y/O Sudoracion
							<br>
							<input class="with-gap" type="radio" name="opFiebreMasDe14Dias" id="opFiebreMasDe14DiasSi">
							<label for="opFiebreMasDe14DiasSi">Si</label>
							<input class="with-gap" type="radio" name="opFiebreMasDe14Dias" id="opFiebreMasDe14DiasNo">
							<label for="opFiebreMasDe14DiasNo">No</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							Dolor De Cabeza Reciente Que Aumenta
							<br>
							<input class="with-gap" type="radio" name="opDolorDeCabezaRecAumenta" id="opDolorDeCabezaRecAumentaSi">
							<label for="opDolorDeCabezaRecAumentaSi">Si</label>
							<input class="with-gap" type="radio" name="opDolorDeCabezaRecAumenta" id="opDolorDeCabezaRecAumentaNo">
							<label for="opDolorDeCabezaRecAumentaNo">No</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							El Dolor De Cabeza Despierta Al Niño
							<br>
							<input class="with-gap" type="radio" name="opDolorDeCabezaDespiertaAlNiño" id="opDolorDeCabezaDespiertaAlNiñoSi">
							<label for="opDolorDeCabezaDespiertaAlNiñoSi">Si</label>
							<input class="with-gap" type="radio" name="opDolorDeCabezaDespiertaAlNiño" id="opDolorDeCabezaDespiertaAlNiñoNo">
							<label for="opDolorDeCabezaDespiertaAlNiñoNo">No</label>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s4">
						<p>
							<input type="number" min="0" value="0" name="numDiasConDolorDeCabeza" id="numDiasConDolorDeCabeza">
							<label for="numDiasConDolorDeCabeza">Numero De Dias Que El Niño Tiene Dolor De Cabeza</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							El Dolor De Cabeza Se Acompaña De Otro Sintoma Como Vomito
							<br>
							<input class="with-gap" type="radio" name="opDolorDeCabezaAcompañadoConVomito" id="opDolorDeCabezaAcompañadoConVomitoSi">
							<label for="opDolorDeCabezaAcompañadoConVomitoSi">Si</label>
							<input class="with-gap" type="radio" name="opDolorDeCabezaAcompañadoConVomito" id="opDolorDeCabezaAcompañadoConVomitoNo">
							<label for="opDolorDeCabezaAcompañadoConVomitoNo">No</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							Ah Tenido Dolor De Huesos En El Ultimo Mes
							<br>
							<input class="with-gap" type="radio" name="opDolorDeHuesosEnElUltimoMes" id="opDolorDeHuesosEnElUltimoMesSi">
							<label for="opDolorDeHuesosEnElUltimoMesSi">Si</label>
							<input class="with-gap" type="radio" name="opDolorDeHuesosEnElUltimoMes" id="opDolorDeHuesosEnElUltimoMesNo">
							<label for="opDolorDeHuesosEnElUltimoMesNo">No</label>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s4">
						<p>
							Dolor De Huesos Interrumpe Las Actividades Del Niño
							<br>
							<input class="with-gap" type="radio" name="opDolorHuesosInterrumpeActNiño" id="opDolorHuesosInterrumpeActNiñoSi">
							<label for="opDolorHuesosInterrumpeActNiñoSi">Si</label>
							<input class="with-gap" type="radio" name="opDolorHuesosInterrumpeActNiño" id="opDolorHuesosInterrumpeActNiñoNo">
							<label for="opDolorHuesosInterrumpeActNiñoNo">No</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							El Dolor De Huesos Ha Ido En Aumento
							<br>
							<input class="with-gap" type="radio" name="opDolorDeHuesosEnAumento" id="opDolorDeHuesosEnAumentoSi">
							<label for="opDolorDeHuesosEnAumentoSi">Si</label>
							<input class="with-gap" type="radio" name="opDolorDeHuesosEnAumento" id="opDolorDeHuesosEnAumentoNo">
							<label for="opDolorDeHuesosEnAumentoNo">No</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							En Los Ultimos 3 Meses Ha Tenido Cambios Como Fatiga, Perdida De Apetito O Peso
							<br>
							<input class="with-gap" type="radio" name="opUlt3MesesCambiosFatiga" id="opUlt3MesesCambiosFatigaSi">
							<label for="opUlt3MesesCambiosFatigaSi">Si</label>
							<input class="with-gap" type="radio" name="opUlt3MesesCambiosFatiga" id="opUlt3MesesCambiosFatigaNo">
							<label for="opUlt3MesesCambiosFatigaSi">No</label>
						</p>
					</div>
				</div>
			</div>
		</li>
		<li>
			<div class="collapsible-header teal darken-2 white-text text-white">Problemas De Oido</div>
			<div class="collapsible-body">
				<div class="row">
					<div class="input-field col s6">
						<p>
							El Niño(a) Tiene Problemas De Oido
							<br>
							<input class="with-gap" type="radio" name="opProblemasDeOido" id="opProblemasDeOidoSi">
							<label for="opProblemasDeOidoSi">Si</label>
							<input class="with-gap" type="radio" name="opProblemasDeOido" id="opProblemasDeOidoNo">
							<label for="opProblemasDeOidoNo">No</label>
						</p>
					</div>
					<div class="input-field col s6">
						<p>
							<input type="number" min="0" value="0" name="numDeEpisodiosPrevios" id="numDeEpisodiosPrevios">
							<label for="numDeEpisodiosPrevios">Numero De Episodios Previos</label>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s6">
						<p>
							Tiene Supuracion De Oido
							<br>
							<input class="with-gap" type="radio" name="opSupuracionDeOido" id="opSupuracionDeOidoSi">
							<label for="opSupuracionDeOidoSi">Si</label>
							<input class="with-gap" type="radio" name="opSupuracionDeOido" id="opSupuracionDeOidoNo">
							<label for="opSupuracionDeOidoNo">No</label>
						</p>
					</div>
					<div class="input-field col s6">
						<p>
							<input type="number" min="0" value="0" name="numDiasConSupuracion" id="numDiasConSupuracion">
							<label for="numDiasConSupuracion">Hace cuantos Dias</label>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s6">
						<p>
							Tumefaccion/Dolor Atras De La Oreja
							<br>
							<input class="with-gap" type="radio" name="opDolorAtrasDeLaOreja" id="opDolorAtrasDeLaOrejaSi">
							<label for="opDolorAtrasDeLaOrejaSi">Si</label>
							<input class="with-gap" type="radio" name="opDolorAtrasDeLaOreja" id="opDolorAtrasDeLaOrejaNo">
							<label for="opDolorAtrasDeLaOrejaNo">No</label>
						</p>
					</div>
				</div>
			</div>
		</li>
		<li>
			<div class="collapsible-header teal darken-2 white-text text-white">Problemas De Desnutricion</div>
			<div class="collapsible-body">
				<div class="row">
					<div class="input-field col s4">
						<p>
							El Niño(a) Tiene Desnutricion Y/O Anemia
							<br>
							<input class="with-gap" type="radio" name="opNiñoDesnutricionOAnemia" id="opNiñoDesnutricionOAnemiaSi">
							<label for="opNiñoDesnutricionOAnemiaSi">Si</label>
							<input class="with-gap" type="radio" name="opNiñoDesnutricionOAnemia" id="opNiñoDesnutricionOAnemiaNo">
							<label for="opNiñoDesnutricionOAnemiaNo">No</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							Retraso En El Crecimiento
							<br>
							<input class="with-gap" type="radio" name="opRetrasoDeCrecimiento" id="opRetrasoDeCrecimientoIntenso">
							<label for="opRetrasoDeCrecimientoIntenso">Muy Intenso</label>
							<input class="with-gap" type="radio" name="opRetrasoDeCrecimiento" id="opRetrasoDeCrecimientoMarcado">
							<label for="opRetrasoDeCrecimientoMarcado">Menos Marcado</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							Valoracion De La Cara
							<br>
							<input class="with-gap" type="radio" name="opValoracionDeCara" id="opValoracionDeCaraViejito">
							<label for="opValoracionDeCaraViejito">Cara De Viejito</label>
							<input class="with-gap" type="radio" name="opValoracionDeCara" id="opValoracionDeCaraLunaLlena">
							<label for="opValoracionDeCaraLunaLlena">Cara De Luna Llena</label>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s4">
						<p>
							Perdida De Tejido Muscular
							<br>
							<input class="with-gap" type="radio" name="opPerdidaTejidoMusc" id="opPerdidaTejidoMuscMuyMarcada">
							<label for="opPerdidaTejidoMuscMuyMarcada">Muy Marcada</label>
							<input class="with-gap" type="radio" name="opPerdidaTejidoMusc" id="opPerdidaTejidoMuscMarcada">
							<label for="opPerdidaTejidoMuscMarcada">Marcada</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							El Sistema Oseo
							<br>
							<input class="with-gap" type="radio" name="opSistemaOseo" id="opSistemaOseoCostalVisible">
							<label for="opSistemaOseoCostalVisible">Rosario Costal Visible</label>
							<input class="with-gap" type="radio" name="opSistemaOseo" id="opSistemaOseoPiernasDeSable">
							<label for="opSistemaOseoPiernasDeSable">Piernas De Sable</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							Tejido Adiposo
							<br>
							<input class="with-gap" type="radio" name="opTejidoAdiposo" id="opTejidoAdiposoAusente">
							<label for="opTejidoAdiposoAusente">Ausente</label>
							<input class="with-gap" type="radio" name="opTejidoAdiposo" id="opTejidoAdiposoPocoDisminuido">
							<label for="opTejidoAdiposoPocoDisminuido">Poco Disminuido</label>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s4">
						<p>
							Comportamiento
							<br>
							<input class="with-gap" type="radio" name="opComportamiento" id="opComportamientoMirada">
							<label for="opComportamientoMirada">Mirada De Angustia</label>
							<input class="with-gap" type="radio" name="opComportamiento" id="opComportamientoLlanto">
							<label for="opComportamientoLlanto">Llanto/Apatia</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							Edema
							<br>
							<input class="with-gap" type="radio" name="opEdema" id="opEdemaSi">
							<label for="opEdemaSi">Si</label>
							<input class="with-gap" type="radio" name="opEdema" id="opEdemaNo">
							<label for="opEdemaNo">No</label>
						</p>
					</div>
					<div class="input-field col s4">
						<p>
							Cabello
							<br>
							<input class="with-gap" type="radio" name="opCabello" id="opCabelloEscaso">
							<label for="opCabelloEscaso">Escaso</label>
							<input class="with-gap" type="radio" name="opCabello" id="opCabelloDebil">
							<label for="opCabelloDebil">Debil</label>
						</p>
					</div>
				</div>
			</li>
			<li>
				<div class="collapsible-header teal darken-2 white-text text-white">Perimetro Braquial</div>
				<div class="collapsible-body">
					<div class="row">
						<div class="input-field col s8">
							<p>
								Color:Marcar El Color Obtenido Al Medir La Circunferencia En El Punto Medio Del Brazo
								<br>
								<input class="with-gap" type="radio" name="opMarcaDelColorBrazo" id="opMarcaDelColorBrazoRojo">
								<label for="opMarcaDelColorBrazoRojo">Rojo</label>
								<input class="with-gap" type="radio" name="opMarcaDelColorBrazo" id="opMarcaDelColorBrazoNaranja">
								<label for="opMarcaDelColorBrazoNaranja">Naranja</label>
								<input class="with-gap" type="radio" name="opMarcaDelColorBrazo" id="opMarcaDelColorBrazoAmarillo">
								<label for="opMarcaDelColorBrazoAmarillo">Amarillo</label>
								<input class="with-gap" type="radio" name="opMarcaDelColorBrazo" id="opMarcaDelColorBrazoVerde">
								<label for="opMarcaDelColorBrazoVerde">Verde</label>
							</p>
						</div>
						<div class="input-field col s4">
							<input type="text" name="mediaMarcaColorBrazo" id="mediaMarcaColorBrazo">
							<label for="mediaMarcaColorBrazo">Media</label>
						</div>
					</div>
				</div>
			</li>
			<li>
				<div class="collapsible-header teal darken-2 white-text text-white">Aplicacion De Medidas De Proteccion De Salud Niños Menores De 6 Meses</div>
				<div class="collapsible-body">
					<div class="row">
						<div class="input-field col s4">
							<p>
								¿El Lactante Toma Seno?
								<br>
								<input class="with-gap" type="radio" name="opTomaSenoMen6Meses" id="opTomaSenoMen6MesesSi">
								<label for="opTomaSenoMen6MesesSi">Si</label>
								<input class="with-gap" type="radio" name="opTomaSenoMen6Meses" id="opTomaSenoMen6MesesNo">
								<label for="opTomaSenoMen6MesesNo">No</label>
							</p>
						</div>
						<div class="input-field col s4">
							
							<input type="number" min="0" value="0" name="numVecesTomaSenoDiaMen6Meses" id="numVecesTomaSenoDiaMen6Meses">
							<label for="numVecesTomaSenoDiaMen6Meses">¿Cuantas Veces Toma Seno En El Dia?</label>
							
						</div>
						<div class="input-field col s4">
							
							<input type="number" min="0" value="0" name="numVecesTomaSenoNocheMen6Meses" id="numVecesTomaSenoNocheMen6Meses">
							<label for="numVecesTomaSenoNocheMen6Meses">¿Cuantas Veces Toma Seno En La Noche?</label>
						</div>
					</div>
					<div class="row">
						<div class="input-field col s6">
							<p>
								La Posicion:
								<br><input type="checkbox" class="filled-in" name="posicionTomaSenoNum1" id="posicionTomaSenoNum1">
								<label for="posicionTomaSenoNum1">el Lactante Esta En Direccion Al Pecho De La MAdre Con La Nariz Frente Al Pezon</label>
								<br><input type="checkbox" class="filled-in" name="posicionTomaSenoNum2" id="posicionTomaSenoNum2">
								<label for="posicionTomaSenoNum2">El Cuerpo Del Lactante Est Frente A La Madre</label>
								<br><input type="checkbox" class="filled-in" name="posicionTomaSenoNum3" id="posicionTomaSenoNum3">
								<label for="posicionTomaSenoNum3">La Madre Sostiene Todo el Cuerpo Del Niño(a)</label>
							</p>
						</div>
						<div class="input-field col s6">
							<p>
								Agarre
								<br><input type="checkbox" class="filled-in" name="agarreTomaSenoNum1" id="agarreTomaSenoNum1">
								<label for="agarreTomaSenoNum1">El Menton Toca El Seno</label>
								<br><input type="checkbox" class="filled-in" name="agarreTomaSenoNum2" id="agarreTomaSenoNum2">
								<label for="agarreTomaSenoNum2">El Labio Inferior Esta Hacia Afuera</label>
								<br><input type="checkbox" class="filled-in" name="agarreTomaSenoNum3" id="agarreTomaSenoNum3">
								<label for="agarreTomaSenoNum3">Aureola Se Va Mas Arriba Que Abajo</label>
							</p>
						</div>
					</div>
					<div class="row">
						<div class="input-field col s6">
							<p>
								¿Tiene Alguna Dificultad Para Amamantarlo?
								<br>
								<input type="checkbox" class="filled-in" name="dificultadParaAmamantarNum1" id="dificultadParaAmamantarNum1">
								<label for="dificultadParaAmamantarNum1">No Lacta</label>
								<br><input type="checkbox" class="filled-in" name="dificultadParaAmamantarNum2" id="dificultadParaAmamantarNum2">
								<label for="dificultadParaAmamantarNum2">No Tiene Dificultad</label>
								<br><input type="checkbox" class="filled-in" name="dificultadParaAmamantarNum3" id="dificultadParaAmamantarNum3">
								<label for="dificultadParaAmamantarNum3">Le Duele</label>
								<br><input type="checkbox" class="filled-in" name="dificultadParaAmamantarNum4" id="dificultadParaAmamantarNum4">
								<label for="dificultadParaAmamantarNum4">No Le Baja Leche</label>
								<br><input type="checkbox" class="filled-in" name="dificultadParaAmamantarNum5" id="dificultadParaAmamantarNum5">
								<label for="dificultadParaAmamantarNum5">Produce Mucha Leche</label>
								<br><input type="checkbox" class="filled-in" name="dificultadParaAmamantarNum6" id="dificultadParaAmamantarNum6">
								<label for="dificultadParaAmamantarNum6">Laceracion Del Pezon</label>
								<br><input type="checkbox" class="filled-in" name="dificultadParaAmamantarNum7" id="dificultadParaAmamantarNum7">
								<label for="dificultadParaAmamantarNum7">Hospitalizacion</label>
								<br><input type="checkbox" class="filled-in" name="dificultadParaAmamantarNum8" id="dificultadParaAmamantarNum8">
								<label for="dificultadParaAmamantarNum8">Otro</label>
							</p>
							<!--
							<div class="row">
											<div class="input-field col s8">
															<input type="text" name="dificultadParaAmamantarOtro" id="dificultadParaAmamantarOtro">
															<label for="dificultadParaAmamantarOtro">¿Cual?</label>
											</div>
							</div>-->
						</div>
						<div class="input-field col s6">
							<p>
								¿El Lactante Recibe Habitualmente Otros Alimentos?
								<br><input type="checkbox" class="filled-in" name="lactRecibeOtrosAlimentosNum1" id="lactRecibeOtrosAlimentosNum1">
								<label for="lactRecibeOtrosAlimentosNum1">Otra Leche</label>
								<br><input type="checkbox" class="filled-in" name="lactRecibeOtrosAlimentosNum2" id="lactRecibeOtrosAlimentosNum2">
								<label for="lactRecibeOtrosAlimentosNum2">Jugo</label>
								<br><input type="checkbox" class="filled-in" name="lactRecibeOtrosAlimentosNum3" id="lactRecibeOtrosAlimentosNum3">
								<label for="lactRecibeOtrosAlimentosNum3">Agua</label>
								<br><input type="checkbox" class="filled-in" name="lactRecibeOtrosAlimentosNum4" id="lactRecibeOtrosAlimentosNum4">
								<label for="lactRecibeOtrosAlimentosNum4">Colada</label>
								<br><input type="checkbox" class="filled-in" name="lactRecibeOtrosAlimentosNum5" id="lactRecibeOtrosAlimentosNum5">
								<label for="lactRecibeOtrosAlimentosNum5">Papillas</label>
								<br><input type="checkbox" class="filled-in" name="lactRecibeOtrosAlimentosNum6" id="lactRecibeOtrosAlimentosNum6">
								<label for="lactRecibeOtrosAlimentosNum6">No Recibe</label>
							</p>
						</div>
					</div>
					<div class="row">
						<div class="input-field col s6">
							<p>
								Estos Alimentos Contienen
								<br><input type="checkbox" class="filled-in" name="alimentosContienenSal" id="alimentosContienenSal">
								<label for="alimentosContienenSal">Sal</label>
								<br><input type="checkbox" class="filled-in" name="alimentosContienenAzucar" id="alimentosContienenAzucar">
								<label for="alimentosContienenAzucar">Azucar</label>
							</p>
						</div>
						<div class="input-field col s6">
							<p>
								¿Que Utiliza Para Alimentar Al Lactante?
								<br><input type="checkbox" class="filled-in" name="utilizaParaAlimentarNum1" id="utilizaParaAlimentarNum1">
								<label for="utilizaParaAlimentarNum1">Tetero</label>
								<br><input type="checkbox" class="filled-in" name="utilizaParaAlimentarNum2" id="utilizaParaAlimentarNum2">
								<label for="utilizaParaAlimentarNum2">Tasa</label>
								<br><input type="checkbox" class="filled-in" name="utilizaParaAlimentarNum3" id="utilizaParaAlimentarNum3">
								<label for="utilizaParaAlimentarNum3">Cuchara</label>
								<br><input type="checkbox" class="filled-in" name="utilizaParaAlimentarNum4" id="utilizaParaAlimentarNum4">
								<label for="utilizaParaAlimentarNum4">Otro:</label>
								<!--
								<div class="row">
												<div class="input-field">
																<input type="text" name="utilizaParaAlimentarOtro" id="utilizaParaAlimentarOtro">
																<label for="utilizaParaAlimentarOtro">¿Cual?</label>
												</div>
								</div>-->
							</p>
						</div>
					</div>
				</div>
			</li>
			<li>
				<div class="collapsible-header teal darken-2 white-text text-white">Aplicacion De Medidas De Proteccion De Salud Niños De 6 meses A 5 Años</div>
				<div class="collapsible-body">
					<div class="row">
						<div class="input-field col s4">
							<p>
								¿El Niño(a) Toma Seno?
								<br>
								<input class="with-gap" type="radio" name="opTomaSenoMas6Meses" id="opTomaSenoMas6MesesSi">
								<label for="opTomaSenoMas6MesesSi">Si</label>
								<input class="with-gap" type="radio" name="opTomaSenoMas6Meses" id="opTomaSenoMas6MesesNo">
								<label for="opTomaSenoMas6MesesNo">No</label>
							</p>
						</div>
						<br>
						<br>
						<div class="input-field col s4">
							<input type="number" min="0" value="0" name="numVecesTomaSenoDiaMas6Meses" id="numVecesTomaSenoDiaMas6Meses">
							<label for="numVecesTomaSenoDiaMas6Meses">¿Cuantas Veces Toma Seno En El Dia?</label>
						</div>
						<div class="input-field col s4">
							<input type="number" min="0" value="0" name="numVecesTomaSenoNocheMas6Meses" id="numVecesTomaSenoNocheMas6Meses">
							<label for="numVecesTomaSenoNocheMas6Meses">¿Cuantas Veces Toma Seno En La Noche?</label>
						</div>
					</div>
					<div class="row">
						<div class="input-field col s4">
							<p>
								¿El Niño Usa biberon?
								<br>
								<input class="with-gap" type="radio" name="opUsaBiberon" id="opUsaBiberonSi">
								<label for="opUsaBiberonSi">Si</label>
								<input class="with-gap" type="radio" name="opUsaBiberon" id="opUsaBiberonNo">
								<label for="opUsaBiberonNo">No</label>
							</p>
						</div>
						<div class="input-field col s4">
							¿Que Toma el Niño(a)?
							<br><input type="checkbox" class="filled-in" name="queTomaElNiñoNum1" id="queTomaElNiñoNum1">
							<label for="queTomaElNiñoNum1">Aguadepanela</label>
							<br><input type="checkbox" class="filled-in" name="queTomaElNiñoNum2" id="queTomaElNiñoNum2">
							<label for="queTomaElNiñoNum2">Leche</label>
							<br><input type="checkbox" class="filled-in" name="queTomaElNiñoNum3" id="queTomaElNiñoNum3">
							<label for="queTomaElNiñoNum3">Colada</label>
							<br><input type="checkbox" class="filled-in" name="queTomaElNiñoNum4" id="queTomaElNiñoNum4">
							<label for="queTomaElNiñoNum4">Sopa</label>
							<br><input type="checkbox" class="filled-in" name="queTomaElNiñoNum5" id="queTomaElNiñoNum5">
							<label for="queTomaElNiñoNum5">Gaseosa</label>
							<br><input type="checkbox" class="filled-in" name="queTomaElNiñoNum6" id="queTomaElNiñoNum6">
							<label for="queTomaElNiñoNum6">Otro:</label>
							<!--
							<input type="text" name="queTomaElNiñoOtro" id="queTomaElNiñoOtro">-->
						</div>
						<div class="input-field col s4">
							¿Cual Es La Consistencia De Los Alimentos?
							<br><input type="checkbox" class="filled-in" name="consistenciaDeAlimentosNum1" id="consistenciaDeAlimentosNum1">
							<label for="consistenciaDeAlimentosNum1">Liquida</label>
							<br><input type="checkbox" class="filled-in" name="consistenciaDeAlimentosNum2" id="consistenciaDeAlimentosNum2">
							<label for="consistenciaDeAlimentosNum2">Crema</label>
							<br><input type="checkbox" class="filled-in" name="consistenciaDeAlimentosNum3" id="consistenciaDeAlimentosNum3">
							<label for="consistenciaDeAlimentosNum3">Papilla</label>
							<br><input type="checkbox" class="filled-in" name="consistenciaDeAlimentosNum4" id="consistenciaDeAlimentosNum4">
							<label for="consistenciaDeAlimentosNum4">Otro:</label>
							<!--
							<input type="text" name="consistenciaDeAlimentosOtro" id="consistenciaDeAlimentosOtro">-->
						</div>
					</div>
					<div class="row">
						<div class="input-field col s4">
							<p>
								¿El Niño Come Solo?
								<br>
								<input class="with-gap" type="radio" name="opComeSolo" id="opComeSoloSi">
								<label for="opComeSoloSi">Si</label>
								<input class="with-gap" type="radio" name="opComeSolo" id="opComeSoloNo">
								<label for="opComeSoloNo">No</label>
							</p>
						</div>
						<div class="input-field col s4">
							<input type="text" name="alimentosConMayorFrecuencia" id="alimentosConMayorFrecuencia">
							<label for="alimentosConMayorFrecuencia">¿Que Alimentos Le Da Con Mayor Frecuencia Al Niño?</label>
						</div>
						<div class="input-field col s4">
							<p>
								Esta En Algun Programa De Recuperacion Nutricional
								<br>
								<input class="with-gap" type="radio" name="opProgramaRecuperacionNutri" id="opProgramaRecuperacionNutriSi">
								<label for="opProgramaRecuperacionNutriSi">Si</label>
								<input class="with-gap" type="radio" name="opProgramaRecuperacionNutri" id="opProgramaRecuperacionNutriNo">
								<label for="opProgramaRecuperacionNutriNo">No</label>
							</p>
							<!--
							¿Cual?
							<br><input type="text" name="programaRecuperacionNutri" id="programaRecuperacionNutri">
							-->
						</div>
					</div>
				</div>
			</li>
			<li>
				<div class="collapsible-header teal darken-2 white-text text-white">Evalue El Desarrollo</div>
				<div class="collapsible-body">
					<div class="row">
						<div class="input-field col s4">
							<table class="bordered">
								<tbody>
									<tr>
										<td>
											A Los 3 Meses Levanta La Cabeza
										</td>
										<td>
											<input class="with-gap" type="radio" name="op3MesesLevantaCabeza" id="op3MesesLevantaCabezaSi">
											<label for="op3MesesLevantaCabezaSi">Si</label>
											<input class="with-gap" type="radio" name="op3MesesLevantaCabeza" id="op3MesesLevantaCabezaNo">
											<label for="op3MesesLevantaCabezaNo">No</label>
											<input class="with-gap" type="radio" name="op3MesesLevantaCabeza" id="op3MesesLevantaCabezaNa">
											<label for="op3MesesLevantaCabezaNa">No Aplica</label>
										</td>
									</tr>
									<tr>
										<td>A Los 6 Meses Se Sienta Con Apoyo</td>
										<td>
											<input class="with-gap" type="radio" name="op6MesesSeSientaConApoyo" id="op6MesesSeSientaConApoyoSi">
											<label for="op6MesesSeSientaConApoyoSi">Si</label>
											<input class="with-gap" type="radio" name="op6MesesSeSientaConApoyo" id="op6MesesSeSientaConApoyoNo">
											<label for="op6MesesSeSientaConApoyoNo">No</label>
											<input class="with-gap" type="radio" name="op6MesesSeSientaConApoyo" id="op6MesesSeSientaConApoyoNa">
											<label for="op6MesesSeSientaConApoyoNa">No Aplica</label>
										</td>
									</tr>
									<tr>
										<td>A los 9 Meses Se Sienta Por Si Solo</td>
										<td>
											<input class="with-gap" type="radio" name="op9MesesSeSientaPorSiSolo" id="op9MesesSeSientaPorSiSoloSi">
											<label for="op9MesesSeSientaPorSiSoloSi">Si</label>
											<input class="with-gap" type="radio" name="op9MesesSeSientaPorSiSolo" id="op9MesesSeSientaPorSiSoloNo">
											<label for="op9MesesSeSientaPorSiSoloNo">No</label>
											<input class="with-gap" type="radio" name="op9MesesSeSientaPorSiSolo" id="op9MesesSeSientaPorSiSoloNa">
											<label for="op9MesesSeSientaPorSiSoloNa">No Aplica</label>
										</td>
									</tr>
									<tr>
										<td>
											A Los 12 Meses Camina Por si solo
										</td>
										<td>
											<input class="with-gap" type="radio" name="op12MesesCaminaSolo" id="op12MesesCaminaSoloSi">
											<label for="op12MesesCaminaSoloSi">Si</label>
											<input class="with-gap" type="radio" name="op12MesesCaminaSolo" id="op12MesesCaminaSoloNo">
											<label for="op12MesesCaminaSoloNo">No</label>
											<input class="with-gap" type="radio" name="op12MesesCaminaSolo" id="op12MesesCaminaSoloNa">
											<label for="op12MesesCaminaSoloNa">No Aplica</label>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
						<div class="input-field col s4">
							<table class="bordered">
								<tbody>
									<tr>
										<td>A Los 16 Meses Camina Solo</td>
										<td>
											<input class="with-gap" type="radio" name="op16MesesCaminaSolo" id="op16MesesCaminaSoloSi">
											<label for="op16MesesCaminaSoloSi">Si</label>
											<input class="with-gap" type="radio" name="op16MesesCaminaSolo" id="op16MesesCaminaSoloNo">
											<label for="op16MesesCaminaSoloNo">No</label>
											<input class="with-gap" type="radio" name="op16MesesCaminaSolo" id="op16MesesCaminaSoloNa">
											<label for="op16MesesCaminaSoloNa">No Aplica</label>
										</td>
									</tr>
									<tr>
										<td>A Los 20 Meses Corre Rapido</td>
										<td>
											<input class="with-gap" type="radio" name="op20MesesCorreRapido" id="op20MesesCorreRapidoSi">
											<label for="op20MesesCorreRapidoSi">Si</label>
											<input class="with-gap" type="radio" name="op20MesesCorreRapido" id="op20MesesCorreRapidoNo">
											<label for="op20MesesCorreRapidoNo">No</label>
											<input class="with-gap" type="radio" name="op20MesesCorreRapido" id="op20MesesCorreRapidoNa">
											<label for="op20MesesCorreRapidoNa">No Aplica</label>
										</td>
									</tr>
									<tr>
										<td>A Los 24 Meses Patea La Pelota</td>
										<td>
											<input class="with-gap" type="radio" name="op24MesesPateaPelota" id="op24MesesPateaPelotaSi">
											<label for="op24MesesPateaPelotaSi">Si</label>
											<input class="with-gap" type="radio" name="op24MesesPateaPelota" id="op24MesesPateaPelotaNo">
											<label for="op24MesesPateaPelotaNo">No</label>
											<input class="with-gap" type="radio" name="op24MesesPateaPelota" id="op24MesesPateaPelotaNa">
											<label for="op24MesesPateaPelotaNa">No Aplica</label>
										</td>
									</tr>
									<tr>
										<td>
										A Los 30 Meses Se Empina En Ambos Pies</td>
										<td>
											<input class="with-gap" type="radio" name="op30MesesSeEmpinaPies" id="op30MesesSeEmpinaPiesSi">
											<label for="op30MesesSeEmpinaPiesSi">Si</label>
											<input class="with-gap" type="radio" name="op30MesesSeEmpinaPies" id="op30MesesSeEmpinaPiesNo">
											<label for="op30MesesSeEmpinaPiesNo">No</label>
											<input class="with-gap" type="radio" name="op30MesesSeEmpinaPies" id="op30MesesSeEmpinaPiesNa">
											<label for="op30MesesSeEmpinaPiesNa">No Aplica</label>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
						<div class="input-field col s4">
							<table class="bordered">
								<tbody>
									<tr>
										<td>A Los 36 Meses Sube/Baja Escaleras Solo</td>
										<td>
											<input class="with-gap" type="radio" name="op36MesesSubeEscaleras" id="op36MesesSubeEscalerasSi">
											<label for="op36MesesSubeEscalerasSi">Si</label>
											<input class="with-gap" type="radio" name="op36MesesSubeEscaleras" id="op36MesesSubeEscalerasNo">
											<label for="op36MesesSubeEscalerasNo">No</label>
											<input class="with-gap" type="radio" name="op36MesesSubeEscaleras" id="op36MesesSubeEscalerasNa">
											<label for="op36MesesSubeEscalerasNa">No Aplica</label>
										</td>
									</tr>
									<tr>
										<td>A Los 48 Meses Lanza Y Atrapa La Pelota</td>
										<td>
											<input class="with-gap" type="radio" name="op48MesesLanzaPelota" id="op48MesesLanzaPelotaSi">
											<label for="op48MesesLanzaPelotaSi">Si</label>
											<input class="with-gap" type="radio" name="op48MesesLanzaPelota" id="op48MesesLanzaPelotaNo">
											<label for="op48MesesLanzaPelotaNo">No</label>
											<input class="with-gap" type="radio" name="op48MesesLanzaPelota" id="op48MesesLanzaPelotaNa">
											<label for="op48MesesLanzaPelotaNa">No Aplica</label>
										</td>
									</tr>
									<tr>
										<td>A Los 60 Meses Se Para Y Salta En Un Pie</td>
										<td>
											<input class="with-gap" type="radio" name="op60MesesSeParaYSalta1Pie" id="op60MesesSeParaYSalta1PieSi">
											<label for="op60MesesSeParaYSalta1PieSi">Si</label>
											<input class="with-gap" type="radio" name="op60MesesSeParaYSalta1Pie" id="op60MesesSeParaYSalta1PieNo">
											<label for="op60MesesSeParaYSalta1PieNo">No</label>
											<input class="with-gap" type="radio" name="op60MesesSeParaYSalta1Pie" id="op60MesesSeParaYSalta1PieNa">
											<label for="op60MesesSeParaYSalta1PieNa">No Aplica</label>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</li>
		</ul>
		
		<br>
		<h1>Evalue La Aderencia Al Programa De Crecimiento Y Desarrollo</h1>
		<h3>Seccion 14</h3>
		Numero De Consultas De Crecimiento y Desarrollo
		<input type="number" min="0" value="0"  name="numConsultasCrecimiento" id="numConsultasCrecimiento">
		<br>
		Recibio Desparacitacion
		<br>
		<input class="with-gap" type="radio" name="opRecibioDesparacitacion" id="opRecibioDesparacitacionSi">Si
		<input class="with-gap" type="radio" name="opRecibioDesparacitacion" id="opRecibioDesparacitacionNo">No
		<br>
		Fecha De Desparacitacion: <input type="date"  name="fechaDeDesparacitacion" id="fechaDeDesparacitacion">
		<br>
		¿El Niño Recibe Micronutrientes?
		<br>
		<input class="with-gap" type="radio" name="opRecibeMicronutrientes" id="opRecibeMicronutrientesSi">Si
		<input class="with-gap" type="radio" name="opRecibeMicronutrientes" id="opRecibeMicronutrientesNo">No
		<br>
		Cuales Son: <input type="text" name="descripcionMicronutrientes" id="descripcionMicronutrientes">
		<br>
		Fecha De Ultima Entrega: <input type="date" name="fechaEntregaMicronutrientes" id="fechaEntregaMicronutrientes">
		<h1>Evaluacion Del Buen Trato</h1>
		<h3>Seccion 15</h3>
		Le Sonrien
		<br>
		<input class="with-gap" type="radio" name="opLeSonrien" id="opLeSonrienSi">Si
		<input class="with-gap" type="radio" name="opLeSonrien" id="opLeSonrienNo">No
		<br>
		Lo Acompañan
		<br>
		<input class="with-gap" type="radio" name="opLeAcompañan" id="opLeAcompañanSi">Si
		<input class="with-gap" type="radio" name="opLeAcompañan" id="opLeAcompañanNo">No
		<br>
		Alzan O Arrulla Al Niño(a)
		<br>
		<input class="with-gap" type="radio" name="opArrullan" id="opArrullanSi">Si
		<input class="with-gap" type="radio" name="opArrullan" id="opArrullanNo">No
		<br>
		Le Juegan O Permiten Que Juegue
		<br>
		<input class="with-gap" type="radio" name="opJuegan" id="opJueganSi">Si
		<input class="with-gap" type="radio" name="opJuegan" id="opJueganNo">No
		<br>
		Se Preocupan Por La Higiene
		<br>
		<input class="with-gap" type="radio" name="opPreocupanPorLaHigiene" id="opPreocupanPorLaHigieneSi">Si
		<input class="with-gap" type="radio" name="opPreocupanPorLaHigiene" id="opPreocupanPorLaHigieneNo">No
		<br>
		Lo Castigan Con Correa, Palmadas, Patadas o Puños
		<br>
		<input class="with-gap" type="radio" name="opCastigan" id="opCastiganSi">Si
		<input class="with-gap" type="radio" name="opCastigan" id="opCastiganNo">No
		<br>
		Se Preocupan Por Su Salud
		<br>
		<input class="with-gap" type="radio" name="opSePreocupanPorSalud" id="opSePreocupanPorSaludSi">Si
		<input class="with-gap" type="radio" name="opSePreocupanPorSalud" id="opSePreocupanPorSaludNo">No
		<br>
		Tiene Accidentes Frecuentes
		<br>
		<input class="with-gap" type="radio" name="opAccidentesFrecuentes" id="opAccidentesFrecuentesSi">Si
		<input class="with-gap" type="radio" name="opAccidentesFrecuentes" id="opAccidentesFrecuentesNo">No
		<br>
		<h1>Riesgos De Accidentes En El Hogar</h1>
		<h3>Seccion 16</h3>
		Esta Solo Tomandose el Tetero
		<br>
		<input class="with-gap" type="radio" name="opSoloTomandoseTetero" id="opSoloTomandoseTeteroSi">Si
		<input class="with-gap" type="radio" name="opSoloTomandoseTetero" id="opSoloTomandoseTeteroNo">No
		<br>
		Objetos Pequeños Al Alcance De Los Niños
		<br>
		<input class="with-gap" type="radio" name="opObjPequeñosAlAlcance" id="opObjPequeñosAlAlcanceSi">Si
		<input class="with-gap" type="radio" name="opObjPequeñosAlAlcance" id="opObjPequeñosAlAlcanceNo">No
		<br>
		Niños En La Cocina
		<br>
		<input class="with-gap" type="radio" name="opNiñosEnCocina" id="opNiñosEnCocinaSi">Si
		<input class="with-gap" type="radio" name="opNiñosEnCocina" id="opNiñosEnCocinaNo">No
		<br>
		Cuchillos, Serruchos Tijeras Al Alcance De Los Niños
		<br>
		<input class="with-gap" type="radio" name="opCuchillosAlAlcance" id="opCuchillosAlAlcanceSi">Si
		<input class="with-gap" type="radio" name="opCuchillosAlAlcance" id="opCuchillosAlAlcanceNo">No
		<br>
		Medicamentos-Insecticidas Al Alcance De Los Niños
		<br>
		<input class="with-gap" type="radio" name="opMedicamentosAlAlcance" id="opMedicamentosAlAlcanceSi">Si
		<input class="with-gap" type="radio" name="opMedicamentosAlAlcance" id="opMedicamentosAlAlcanceNo">No
		<br>
		Escaleras-Terrazas Sin Barandas-Ventanas Sin Proteccion
		<br>
		<input class="with-gap" type="radio" name="opEscalerasSinBarandas" id="opEscalerasSinBarandasSi">Si
		<input class="with-gap" type="radio" name="opEscalerasSinBarandas" id="opEscalerasSinBarandasNo">No
		<br>
		Existen Otros Riesgos Para El Niño En El Hogar
		<br>
		<input class="with-gap" type="radio" name="opRiesgosEnElHogar" id="opRiesgosEnElHogarSi">Si
		<input class="with-gap" type="radio" name="opRiesgosEnElHogar" id="opRiesgosEnElHogarNo">No
		<br>
		Agua Almacenada Sin Tapa
		<br>
		<input class="with-gap" type="radio" name="opAguaAlmacenadaSinTapa" id="opAguaAlmacenadaSinTapaSi">Si
		<input class="with-gap" type="radio" name="opAguaAlmacenadaSinTapa" id="opAguaAlmacenadaSinTapaNo">No
		<br>
		Enchufes Y Cables Descubiertos
		<br>
		<input class="with-gap" type="radio" name="opCablesDescubieros" id="opCablesDescubierosSi">Si
		<input class="with-gap" type="radio" name="opCablesDescubieros" id="opCablesDescubierosNo">No
		<br>
		Velas Y Fosforos Al Alcance De Los Niños
		<br>
		<input class="with-gap" type="radio" name="opVelasAlAlcance" id="opVelasAlAlcanceSi">Si
		<input class="with-gap" type="radio" name="opVelasAlAlcance" id="opVelasAlAlcanceNo">No
		<br>
		<h1>Problemas Ambientales Y De Higiene</h1>
		<h3>Seccion 17</h3>
		<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum1" id="problemaAbientalYHigieneNum1">Niños O Adultos Con ropa Sucia
		<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum2" id="problemaAbientalYHigieneNum2">Niños O Adultos Con Manos y Uñas Sucias
		<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum3" id="problemaAbientalYHigieneNum3">Niños Descalzos
		<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum4" id="problemaAbientalYHigieneNum4">Basura Y Desorden De La Vivienda
		<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum5" id="problemaAbientalYHigieneNum5">Alimentos Sin Almacenar Y No Cubiertos
		<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum6" id="problemaAbientalYHigieneNum6">Personas Que Fuman Dentro De La Vivienda
		<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum7" id="problemaAbientalYHigieneNum7">No Usan Toldillo
		<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum8" id="problemaAbientalYHigieneNum8">Insectos Y Ratones En La Vivienda o Alrededores
		<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum9" id="problemaAbientalYHigieneNum9">Manejo Adecuado De las Basuras/Recoleccion
		<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum10" id="problemaAbientalYHigieneNum10">Se Consume Agua No Potable
		<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum11" id="problemaAbientalYHigieneNum11">Estufa O Brasero Ubicado En La Habitacion
		<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum12" id="problemaAbientalYHigieneNum12">Vivienda Sin Iluminacion y Ventilacion
		<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum13" id="problemaAbientalYHigieneNum13">Evitan Cambios Bruscos De Temperatura
		<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum14" id="problemaAbientalYHigieneNum14">Charcos, Zanjas Y Objetos Donde Se Acumula Agua
		<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum15" id="problemaAbientalYHigieneNum15">Adultos Con Tos O Gripa, Que Cuidan/Alimentan Al Niño Sin Tapaboca
		<p></p>
		Nombre Del Gestor De Calidad De Vida <input type="text" name="nomGeCaVi" id="nomGeCaVi">
		<br>
		Firma De La Persona Que Recibe La Visita <input type="text" name="firmaPersonaEncuestada" id="firmaPersonaEncuestada">
	</form>
