<center><p class="titulo" style = "font-size:35px; color:#2196f3" >FORMULARIO FICHA AIEPI</p></center>
<div class="container">
	<div class="row">
		<form action="<?php echo BASE_URL.'aiepi/nuevo/'.$this->datos['ID_TAREA'];?>" class="col s12" id="formAiepi" name="formAiepi" method="post">
			<input type="hidden" name="guardar" value="1" />
			<ul class="collapsible" data-collapsible="accordion" >
				<li id="l1">
					<div class="collapsible-header blue active white-text text-white white-text text-white" id="seccionDatosUbicacion">Datos de ubicación <div  class="right" id="numPreguntas"></div></div>
					<div class="collapsible-body" id="seccionBodyDatosUbicacion">
						<div class="row">
							<br>
							<div class="input-field col s4">
								<input type="text" name="fechaEncuestaAiepi" placeholder="Fecha" id="fechaEncuestaAiepi" class="datepicker">
								<label class="blue-text text-darken-2 active" for="fechaEncuestaAiepi" value="">1. Fecha</label>
							</div>
							<div class="input-field col s4">
								<input type="text" name="nombreInstitucion" id="nombreInstitucion" class="validate" value="HOSPITAL SAN RAFAEL">
								<label class="blue-text text-darken-2 active" for="nombreInstitucion">2. Institución</label>
							</div>
							<div class="input-field col s4">
								<select name="nombreMunicipio" id="nombreMunicipio" disabled="true">
									<option><?php echo $this->datos['DES_MUNICIPIO']; ?></option>
								</select>
								<label  class="blue-text text-darken-2">3. Municipio</label>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s6">
								<select name="aseguradorAiepi" id="aseguradorAiepi" disabled="true">
									<option><?php echo $this->datos['DES_EPS']; ?></option>
								</select>
								<label for="aseguradorAiepi">4. Asegurador (EPS) <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="EPS a la cual esta afiliado"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></label>
							</div>
							<!-- Los Tipos De Usuarios Se Traen De La Base De Datos -->
							<div class="input-field col s6">
								<select name="tipoDeUsuarioAiepi" id="tipoDeUsuarioAiepi">

									<option value="2">CONTRIBUTIVO</option>
									<option value="3">SUBSIDIADO</option>
									<option value="4">VINCULADO</option>
									<option value="5">POBRE NO ASEGURADO</option>
									<option value="6">ESPECIAL</option>
								</select>
								<label for="tipoDeUsuarioAiepi" class="blue-text text-darken-2" >5. Tipo de usuario <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Régimen de seguridad social al cual corresponde"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></label>
							</div>
						</div>
					</div>
				</li>
				<li>
					<div class="collapsible-header blue white-text text-white">Datos del niño <div  class="right" id="numPreguntasNiño"></div></div>
					<div class="collapsible-body" id="contDatosNiño">
						<div class="row">
							<br>
							<div class="input-field col s12">
								<input type="text" name="nombreNiño" placeholder="Nombres y apellidos" id="nombreNiño" class="validate" value="<?php echo $this->datos['NOMBRE_MIEMBRO'].' '.$this->datos['APELLIDO_MIEMBRO']; ?>" disabled>
								<label class="blue-text text-darken-2 active" for="nombreNiño">6. Nombres y apellidos</label>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s4">
								<input type="text" name="rcNiño" id="rcNiño" class="validate" placeholder="Registro civil" value="<?php echo $this->datos['IDENTIFICACION_MIEMBRO_HOGAR']; ?>" disabled>
								<label for="rcNiño" class="blue-text text-darken-2 active">7. Registro civil</label>
							</div>
							<div class="input-field col s4">
								<input type="text" name="fechNacimientoNiño" id="fechNacimientoNiño" value="<?php echo $this->datos['FECHA_NACIMIENTO']; ?>" disabled>
								<label for="fechNacimientoNiño" class="blue-text text-darken-2 active">8. Fecha De Nacimiento</label>
							</div>
							<label class="blue-text text-darken-2" style = "font-size:15px">9. Genero</label>
							<div class="input-field col s4">
								<?php if ($this->datos['SEXO']=='M'): ?>
									<input class="with-gap" type="radio"  name="generoEncuestaAiepi" id="masculinoGeneroAiepi" value="M" checked disabled>
									<label for="masculinoGeneroAiepi">Masculino</label>
									<input class="with-gap" type="radio"  name="generoEncuestaAiepi" id="femeninoGeneroAiepi" value="F" disabled>
									<label for="femeninoGeneroAiepi">Femenino</label>
								<?php else: ?>
									<input class="with-gap" type="radio"  name="generoEncuestaAiepi" id="masculinoGeneroAiepi" value="M" disabled>
									<label for="masculinoGeneroAiepi">Masculino</label>
									<input class="with-gap" type="radio"  name="generoEncuestaAiepi" id="femeninoGeneroAiepi" value="F" checked disabled>
									<label for="femeninoGeneroAiepi">Femenino</label>
								<?php endif ?>
							</div>
						</div>
						<div class="row">
							<!-- Los Datos Se Traen De La Base De Datos -->
							<div class="input-field col s6">
								<select name="procedenciaAiepi" id="procedenciaAiepi" disabled>
									<?php if ($this->datos['ID_ZONA'] == 1): ?>
										<option value="1" selected>Urbana</option>
									<?php elseif ($this->datos['ID_ZONA'] == 2): ?>
										<option value="2" selected>Rural</option>
									<?php else: ?>
										<option value="3" selected>Centros Poblados</option>
									<?php endif ?>
								</select>
								<label class="blue-text text-darken-2">10. Procedencia</label>
							</div>
							<!-- Los Datos Se Traen De La Base De Datos -->
							<div class="input-field col s6">
								<select name="tipoPoblacionAiepi" id="tipoPoblacionAiepi">
									<option value="" disabled selected>Seleccione tipo de población</option>
									<option value="1">Desplazado</option>
									<option value="2">Desmovilizado</option>
									<option value="3">Raizal</option>
									<option value="4">Menor Abandonado</option>
									<option value="5">Persona En Condicion De Discapacidad</option>
									<option value="6">Afro</option>
									<option value="7">ROM/Gitano</option>
									<option value="8">Palenquero</option>
									<option value="9">Indigena</option>
									<option value="10">Habitante De Calle</option>
									<option value="11">Victima Conflicto Armado</option>
									<option value="12">No Aplica</option>
								</select>
								<label class="blue-text text-darken-2">11. Tipo de población</label>
							</div>
						</div>
					</div>
				</li>
				<li>
					<div class="collapsible-header blue white-text text-white">Datos del acompañante</div>
					<div class="collapsible-body">
						<div class="row">
							<br>
							<div class="input-field col s12">
								<input type="text" name="nombreAcompañanteAiepi" placeholder="Nombres y apellidos del acompañante" id="nombreAcompañanteAiepi" >
								<label for="nombreAcompañanteAiepi" class="blue-text text-darken-2 active">12. Nombres y apellidos del acompañante</label>
							</div>
						</div>
						<div class="row">
							<!-- Los Datos Se Traen De La Base De Datos -->
							<div class="input-field col s6">
								<select name="parentescoAiepi" id="parentescoAiepi">
									<option value="" disabled selected>Seleccione parentesco</option>
									<option value="1">Jefe De Hogar</option>
									<option value="2">Conyuge</option>
									<option value="3">Madre</option>
									<option value="4">Padre</option>
									<option value="5">Hijo(a)</option>
									<option value="6">Hermano(a)</option>
									<option value="7">Abuelos(as)</option>
									<option value="8">Sobrinos</option>
									<option value="9">Madrasta</option>
									<option value="10">Padrastro</option>
									<option value="11">Otros Parientes</option>
									<option value="12">Otros Miembros No Parientes</option>
								</select>
								<label class="blue-text text-darken-2">13. Parentesco <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Que Parentesco Tiene El Acompañante Con El Niño"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></label>
							</div>
							<div class="input-field col s6">
								<input type="text" name="direccionAiepi" placeholder="Dirección" id="direccionAiepi" >
								<label for="direccionAiepi" class="blue-text text-darken-2 active">14. Dirección<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Direccion De Residencia Del acompañante"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></label>
							</div>
							<div class="input-field col s6">
								<input type="text" name="TelefonoAiepi" placeholder="Teléfono" id="TelefonoAiepi">
								<label for="TelefonoAiepi" class="blue-text text-darken-2 active">15. Teléfono <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Numero De Telefono Donde Se Pueda Ubicar"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></label>
							</div>
							<div class="input-field col s6">
								<select name="evaluacionRealizadaAiepi" id="evaluacionRealizadaAiepi">
									<option value="" disabled selected>Seleccione evaluación realizada</option>
									<option value="1">Primera Vez</option>
									<option value="2">Seguimiento</option>
									<option value="3">Por alto riesgo de la familia</option>
									<option value="4">Enfermedad de alto riesgo</option>
								</select>
								<label  class="blue-text text-darken-2">16. Evaluacion realizada <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Realizacion De La Valoracion O Visita"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></label>
							</div>
						</div>
					</div>
				</li>
				<li>
					<div class="collapsible-header blue white-text text-white" id="primeraParte">Primera parte: Identificación de signos generales de riesgo</div>
					<div class="collapsible-body">
						<div class="row">
							<div class="input-field col s4">
								<label for="tipSelecSignoRiesgoOp1" class="blue-text text-darken-2">17. Identificacion de signos generales de riesgo  <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Inicie la valoracion del menor; pregunte, observe y seleccione si el menor presenta alguno de los signos mostrados, de lo contrario seleccion No Aplica"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></label></label>
								<br><br>
								<input type="checkbox" class="filled-in" name="tipSelecSignoRiesgoOp1" id="tipSelecSignoRiesgoOp1" value="1">
								<label for="tipSelecSignoRiesgoOp1" class="black-text text-black"> No puede beber o tomar el pecho</label>
								<br>
								<input type="checkbox" class="filled-in" name="tipSelecSignoRiesgoOp2" id="tipSelecSignoRiesgoOp2" value="2">
								<label for="tipSelecSignoRiesgoOp2" class="black-text text-black"> Letargico</label>
								<br>
								<input type="checkbox" class="filled-in" name="tipSelecSignoRiesgoOp3" id="tipSelecSignoRiesgoOp3" value="3">
								<label for="tipSelecSignoRiesgoOp3" class="black-text text-black"> Inconsciente</label>
								<br>
								<input type="checkbox" class="filled-in" name="tipSelecSignoRiesgoOp4" id="tipSelecSignoRiesgoOp4" value="4">
								<label for="tipSelecSignoRiesgoOp4" class="black-text text-black"> Vomita todo</label>
								<br>
								<input type="checkbox" class="filled-in" name="tipSelecSignoRiesgoOp5" id="tipSelecSignoRiesgoOp5" value="5">
								<label for="tipSelecSignoRiesgoOp5" class="black-text text-black"> Convulsiones</label>
								<br>
								<input type="checkbox" class="filled-in" name="tipSelecSignoRiesgoOp6" id="tipSelecSignoRiesgoOp6" value="6">
								<label for="tipSelecSignoRiesgoOp6" class="black-text text-black"> Ninguna de las anteriores</label>
							</div>
							<div class="input-field col s8">
								<table class="bordered">
									<tbody>
										<tr>
											<td>18. ¿Tiene el niño o niña problemas de salud bucal? <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Indage a la madre si el niño tiene problemas de salud bucal"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
											<td>
												<input class="with-gap" class="with-gap" type="radio" name="opProblemaSaludBocal" id="opProblemaSaludBocalSi" value="1">
												<label for="opProblemaSaludBocalSi">Si</label>
												<input class="with-gap" class="with-gap" type="radio" name="opProblemaSaludBocal" id="opProblemaSaludBocalNo" value="0">
												<label for="opProblemaSaludBocalNo">No</label>
											</td>
										</tr>
										<tr>
											<td>19. ¿Tiene dolor o molestia al comer?<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Realize la valoración de la boca, luego pregunte ¿Tiene dolor o molestia al comer?"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i> </td>
											<td><input class="with-gap" type="radio" name="opDolorAlComer" id="opDolorAlComerSi" value="1">
												<label for="opDolorAlComerSi">Si</label>
												<input class="with-gap" type="radio" name="opDolorAlComer" id="opDolorAlComerNo" value="0">
												<label for="opDolorAlComerNo">No</label></td>
											</tr>
											<tr>
												<td>20. ¿Ha tenido algun golpe en la boca?<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Observe y pregunte ¿ha tenido algún golpe o trauma en la boca?"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
												<td>
													<input class="with-gap" class="with-gap" type="radio" name="opGolpeBoca" id="opGolpeBocaSi" value="1">
													<label for="opGolpeBocaSi" >Si</label>
													<input class="with-gap" class="with-gap" type="radio" name="opGolpeBoca" id="opGolpeBocaNo" value="0">
													<label for="opGolpeBocaNo">No</label>
												</td>
											</tr>
											<tr>
												<td>21. ¿Durante la noche duerme sin cepillarse los dientes? <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Observe y pregunte ¿Durante la noche duerme sin cepillarse los dientes?"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
												<td>
													<input class="with-gap" class="with-gap" type="radio" name="opDuermeSinCepillarse" id="opDuermeSinCepillarseSi" value="1">
													<label for="opDuermeSinCepillarseSi">Si</label>
													<input class="with-gap" class="with-gap" type="radio" name="opDuermeSinCepillarse" id="opDuermeSinCepillarseNo" value="0">
													<label for="opDuermeSinCepillarseNo">No</label>
												</td>
											</tr>
											<tr>
												<td>22. ¿Le supervisa el cepillado de dientes? <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Indage a la madre y pregunte ¿Le supervisa el cepillado de dientes?"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
												<td>
													<input class="with-gap" class="with-gap" type="radio" name="opSupervisaCepillado" id="opSupervisaCepilladoSi" value="1">
													<label for="opSupervisaCepilladoSi">Si</label>
													<input class="with-gap" class="with-gap" type="radio" name="opSupervisaCepillado" id="opSupervisaCepilladoNo" value="0">
													<label for="opSupervisaCepilladoNo">No</label>
												</td>
											</tr>
											<tr>
												<td>23. ¿Le sangra la encia cuando se cepilla?  <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Observe y pregunte ¿Le sangra la encia cuando se cepilla?"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
												<td>
													<input class="with-gap" class="with-gap" type="radio" name="opSangraCuandoCepilla" id="opSangraCuandoCepillaSi" value="1">
													<label for="opSangraCuandoCepillaSi">Si</label>
													<input class="with-gap" class="with-gap" type="radio" name="opSangraCuandoCepilla" id="opSangraCuandoCepillaNo" value="0">
													<label for="opSangraCuandoCepillaNo">No</label>
												</td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>

							<div class="row">

								<div class="input-field col s6">
									<input type="number" placeholder="Número de valoraciones" min="0" name="numValOdontologicasAño" id="numValOdontologicasAño">
									<label for="numValOdontologicasAño" class="blue-text text-darken-2 active">24. N° de valoraciones odontologicas en el último año<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Numero De Visitas al odontologo en el ultimo año"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></label>
								</div>
								<div class="input-field col s6">
									<input type="number" placeholder="Número de veces" min="0" name="numHigieneOralDia" id="numHigieneOralDia">
									<label for="numHigieneOralDia" class="blue-text text-darken-2 active">25. ¿Cuantas veces hace higiene oral al dia?<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Numero de Veces que le hace higiene oral al dia"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></label>
								</div>

							</div>
							<div class="row">
								<div class="input-field col s12">
									<input type="text" name="dascHigOral" id="dascHigOral" placeholder="Respuesta" length="15">
									<label for="dascHigOral" class="blue-text text-darken-2 active">26. ¿Con qué hace la higienización oral?<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Elementos con los que hace higiene oral al niño, Maximo 15 caracteres para la descripcion"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></label>
								</div>
							</div>
						</div>
					</li>
					<li>
						<div class="collapsible-header blue white-text text-white">Segunda Parte: Identificación de signos generales de riesgo</div>
						<div class="collapsible-body">
							<div class="row">
								<div class="input-field col s6">
									<table class="borderer">
										<tbody>
											<tr>
												<td>27. ¿Tiene el niño o niña tos? <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Si la respuesta es NO se deshabilita el numero de dias que lleva con tos Pregunta N°28; la respuesta a esta pregunta responde automaticamente la pregunta N°60"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
												<td>
													<input class="with-gap" type="radio" name="opNiñoConTos" id="opNiñoConTosSi" value="1">
													<label for="opNiñoConTosSi">Si</label>
													<input class="with-gap" type="radio" name="opNiñoConTos" id="opNiñoConTosNo"  value="0">
													<label for="opNiñoConTosNo">No</label>
												</td>
											</tr>
											<tr>
												<td id="tdNumDiasConTos" colspan="2">

													<div class="input-field">
														<input type="number" min="0" placeholder="Número de dias" name="numDiasConTos" id="numDiasConTos">
														<label for="numDiasConTos" class="active blue-text text-darken-2">28. Número de dias que lleva con tos</label>
													</div>

												</td>

											</tr>
											<tr>
												<td>29. ¿Tiene el niño(a) dificultado para respirar?  <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Si la respuesta es NO se deshabilita el numero de dias con dificultad para respirar; Pregunta N°30"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
												<td>
													<input class="with-gap" type="radio" name="opDificultadParaRespirar" id="opDificultadParaRespirarSi" value="1">
													<label for="opDificultadParaRespirarSi">Si</label>
													<input class="with-gap" type="radio" name="opDificultadParaRespirar" id="opDificultadParaRespirarNo" value="0">
													<label for="opDificultadParaRespirarNo">No</label>
												</td>
											</tr>
											<tr>

												<td id="tdNumDiasConDificultadParaRespirar" colspan="2">

													<div class="input-field col s12">
														<input type="number" min="0" placeholder="Número de dias" name="numDiasConDificultadParaRespirar" id="numDiasConDificultadParaRespirar">
														<label for="numDiasConDificultadParaRespirar" class="blue-text text-darken-2 active">30. Número de dias con dificultad para respirar</label>
													</div>

												</td>
											</tr>
										</tbody>
									</table>
								</div>
								<div class="input-field col s6">
									<table class="bordered">
										<tbody>
											<tr>
												<td>31. ¿Tiene tiraje sucostal? <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Evalue al menor y seleccione una opcion"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
												<td>
													<input class="with-gap" class="with-gap" type="radio" name="opTirajeSucostal" id="opTirajeSucostalSi" value="1">
													<label for="opTirajeSucostalSi" >Si</label>
													<input class="with-gap" class="with-gap" type="radio" name="opTirajeSucostal" id="opTirajeSucostalNo" value="0">
													<label for="opTirajeSucostalNo" >No</label>
												</td>
											</tr>
											<tr>
												<td>32. ¿Tiene estridor? <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Evalue al menor y seleccione una opcion"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
												<td>
													<input class="with-gap" class="with-gap" type="radio" name="opTieneEstridor" id="opTieneEstridorSi" value="1">
													<label for="opTieneEstridorSi">Si</label>
													<input class="with-gap" class="with-gap" type="radio" name="opTieneEstridor" id="opTieneEstridorNo" value="0">
													<label for="opTieneEstridorNo" >No</label>
												</td>
											</tr>
											<tr>
												<td colspan="2">

													<div class="input-field">
														<input type="number" min="30" max="99" placeholder="Número de respiraciones" name="numRespiracionesPorMin" id="numRespiracionesPorMin">
														<label for="numRespiracionesPorMin" class="blue-text text-darken-2 active">33. Número de respiraciones por minuto<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Cuente las respiraciones en un minuto y digite el resultado"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></label>
													</div>

												</td>

											</tr>
											<tr>
												<td>34. ¿Tiene respiración rapida?<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Esta pregunta se responde automaticamente despues de que se digite el numero de respiraciones por minuto"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
												<td>
													<input class="with-gap" class="with-gap" type="radio" name="opRespiracionRapida" id="opRespiracionRapidaSi" value="1">
													<label for="opRespiracionRapidaSi" >Si</label>
													<input class="with-gap" class="with-gap" type="radio" name="opRespiracionRapida" id="opRespiracionRapidaNo" value="0">
													<label for="opRespiracionRapidaNo" >No</label>
												</td>
											</tr>
											<tr>
												<td>35. ¿Tiene sibilancias?<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Evalue al menor y seleccione una opcion"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
												<td><input class="with-gap" type="radio" name="opTieneSibilancias" id="opTieneSibilanciasSi" value="1">
													<label for="opTieneSibilanciasSi" >Si</label>
													<input class="with-gap" type="radio" name="opTieneSibilancias" id="opTieneSibilanciasNo" value="0">
													<label for="opTieneSibilanciasNo">No</label></td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</li>
						<li>
							<div class="collapsible-header blue white-text text-white">Tercera Parte: Identificación de signos generales de riesgo</div>
							<div class="collapsible-body">
								<div class="row">
									<div class="input-field col s6">
										<table class="bordered">
											<tbody>
												<tr>
													<td>36. ¿El niño(a) ha estado en cntacto con personas con TB?<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Pregunte a la persona que esta siendo encuestada y seleccione una opcion"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opContactoConPerTb" id="opContactoConPerTbSi" value="1">
														<label for="opContactoConPerTbSi">Si</label>
														<input class="with-gap" type="radio" name="opContactoConPerTb" id="opContactoConPerTbNo" value="0">
														<label for="opContactoConPerTbNo">No</label>
													</td>
												</tr>
												<tr>
													<td>37. ¿El niño(a) ha estado en contacto conpersonas sintomaticas respiratorias?<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Pregunte a la persona que esta siendo encuestada y seleccione una opcion"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opContactoConPerSintomaticasResp" id="opContactoConPerSintomaticasRespSi" value="1">
														<label for="opContactoConPerSintomaticasRespSi">Si</label>
														<input class="with-gap" type="radio" name="opContactoConPerSintomaticasResp" id="opContactoConPerSintomaticasRespNo" value="0">
														<label for="opContactoConPerSintomaticasRespNo">No</label>
													</td>
												</tr>
											</tbody>
										</table>
									</div>
									<div class="input-field col s6">
										<table class="bordered">
											<tbody>
												<tr>
													<td>38. ¿Tos persistente con mas de 21 dias?<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Pregunte a la persona que esta siendo encuestada y seleccione una opcion"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opTosPersistenteMasDe21Dias" id="opTosPersistenteMasDe21DiasSi" value="1" value="1">
														<label for="opTosPersistenteMasDe21DiasSi">Si</label>
														<input class="with-gap" type="radio" name="opTosPersistenteMasDe21Dias" id="opTosPersistenteMasDe21DiasNo" value="0" value="2">
														<label for="opTosPersistenteMasDe21DiasNo">No</label>
													</td>
												</tr>
												<tr>
													<td>39. ¿Perdida o ganancia de peso en los últimos tres meses?<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Pregunte a la persona que esta siendo encuestada y seleccione una opcion"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opPerdidaOGananciaPesoUlt3Meses" id="opPerdidaOGananciaPesoUlt3MesesSi" value="1">
														<label for="opPerdidaOGananciaPesoUlt3MesesSi">Si</label>
														<input class="with-gap" type="radio" name="opPerdidaOGananciaPesoUlt3Meses" id="opPerdidaOGananciaPesoUlt3MesesNo" value="0">
														<label for="opPerdidaOGananciaPesoUlt3MesesNo">No</label>
													</td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</li>
						<li>
							<div class="collapsible-header blue white-text text-white">Cuarta Parte: Identificación de signos generales de riesgo</div>
							<div class="collapsible-body">
								<div class="row">
									<div class="input-field col s6">
										<table class="bordered">
											<tbody>
												<tr>
													<td>40. ¿Tiene el niño(a) diarrea?<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Si la respuesta es NO se deshabilita el numero de dias que lleva con diarrea; Pregunta N°41"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opTieneDiarrea" id="opTieneDiarreaSi" value="1">
														<label for="opTieneDiarreaSi" >Si</label>
														<input class="with-gap" type="radio" name="opTieneDiarrea" id="opTieneDiarreaNo" value="0">
														<label for="opTieneDiarreaNo" >No</label>
													</td>
												</tr>
												<tr>
													<td colspan="2" id="numDiasConDiarreaTd">
														<div class="input-field">
															<input type="number" placeholder="Número de dias" min="0" name="numDiasConDiarrea" id="numDiasConDiarrea">
															<label  for="numDiasConDiarrea" class="blue-text text-darken-2 active">41. N° de dias con diarrea</label>
														</div>
													</td>
												</tr>
												<tr>
													<td>42. Fontanela o molleja hundida <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Pregunte a la persona encuestada y seleccione una opción"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opFontanelaOMollejaHundida" id="opFontanelaOMollejaHundidaSi" value="1">
														<label for="opFontanelaOMollejaHundidaSi">Si</label>
														<input class="with-gap" type="radio" name="opFontanelaOMollejaHundida" id="opFontanelaOMollejaHundidaNo" value="0">
														<label for="opFontanelaOMollejaHundidaNo">No</label>
													</td>
												</tr>
												<tr>
													<td>43. Intranquilo o irritable<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Pregunte a la persona encuestada y seleccione una opción"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opIntranquiloOIrritable" id="opIntranquiloOIrritableSi" value="1">
														<label for="opIntranquiloOIrritableSi">Si</label>
														<input class="with-gap" type="radio" name="opIntranquiloOIrritable" id="opIntranquiloOIrritableNo"  value="0">
														<label for="opIntranquiloOIrritableNo">No</label>
													</td>
												</tr>

											</tbody>
										</table>
									</div>
									<div class="input-field col s6">
										<table class="bordered">
											<tbody>
												<tr>
													<td>44. ¿Hay sangre en las heces? <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Pregunte a la persona encuestada, evalue al menor y seleccione una opcion"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opSangreEnHeces" id="opSangreEnHecesSi" value="1">
														<label for="opSangreEnHecesSi">Si</label>
														<input class="with-gap" type="radio" name="opSangreEnHeces" id="opSangreEnHecesNo" value="0">
														<label for="opSangreEnHecesNo">No</label>
													</td>
												</tr>
												<tr>
													<td>45. Boca seca o mucha sed  <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Pregunte a la persona encuestada, evalue al menor y seleccione una opcion"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opBocaSecaOMuchaSed" id="opBocaSecaOMuchaSedSi" value="1">
														<label for="opBocaSecaOMuchaSedSi">Si</label>
														<input class="with-gap" type="radio" name="opBocaSecaOMuchaSed" id="opBocaSecaOMuchaSedNo"  value="0">
														<label for="opBocaSecaOMuchaSedNo">No</label>
													</td>
												</tr>
												<tr>
													<td>46. Ojos hundidos  <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip="Pregunte a la persona encuestada, evalue al menor y seleccione una opcion"><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opOjosUndidos" id="opOjosUndidosSi" value="1">
														<label for="opOjosUndidosSi">Si</label>
														<input class="with-gap" type="radio" name="opOjosUndidos" id="opOjosUndidosNo" value="0">
														<label for="opOjosUndidosNo">No</label>
													</td>
												</tr>
												<tr>
													<td>
														47. Pliegue cutaneo - muy lento mayor a 2 seg <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Evalue el pliegue cutaneo si selecciona "SI", la pregunta N°48 quedara como "NO"'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i>
													</td>
													<td>
														<input class="with-gap" type="radio" name="opPliegueCutaneoMuyLento" id="opPliegueCutaneoMuyLentoSi" value="1">
														<label for="opPliegueCutaneoMuyLentoSi">Si</label>
														<input class="with-gap" type="radio" name="opPliegueCutaneoMuyLento" id="opPliegueCutaneoMuyLentoNo"  value="0">
														<label for="opPliegueCutaneoMuyLentoNo">No</label>
													</td>
												</tr>
												<tr>
													<td>
														48. Pliegue cutaneo - lento 2 seg o menor <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Evalue el pliegue cutaneo si selecciona "SI", la pregunta N°47 quedara como "NO"'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i>
													</td>
													<td>
														<input class="with-gap" type="radio" name="opPliegueCutaneoLento" id="opPliegueCutaneoLentoSi" value="1">
														<label for="opPliegueCutaneoLentoSi">Si</label>
														<input class="with-gap" type="radio" name="opPliegueCutaneoLento" id="opPliegueCutaneoLentoNo" value="0">
														<label for="opPliegueCutaneoLentoNo">No</label>
													</td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
							</li>
							<li>
								<div class="collapsible-header blue white-text text-white">Quinta Parte: Identificación de signos generales de riesgo</div>
								<div class="collapsible-body">
									<div class="row">
										<div class="input-field col s6">
											<table class="bordered">
												<tr>
													<td>49. ¿El niño(a) tiene fiebre?<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Indage a la persona encuestada, evalue al menor y seleccione una opcion; Si la respuesta es "NO" las preguntas N°50 y N°51 quedan deshabilitadas'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opNiñoConFiebre" id="opNiñoConFiebreSi" value="1">
														<label for="opNiñoConFiebreSi">Si</label>
														<input class="with-gap" type="radio" name="opNiñoConFiebre" id="opNiñoConFiebreNo" value="0">
														<label for="opNiñoConFiebreNo">No</label>
													</td>
												</tr>
												<tr>
													<td colspan="2">
														<div class="input-field" id="divNumDiasFiebre">
															<input type="number" min="0" placeholder="Número de dias" name="numDiasConFiebre" id="numDiasConFiebre" size="8">
															<label for="numDiasConFiebre" class="blue-text text-darken-2 active">50. N° dias con fiebre<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Preungte a la persona encuestada, evalue al menor y digite el numero de dias que lleva el menor con fiebre'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></label>
														</div>
													</td>
												</tr>
												<tr id="divFiebreMas5D">
													<td>51. Fiebre de mas de 5 dias todos los dias<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Esta pregunta se responde automaticamente despues de que digite el numero de dias que lleva con fiebre'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opFiebreMasDe5DiasTodosLosDias" id="opFiebreMasDe5DiasTodosLosDiasSi" value="1">
														<label for="opFiebreMasDe5DiasTodosLosDiasSi">Si</label>
														<input class="with-gap" type="radio" name="opFiebreMasDe5DiasTodosLosDias" id="opFiebreMasDe5DiasTodosLosDiasNo" value="0">
														<label for="opFiebreMasDe5DiasTodosLosDiasNo">No</label>
													</td>
												</tr>
												<tr>
													<td>52. Vive o visito zona de riesgo de malaria<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Pregunte a la persona encuestada y seleccione una opcion'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opViveOVisitoZonaMalaria" id="opViveOVisitoZonaMalariaSi" value="1">
														<label for="opViveOVisitoZonaMalariaSi">Si</label>
														<input class="with-gap" type="radio" name="opViveOVisitoZonaMalaria" id="opViveOVisitoZonaMalariaNo" value="0">
														<label for="opViveOVisitoZonaMalariaNo">No</label>
													</td>
												</tr>
												<tr>
													<td>53.Vive o visito zona de riesgo de dengue<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Pregunte a la persona encuestada y seleccione una opcion'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opViveVistZonaDenge" id="opViveVistZonaDengeSi" value="1">
														<label for="opViveVistZonaDengeSi">Si</label>
														<input class="with-gap" type="radio" name="opViveVistZonaDenge" id="opViveVistZonaDengeNo" value="0">
														<label for="opViveVistZonaDengeNo">No</label>
													</td>
												</tr>
												<tr>
													<td colspan="2">
														<div class="input-field">
															<select name="zonaVive" id="zonaVive">
																<option value="" disabled selected>Seleccione zona</option>
																<option value="1">Urbana</option>
																<option value="2">Rural</option>
															</select>
															<label for="zonaVive" class="blue-text text-darken-2" >54. Zona<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Seleccione la zona en la que vive o visito en menor valorado'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></label>
														</div>
													</td>
												</tr>
												<tr>
													<td>55. Rigidez de nuca<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe, evalue al menor y seleccione una opción'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opRigidezDeNuca" id="opRigidezDeNucaSi" value="1">
														<label for="opRigidezDeNucaSi">Si</label>
														<input class="with-gap" type="radio" name="opRigidezDeNuca" id="opRigidezDeNucaNo" value="0">
														<label for="opRigidezDeNucaNo">No</label>
													</td>
												</tr>
												<tr>
													<td>56. Manifestación de sangrado <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe, evalue al menor y seleccione una opción'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opManifiestaSangrado" id="opManifiestaSangradoSi"  value="1">
														<label for="opManifiestaSangradoSi">Si</label>
														<input class="with-gap" type="radio" name="opManifiestaSangrado" id="opManifiestaSangradoNo" value="0">
														<label for="opManifiestaSangradoNo">No</label>
													</td>
												</tr>
											</table>
										</div>
										<div class="input-field col s6">
											<table class="bordered">
												<tr>
													<td>57. Piel humeda y fria <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe, evalue al menor y seleccione una opción'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opPielHumedaYFria" id="opPielHumedaYFriaSi" value="1">
														<label for="opPielHumedaYFriaSi">Si</label>
														<input class="with-gap" type="radio" name="opPielHumedaYFria" id="opPielHumedaYFriaNo" value="0">
														<label for="opPielHumedaYFriaNo">No</label>
													</td>
												</tr>
												<tr>
													<td>58. Inquieto o irritable <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe, evalue al menor y seleccione una opción'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opInquitoOIrritable" id="opInquitoOIrritableSi"   value="1">
														<label for="opInquitoOIrritableSi">Si</label>
														<input class="with-gap" type="radio" name="opInquitoOIrritable" id="opInquitoOIrritableNo" value="0">
														<label for="opInquitoOIrritableNo">No</label>
													</td>
												</tr>
												<tr>
													<td>59. Fiebre mayor de 39°C <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe, evalue al menor y seleccione una opción'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opFiebreMayorDe39C" id="opFiebreMayorDe39CSi" value="1">
														<label for="opFiebreMayorDe39CSi">Si</label>
														<input class="with-gap" type="radio" name="opFiebreMayorDe39C" id="opFiebreMayorDe39CNo" value="0">
														<label for="opFiebreMayorDe39CNo">No</label>
													</td>
												</tr>
												<tr>
													<td>60. Tos<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Esta pregunta se responde automaticamente, si no esta respondida redirijase a la pregunta N°27'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opTieneTos" id="opTieneTosSi"  value="1">
														<label for="opTieneTosSi">Si</label>
														<input class="with-gap" type="radio" name="opTieneTos" id="opTieneTosNo" value="0">
														<label for="opTieneTosNo">No</label>
													</td>
												</tr>
												<tr>
													<td>61. Coriza<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='"Coriza:inflamación de la mucosa de la nariz de evolución aguda", evalue este caso y seleccione una opcion'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opCoriza" id="opCorizaSi" value="1">
														<label for="opCorizaSi">Si</label>
														<input class="with-gap" type="radio" name="opCoriza" id="opCorizaNo" value="0">
														<label for="opCorizaNo">No</label>
													</td>
												</tr>
												<tr>
													<td>62. Ojos rojos<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe, evalue al menor y seleccione una opción'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opOjosRojos" id="opOjosRojosSi" value="1">
														<label for="opOjosRojosSi">Si</label>
														<input class="with-gap" type="radio" name="opOjosRojos" id="opOjosRojosNo"  value="0">
														<label for="opOjosRojosNo">No</label>
													</td>
												</tr>
												<tr>
													<td>63. Aspecto toxico<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe, evalue al menor y seleccione una opción'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opAspectoToxico" id="opAspectoToxicoSi" value="1">
														<label for="opAspectoToxicoSi">Si</label>
														<input class="with-gap" type="radio" name="opAspectoToxico" id="opAspectoToxicoNo" value="0">
														<label for="opAspectoToxicoNo">No</label>
													</td>
												</tr>
												<tr>
													<td>64. Dolor abdominal continuo o intenso<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe, evalue al menor y seleccione una opción'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opDolorAbdominalContOInt" id="opDolorAbdominalContOIntSi"  value="1">
														<label for="opDolorAbdominalContOIntSi">Si</label>
														<input class="with-gap" type="radio" name="opDolorAbdominalContOInt" id="opDolorAbdominalContOIntNo" value="0">
														<label for="opDolorAbdominalContOIntNo">No</label>
													</td>
												</tr>
												<tr>
													<td>65. Pulso rápido y debil <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe, evalue al menor y seleccione una opción'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opPulsoRapidoYDebil" id="opPulsoRapidoYDebilSi" value="1">
														<label for="opPulsoRapidoYDebilSi">Si</label>
														<input class="with-gap" type="radio" name="opPulsoRapidoYDebil" id="opPulsoRapidoYDebilNo" value="0">
														<label for="opPulsoRapidoYDebilNo">No</label>
													</td>
												</tr>
												<tr>
													<td>66. Erupción cutanea y generalizada<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe, evalue al menor y seleccione una opción'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
													<td>
														<input class="with-gap" type="radio" name="opErupcionCutaneaYGeneral" id="opErupcionCutaneaYGeneralSi"  value="1">
														<label for="opErupcionCutaneaYGeneralSi">Si</label>
														<input class="with-gap" type="radio" name="opErupcionCutaneaYGeneral" id="opErupcionCutaneaYGeneralNo" value="0">
														<label for="opErupcionCutaneaYGeneralNo">No</label>
													</td>
												</tr>
											</table>
										</div>
									</div>
								</div>
							</li>
							<li>
								<div class="collapsible-header blue white-text text-white">Riesgo para cancer infantil/leucemias</div>
								<div class="collapsible-body">
									<div class="row">
										<div class="input-field col s6">
											<table class="bordered">
												<tbody>
													<tr>
														<td>67. Fiebre por mas de 14 días y/o sudoración<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Pregunte a la persona encuestada, evalue al menor y seleccione una opcion'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
														<td>
															<input class="with-gap" type="radio" name="opFiebreMasDe14Dias" id="opFiebreMasDe14DiasSi" value="1">
															<label for="opFiebreMasDe14DiasSi">Si</label>
															<input class="with-gap" type="radio" name="opFiebreMasDe14Dias" id="opFiebreMasDe14DiasNo" value="0">
															<label for="opFiebreMasDe14DiasNo">No</label>
														</td>
													</tr>
													<tr>
														<td>68. Dolor de cabeza reciente que aumenta<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Pregunte a la persona encuestada, evalue al menor y seleccione una opcion, si la respuesta es "NO" las preguntas N°69, N°70 y N° 71 quedan deshabilitadas'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
														<td>
															<input class="with-gap" type="radio" name="opDolorDeCabezaRecAumenta" id="opDolorDeCabezaRecAumentaSi" value="1">
															<label for="opDolorDeCabezaRecAumentaSi">Si</label>
															<input class="with-gap" type="radio" name="opDolorDeCabezaRecAumenta" id="opDolorDeCabezaRecAumentaNo" value="0">
															<label for="opDolorDeCabezaRecAumentaNo">No</label>
														</td>
													</tr>
													<tr id="divDolorCaezaDespierta">
														<td>69. El dolor de cabeza despierta al niño<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Pregunte a la persona encuestada, evalue al menor y seleccione una opcion'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
														<td>
															<input class="with-gap" type="radio" name="opDolorDeCabezaDespiertaAlNiño" id="opDolorDeCabezaDespiertaAlNiñoSi" value="1">
															<label for="opDolorDeCabezaDespiertaAlNiñoSi">Si</label>
															<input class="with-gap" type="radio" name="opDolorDeCabezaDespiertaAlNiño" id="opDolorDeCabezaDespiertaAlNiñoNo" value="0">
															<label for="opDolorDeCabezaDespiertaAlNiñoNo">No</label>
														</td>
													</tr>
													<tr>
														<td colspan="2" id="divNumDiasColCabeza">
															<div class="input-field col s12" id="numDiasConDolorDeCabeza">
																<input type="number" min="0" name="numDiasConDolorDeCabeza" placeholder="Número de dias" id="numDiasConDolorDeCabeza">
																<label for="numDiasConDolorDeCabeza" class="blue-text text-darken-2 active">70. Número de dias que el niño tiene dolor de cabeza<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Pregunte a la persona encuestada y digite el numero de dias que el niño tiene dolor de cabeza'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></label>
															</div>
														</td>
													</tr>
													<tr id="divDolAcompVom">
														<td>71. El dolor de cabeza se acompaña de otro sintoma como vomito<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Pregunte a la persona encuestada, evalue al menor y seleccione una opcion'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
														<td>
															<input class="with-gap" type="radio" name="opDolorDeCabezaAcompañadoConVomito" id="opDolorDeCabezaAcompañadoConVomitoSi" value="1">
															<label for="opDolorDeCabezaAcompañadoConVomitoSi">Si</label>
															<input class="with-gap" type="radio" name="opDolorDeCabezaAcompañadoConVomito" id="opDolorDeCabezaAcompañadoConVomitoNo" value="0">
															<label for="opDolorDeCabezaAcompañadoConVomitoNo">No</label>
														</td>
													</tr>
												</tbody>
											</table>
										</div>
										<div class="input-field col s6">
											<table class="bordered">
												<tbody>

													<tr>
														<td>72. Ah tenido dolor de huesos en el último mes<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Pregunte a la persona encuestada, evalue al menor y seleccione una opcion; si la respuesta es "NO" las preguntas N°73 y N°74 quedaran deshabilitadas'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
														<td>
															<input class="with-gap" type="radio" name="opDolorDeHuesosEnElUltimoMes" id="opDolorDeHuesosEnElUltimoMesSi" value="1">
															<label for="opDolorDeHuesosEnElUltimoMesSi">Si</label>
															<input class="with-gap" type="radio" name="opDolorDeHuesosEnElUltimoMes" id="opDolorDeHuesosEnElUltimoMesNo" value="0">
															<label for="opDolorDeHuesosEnElUltimoMesNo">No</label>
														</td>
													</tr>
													<tr id="divDolHuesosInterrupe">
														<td>73. Dolor de huesos interrumpe las actividades del niño<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Pregunte a la persona encuestada, evalue al menor y seleccione una opcion'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
														<td>
															<input class="with-gap" type="radio" name="opDolorHuesosInterrumpeActNiño" id="opDolorHuesosInterrumpeActNiñoSi" value="1">
															<label for="opDolorHuesosInterrumpeActNiñoSi">Si</label>
															<input class="with-gap" type="radio" name="opDolorHuesosInterrumpeActNiño" id="opDolorHuesosInterrumpeActNiñoNo" value="0">
															<label for="opDolorHuesosInterrumpeActNiñoNo">No</label>
														</td>
													</tr>
													<tr id="dolHuesosAumento">
														<td>74. El dolor de huesos ha ido en aumento<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Pregunte a la persona encuestada, evalue al menor y seleccione una opcion'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
														<td>
															<input class="with-gap" type="radio" name="opDolorDeHuesosEnAumento" id="opDolorDeHuesosEnAumentoSi" value="1">
															<label for="opDolorDeHuesosEnAumentoSi">Si</label>
															<input class="with-gap" type="radio" name="opDolorDeHuesosEnAumento" id="opDolorDeHuesosEnAumentoNo" value="0">
															<label for="opDolorDeHuesosEnAumentoNo">No</label>
														</td>
													</tr>
													<tr>
														<td>75. En los últimos 3 meses ha tenido cambios como fatiga, perdida de apetito o peso<i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Pregunte a la persona encuestada, evalue al menor y seleccione una opcion'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
														<td>
															<input class="with-gap" type="radio" name="opUlt3MesesCambiosFatiga" id="opUlt3MesesCambiosFatigaSi" value="1">
															<label for="opUlt3MesesCambiosFatigaSi">Si</label>
															<input class="with-gap" type="radio" name="opUlt3MesesCambiosFatiga" id="opUlt3MesesCambiosFatigaNo" value="0">
															<label for="opUlt3MesesCambiosFatigaNo">No</label>
														</td>
													</tr>
												</tbody>
											</table>
										</div>
									</div>
								</div>
							</li>
							<li>
								<div class="collapsible-header blue white-text text-white">Problemas de oido</div>
								<div class="collapsible-body">
									<div class="row">
										<div class="input-field col s6">
											<table class="bordered">
												<tbody>
													<tr>
														<td>76. El niño(a) tiene problemas de oido <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe, evalue al menor y seleccione una opción; si esocogio "NO" la pregunta N° 77 se deshabilita'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
														<td>
															<input class="with-gap" type="radio" name="opProblemasDeOido" id="opProblemasDeOidoSi" value="1">
															<label for="opProblemasDeOidoSi">Si</label>
															<input class="with-gap" type="radio" name="opProblemasDeOido" id="opProblemasDeOidoNo" value="0">
															<label for="opProblemasDeOidoNo">No</label>
														</td>
													</tr>
													<tr>
														<td colspan="2">
															<div class="input-field col s10" id="divNumEpiPreviosOido">
																<input type="number" min="0" placeholder="Número de episodios" name="numDeEpisodiosPrevios" id="numDeEpisodiosPrevios">
																<label for="numDeEpisodiosPrevios" class="blue-text text-darken-2 active">77. Número de episodios previos <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Pregunte al acompañante el numero de episodios previos y digite la respuesta'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></label>
															</div>
														</td>
													</tr>
												</tbody>
											</table>
										</div>
										<div class="input-field col s6">
											<table class="bordered">
												<tbody>
													<tr>
														<td>78. Tiene supuración de oido <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Pregunte al encuestado, evalue al menor y seleccione una opcion, si selecciona "NO" la pregunta N° 79 se deshabilitara'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
														<td>
															<input class="with-gap" type="radio" name="opSupuracionDeOido" id="opSupuracionDeOidoSi" value="1">
															<label for="opSupuracionDeOidoSi">Si</label>
															<input class="with-gap" type="radio" name="opSupuracionDeOido" id="opSupuracionDeOidoNo" value="0">
															<label for="opSupuracionDeOidoNo">No</label>
														</td>
													</tr>
													<tr>
														<td colspan="2">
															<div class="input-field col s10" id="divNumDiasSupuracion">
																<input type="number" min="0" placeholder="Número de dias" name="numDiasConSupuracion" id="numDiasConSupuracion">
																<label for="numDiasConSupuracion" class="blue-text text-darken-2 active">79. Hace cuantos dias <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Pregunte al encuestado, y digite el resultado'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></label>
															</div>
														</td>
													</tr>
													<tr>
														<td>80. Tumefacción/dolor atrás de la oreja <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Pregunte al encuestado, evalue al menor y seleccione una opcion'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
														<td>
															<input class="with-gap" type="radio" name="opDolorAtrasDeLaOreja" id="opDolorAtrasDeLaOrejaSi" value="1">
															<label for="opDolorAtrasDeLaOrejaSi">Si</label>
															<input class="with-gap" type="radio" name="opDolorAtrasDeLaOreja" id="opDolorAtrasDeLaOrejaNo" value="0">
															<label for="opDolorAtrasDeLaOrejaNo">No</label>
														</td>
													</tr>
												</tbody>
											</table>
										</div>
									</div>
								</div>
							</li>
							<li>
								<div class="collapsible-header blue white-text text-white">Problemas de desnutrición</div>
								<div class="collapsible-body">
									<div class="row">
										<div class="input-field col s2">

										</div>
										<div class="input-field col s">
											<table class="bordered">
												<tbody>
													<tr>
														<td>81. El niño(a) tiene desnutrición y/o anemia <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Pregunte al encuestado, evalue al menor y seleccione una opcion'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
														<td><input class="with-gap" type="radio" name="opNiñoDesnutricionOAnemia" id="opNiñoDesnutricionOAnemiaSi" value="1">
															<label for="opNiñoDesnutricionOAnemiaSi">Si</label>
															<input class="with-gap" type="radio" name="opNiñoDesnutricionOAnemia" id="opNiñoDesnutricionOAnemiaNo" value="0">
															<label for="opNiñoDesnutricionOAnemiaNo">No</label></td>
														</tr>
														<tr>
															<td>82. Retraso en el crecimiento <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe y evalue al menor luego seleccione una respuesta'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
															<td>
																<input class="with-gap" type="radio" name="opRetrasoDeCrecimiento" id="opRetrasoDeCrecimientoIntenso" value="1">
																<label for="opRetrasoDeCrecimientoIntenso">Muy intenso</label>
																<input class="with-gap" type="radio" name="opRetrasoDeCrecimiento" id="opRetrasoDeCrecimientoMarcado"  value="0">
																<label for="opRetrasoDeCrecimientoMarcado">Menos marcado</label>
															</td>
														</tr>
														<tr>
															<td>83. Valoración de la cara <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe y evalue la cara del menor luego seleccione una respuesta'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
															<td>
																<input class="with-gap" type="radio" name="opValoracionDeCara" id="opValoracionDeCaraViejito"  value="1">
																<label for="opValoracionDeCaraViejito">Cara de viejito</label>
																<input class="with-gap" type="radio" name="opValoracionDeCara" id="opValoracionDeCaraLunaLlena"  value="0">
																<label for="opValoracionDeCaraLunaLlena">Cara de luna llena</label>
															</td>
														</tr>
														<tr>
															<td>84. Perdida de tejido muscular <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe y evalue al menor luego seleccione una respuesta'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
															<td>
																<input class="with-gap" type="radio" name="opPerdidaTejidoMusc" id="opPerdidaTejidoMuscMuyMarcada"  value="1">
																<label for="opPerdidaTejidoMuscMuyMarcada">Muy marcada</label>
																<input class="with-gap" type="radio" name="opPerdidaTejidoMusc" id="opPerdidaTejidoMuscMarcada"  value="0">
																<label for="opPerdidaTejidoMuscMarcada">Marcada</label>
															</td>
														</tr>
														<tr>
															<td>85. El sistema oseo <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe y evalue al menor luego seleccione una respuesta'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
															<td>
																<input class="with-gap" type="checkbox" name="opSistemaOseoCostalVisible" id="opSistemaOseoCostalVisible"  value="557">
																<label for="opSistemaOseoCostalVisible">Rosario costal visible</label>
																<br>
																<input class="with-gap" type="checkbox" name="opSistemaOseoPiernasDeSable" id="opSistemaOseoPiernasDeSable"  value="558">
																<label for="opSistemaOseoPiernasDeSable">Piernas de sable</label>
															</td>
														</tr>
														<tr>
															<td>86. Tejido adiposo <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe y evalue al menor luego seleccione una respuesta'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
															<td>
																<input class="with-gap" type="radio" name="opTejidoAdiposo" id="opTejidoAdiposoAusente"  value="1">
																<label for="opTejidoAdiposoAusente">Ausente</label>
																<input class="with-gap" type="radio" name="opTejidoAdiposo" id="opTejidoAdiposoPocoDisminuido"  value="0">
																<label for="opTejidoAdiposoPocoDisminuido">Poco disminuido</label>
															</td>
														</tr>
														<tr>
															<td>87. Comportamiento <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe y evalue al menor luego seleccione una respuesta'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
															<td>
																<input class="with-gap" type="checkbox" name="opComportamientoMirada" id="opComportamientoMirada"  value="559">
																<label for="opComportamientoMirada">Mirada de angustia</label>
																<br>
																<input class="with-gap" type="checkbox" name="opComportamientoLlanto" id="opComportamientoLlanto"  value="560">
																<label for="opComportamientoLlanto">Llanto/Apatia</label>
															</td>
														</tr>
														<tr>
															<td>88. Apetito <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Pregunte al encuestado, evalue al menor y seleccione una opcion'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
															<td>
																<input class="with-gap" type="radio" name="opApetito" id="opApetitoDisminuido"  value="1">
																<label for="opApetitoDisminuido">Disminuido</label>
																<input class="with-gap" type="radio" name="opApetito" id="opApetitoAumentado"  value="0">
																<label for="opApetitoAumentado">Aumentado</label>
															</td>
														</tr>
														<tr>
															<td>89. Edema <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe y evalue al menor luego seleccione una respuesta'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
															<td>
																<input class="with-gap" type="radio" name="opEdema" id="opEdemaSi"  value="1">
																<label for="opEdemaSi">Si</label>
																<input class="with-gap" type="radio" name="opEdema" id="opEdemaNo"  value="0">
																<label for="opEdemaNo">No</label>
															</td>
														</tr>
														<tr>
															<td>90. Cabello <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Observe y evalue el cabello del menor luego seleccione una respuesta'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></td>
															<td>
																<input class="with-gap" type="radio" name="opCabello" id="opCabelloEscaso"  value="1">
																<label for="opCabelloEscaso">Escaso</label>
																<input class="with-gap" type="radio" name="opCabello" id="opCabelloDebil"  value="0">
																<label for="opCabelloDebil">Debil</label>
															</td>
														</tr>
													</tbody>
												</table>
											</div>
											<div class="input-field col s2">

											</div>
										</div>
									</div>
								</li>
								<li>
									<div class="collapsible-header blue white-text text-white">Perimetro braquial</div>
									<div class="collapsible-body">
										<div class="row">
											<div class="input-field col s4">
												<input type="number" name="mediaMarcaColorBrazo" id="mediaMarcaColorBrazo" placeholder="Valor">
												<label for="mediaMarcaColorBrazo" class="blue-text text-darken-2 active">92. Medida</label>
											</div>
											<div class="input-field col s7" id="colorPerimetro">
												<!--Color:Marcar El Color Obtenido Al Medir La Circunferencia En El Punto Medio Del Brazo-->
												<select name="opMarcaDelColorBrazo" id="opMarcaDelColorBrazo">
													<option value="" disabled selected>Perimetro braquial</option>
													<option value="8">Rojo</option>
													<option value="9">Naranja</option>
													<option value="10">Amarillo</option>
													<option value="11">Verde</option>
												</select>
												<label class="blue-text text-darken-2">91. Toma del perimetro bracial <i class="tiny material-icons tooltipped" data-position="top"  data-delay="50" data-tooltip='Esta pregunta se responde automaticamente, si no esta respondida redirijase a la pregunta N°27'><img class="" src="<?php echo $_layoutParams['ruta_img']; ?>help.png"></i></label>
											</div>
											
										</div>
									</div>
								</li>
								<li id="contMedidasProtecMenor6Meses" hidden="true">
									<div class="collapsible-header blue white-text text-white">Aplicación de medidas de protección de salud niños menores de 6 meses</div>
									<div class="collapsible-body">
										<div class="row">
											<br>
											<div class="input-field col s3">
												93. ¿El lactante toma seno?
											</div>
											<div class="input-field col s3">
												<input class="with-gap" type="radio" name="opTomaSenoMen6Meses" id="opTomaSenoMen6MesesSi" value="1">
												<label for="opTomaSenoMen6MesesSi">Si</label>
												<input class="with-gap" type="radio" name="opTomaSenoMen6Meses" id="opTomaSenoMen6MesesNo" value="0">
												<label for="opTomaSenoMen6MesesNo">No</label>
											</div>
											<br>
											<div class="input-field col s3" id="numVecesTomaSenoDiaMen6Meses">
												<input type="number" min="0" value="0" name="numVecesTomaSenoDiaMen6Meses" id="numVecesTomaSenoDiaMen6Meses">
												<label for="numVecesTomaSenoDiaMen6Meses" class="blue-text text-darken-2">94. ¿Cuantas veces toma seno en el dia?</label>
											</div>
											<div class="input-field col s3" id="numVecesTomaSenoNocheMen6Meses">
												<input type="number" min="0" value="0" name="numVecesTomaSenoNocheMen6Meses" id="numVecesTomaSenoNocheMen6Meses">
												<label for="numVecesTomaSenoNocheMen6Meses" class="blue-text text-darken-2">95. ¿Cuantas veces toma seno en la noche?</label>
											</div>
										</div>
										<div class="row">
											<div class="input-field col s6" id="posicionTomaSeno">
												<p class="blue-text text-darken-2">
													96. La posición:
													<br><input type="checkbox" class="filled-in" name="posicionTomaSenoNum1" id="posicionTomaSenoNum1" value="12">
													<label for="posicionTomaSenoNum1">El lactante esta en dirección al pecho de la madre con la nariz frente al pezón</label>
													<br><input type="checkbox" class="filled-in" name="posicionTomaSenoNum2" id="posicionTomaSenoNum2" value="13">
													<label for="posicionTomaSenoNum2">El cuerpo del lactante esta frente a la madre</label>
													<br><input type="checkbox" class="filled-in" name="posicionTomaSenoNum3" id="posicionTomaSenoNum3" value="14">
													<label for="posicionTomaSenoNum3">La madre sostiene todo el cuerpo del niño(a)</label>
												</p>
											</div>
											<div class="input-field col s6" id="agarreTomaSeno">
												<p class="blue-text text-darken-2">
													97. Agarre
													<br><input type="checkbox" class="filled-in" name="agarreTomaSenoNum1" id="agarreTomaSenoNum1" value="15">
													<label for="agarreTomaSenoNum1">El menton toca el seno</label>
													<br><input type="checkbox" class="filled-in" name="agarreTomaSenoNum2" id="agarreTomaSenoNum2" value="16">
													<label for="agarreTomaSenoNum2">El labio inferior esta hacia afuera</label>
													<br><input type="checkbox" class="filled-in" name="agarreTomaSenoNum3" id="agarreTomaSenoNum3" value="17">
													<label for="agarreTomaSenoNum3">Aureola se va mas arriba que abajo</label>
												</p>
											</div>
										</div>
										<div class="row">
											<div class="input-field col s6">
												<p class="blue-text text-darken-2">
													98. ¿Tiene alguna dificultad para amamantarlo?
													<br>
													<input type="checkbox" class="filled-in" name="dificultadParaAmamantarNum1" id="dificultadParaAmamantarNum1" value="18">
													<label for="dificultadParaAmamantarNum1">No lacta</label>
													<br><input type="checkbox" class="filled-in" name="dificultadParaAmamantarNum2" id="dificultadParaAmamantarNum2" value="19">
													<label for="dificultadParaAmamantarNum2">No tiene dificultad</label>
													<br><input type="checkbox" class="filled-in" name="dificultadParaAmamantarNum3" id="dificultadParaAmamantarNum3" value="20">
													<label for="dificultadParaAmamantarNum3">Le duele</label>
													<br><input type="checkbox" class="filled-in" name="dificultadParaAmamantarNum4" id="dificultadParaAmamantarNum4" value="21">
													<label for="dificultadParaAmamantarNum4">No le baja leche</label>
													<br><input type="checkbox" class="filled-in" name="dificultadParaAmamantarNum5" id="dificultadParaAmamantarNum5" value="22">
													<label for="dificultadParaAmamantarNum5">Produce mucha leche</label>
													<br><input type="checkbox" class="filled-in" name="dificultadParaAmamantarNum6" id="dificultadParaAmamantarNum6" value="23">
													<label for="dificultadParaAmamantarNum6">Laceración del pezon</label>
													<br><input type="checkbox" class="filled-in" name="dificultadParaAmamantarNum7" id="dificultadParaAmamantarNum7" value="24">
													<label for="dificultadParaAmamantarNum7">Hospitalización</label>
													<br><input type="checkbox" class="filled-in" name="dificultadParaAmamantarNum8" id="dificultadParaAmamantarNum8" value="25">
													<label for="dificultadParaAmamantarNum8">Otro</label>
												</p>
									<!--
									<div class="row">
										<div class="input-field col s8">
											<input type="text" name="dificultadParaAmamantarOtro" id="dificultadParaAmamantarOtro">
											<label for="dificultadParaAmamantarOtro">¿Cual?</label>
																					</div>
																				</div>-->
																			</div>
																			<div class="input-field col s6">
																				<p class="blue-text text-darken-2">
																					99. ¿El lactante recibe habitualmente otros alimentos?
																					<br><input type="checkbox" class="filled-in" name="lactRecibeOtrosAlimentosNum1" id="lactRecibeOtrosAlimentosNum1" value="26">
																					<label for="lactRecibeOtrosAlimentosNum1">Otra leche</label>
																					<br><input type="checkbox" class="filled-in" name="lactRecibeOtrosAlimentosNum2" id="lactRecibeOtrosAlimentosNum2" value="27">
																					<label for="lactRecibeOtrosAlimentosNum2">Jugo</label>
																					<br><input type="checkbox" class="filled-in" name="lactRecibeOtrosAlimentosNum3" id="lactRecibeOtrosAlimentosNum3" value="28">
																					<label for="lactRecibeOtrosAlimentosNum3">Agua</label>
																					<br><input type="checkbox" class="filled-in" name="lactRecibeOtrosAlimentosNum4" id="lactRecibeOtrosAlimentosNum4" value="29">
																					<label for="lactRecibeOtrosAlimentosNum4">Colada</label>
																					<br><input type="checkbox" class="filled-in" name="lactRecibeOtrosAlimentosNum5" id="lactRecibeOtrosAlimentosNum5" value="30">
																					<label for="lactRecibeOtrosAlimentosNum5">Papillas</label>
																					<br><input type="checkbox" class="filled-in" name="lactRecibeOtrosAlimentosNum6" id="lactRecibeOtrosAlimentosNum6" value="31">
																					<label for="lactRecibeOtrosAlimentosNum6">No Recibe</label>
																				</p>
																			</div>
																		</div>
																		<div class="row">
																			<div class="input-field col s6">
																				<p class="blue-text text-darken-2">
																					100. Estos alimentos contienen
																					<br><input type="checkbox" class="filled-in" name="alimentosContienenSal" id="alimentosContienenSal" value="32">
																					<label for="alimentosContienenSal">Sal</label>
																					<br><input type="checkbox" class="filled-in" name="alimentosContienenAzucar" id="alimentosContienenAzucar"  value="33">
																					<label for="alimentosContienenAzucar">Azúcar</label>
																				</p>
																			</div>
																			<div class="input-field col s6">
																				<p class="blue-text text-darken-2">
																					101 ¿Qué utiliza para alimentar al lactante?
																					<br><input type="checkbox" class="filled-in" name="utilizaParaAlimentarNum1" id="utilizaParaAlimentarNum1" value="34">
																					<label for="utilizaParaAlimentarNum1">Tetero</label>
																					<br><input type="checkbox" class="filled-in" name="utilizaParaAlimentarNum2" id="utilizaParaAlimentarNum2" value="35">
																					<label for="utilizaParaAlimentarNum2">Tasa</label>
																					<br><input type="checkbox" class="filled-in" name="utilizaParaAlimentarNum3" id="utilizaParaAlimentarNum3" value="36">
																					<label for="utilizaParaAlimentarNum3">Cuchara</label>
																					<br><input type="checkbox" class="filled-in" name="utilizaParaAlimentarNum4" id="utilizaParaAlimentarNum4" value="37">
																					<label for="utilizaParaAlimentarNum4">Otro:</label>
										<!--
										<div class="row">
																						<div class="input-field">
												<input type="text" name="utilizaParaAlimentarOtro" id="utilizaParaAlimentarOtro">
												<label for="utilizaParaAlimentarOtro">¿Cual?</label>
																						</div>
																					</div>-->
																				</p>
																			</div>
																		</div>
																	</div>
																</li>
																<li id="contMedidasProtecMayor6Meses" hidden="true">
																	<div class="collapsible-header blue white-text text-white">Aplicación de medidas de protección de salud niños de 6 meses a 5 Años</div>
																	<div class="collapsible-body">
																		<div class="row">
																			<div class="input-field col s4">
																				<p class="blue-text text-darken-2">
																					93. ¿El niño(a) toma seno?
																					<br>
																					<input class="with-gap" type="radio" name="opTomaSenoMas6Meses" id="opTomaSenoMas6MesesSi" value="1">
																					<label for="opTomaSenoMas6MesesSi">Si</label>
																					<input class="with-gap" type="radio" name="opTomaSenoMas6Meses" id="opTomaSenoMas6MesesNo" value="0">
																					<label for="opTomaSenoMas6MesesNo">No</label>
																				</p>
																			</div>
																			<br>
																			<br>
																			<div class="input-field col s4" id="numVecesTomaSenoDiaMas6Meses">
																				<input type="number" min="0" value="0" name="numVecesTomaSenoDiaMas6Meses" id="numVecesTomaSenoDiaMas6Meses">
																				<label for="numVecesTomaSenoDiaMas6Meses" class="blue-text text-darken-2">94. ¿Cuantas veces toma seno en el dia?</label>
																			</div>
																			<div class="input-field col s4" id="numVecesTomaSenoNocheMas6Meses">
																				<input type="number" min="0" value="0" name="numVecesTomaSenoNocheMas6Meses" id="numVecesTomaSenoNocheMas6Meses">
																				<label for="numVecesTomaSenoNocheMas6Meses" class="blue-text text-darken-2">95. ¿Cuantas veces toma seno en la noche?</label>
																			</div>
																		</div>
																		<div class="row">
																			<div class="input-field col s4">
																				<p class="blue-text text-darken-2">
																					96. ¿El niño usa biberon?
																					<br>
																					<input class="with-gap" type="radio" name="opUsaBiberon" id="opUsaBiberonSi" value="1">
																					<label for="opUsaBiberonSi">Si</label>
																					<input class="with-gap" type="radio" name="opUsaBiberon" id="opUsaBiberonNo" value="0">
																					<label for="opUsaBiberonNo">No</label>
																				</p>
																			</div>
																			<div class="input-field col s4">
																				<p class="blue-text text-darken-2">97. ¿Qué toma el niño(a)?
																					<br><input type="checkbox" class="filled-in" name="queTomaElNiñoNum1" id="queTomaElNiñoNum1" value="38">
																					<label for="queTomaElNiñoNum1">Aguadepanela</label>
																					<br><input type="checkbox" class="filled-in" name="queTomaElNiñoNum2" id="queTomaElNiñoNum2" value="39">
																					<label for="queTomaElNiñoNum2">Leche</label>
																					<br><input type="checkbox" class="filled-in" name="queTomaElNiñoNum3" id="queTomaElNiñoNum3" value="40">
																					<label for="queTomaElNiñoNum3">Colada</label>
																					<br><input type="checkbox" class="filled-in" name="queTomaElNiñoNum4" id="queTomaElNiñoNum4" value="41">
																					<label for="queTomaElNiñoNum4">Sopa</label>
																					<br><input type="checkbox" class="filled-in" name="queTomaElNiñoNum5" id="queTomaElNiñoNum5" value="42">
																					<label for="queTomaElNiñoNum5">Gaseosa</label>
																					<br><input type="checkbox" class="filled-in" name="queTomaElNiñoNum6" id="queTomaElNiñoNum6" value="43">
																					<label for="queTomaElNiñoNum6">Otro:</label>
																				</p>
									<!--
									<input type="text" name="queTomaElNiñoOtro" id="queTomaElNiñoOtro">-->
								</div>
								<div class="input-field col s4">
									<p class="blue-text text-darken-2">98. ¿Cuál es la consistencia de los alimentos?
										<br><input type="checkbox" class="filled-in" name="consistenciaDeAlimentosNum1" id="consistenciaDeAlimentosNum1" value="44">
										<label for="consistenciaDeAlimentosNum1">Liquida</label>
										<br><input type="checkbox" class="filled-in" name="consistenciaDeAlimentosNum2" id="consistenciaDeAlimentosNum2" value="45">
										<label for="consistenciaDeAlimentosNum2">Crema</label>
										<br><input type="checkbox" class="filled-in" name="consistenciaDeAlimentosNum3" id="consistenciaDeAlimentosNum3" value="46">
										<label for="consistenciaDeAlimentosNum3">Papilla</label>
										<br><input type="checkbox" class="filled-in" name="consistenciaDeAlimentosNum4" id="consistenciaDeAlimentosNum4" value="47">
										<label for="consistenciaDeAlimentosNum4">Otro:</label>
									</p>
									<!--
									<input type="text" name="consistenciaDeAlimentosOtro" id="consistenciaDeAlimentosOtro">-->
								</div>
							</div>
							<div class="row">
								<div class="input-field col s12">
									<div class="row">
										<div class="input-field col s4">
											99. ¿El niño come solo?
											<br>
											<input class="with-gap" type="radio" name="opComeSolo" id="opComeSoloSi" value="1">
											<label for="opComeSoloSi">Si</label>
											<input class="with-gap" type="radio" name="opComeSolo" id="opComeSoloNo" value="0">
											<label for="opComeSoloNo">No</label>
										</div>
										<br><br>
										<div class="input-field col s4">
											<input type="text" name="alimentosConMayorFrecuencia" id="alimentosConMayorFrecuencia" placeholder="Descripción">
											<label for="alimentosConMayorFrecuencia" class="blue-text text-darken-2">100. ¿Qué alimentos le da con mayor frecuencia al niño?</label>
										</div>
										<div class="input-field col s4">
											101. ¿Esta en algún programa de recuperación nutricional?
											<br>
											<input class="with-gap" type="radio" name="opProgramaRecuperacionNutri" id="opProgramaRecuperacionNutriSi" value="1">
											<label for="opProgramaRecuperacionNutriSi">Si</label>
											<input class="with-gap" type="radio" name="opProgramaRecuperacionNutri" id="opProgramaRecuperacionNutriNo" value="0">
											<label for="opProgramaRecuperacionNutriNo">No</label>
											<div class="row">
												<div class="input-field col s12" id="programaNutri">
													<label for="programaRecuperacionNutri">¿Cuál?</label>
													<input type="text" name="programaRecuperacionNutri" id="programaRecuperacionNutri" placeholder="Descripción">
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</li>
					<li>
						<div class="collapsible-header blue white-text text-white" id="evaluaDesarrollo">Evalue el desarrollo</div>
						<div class="collapsible-body">
							<div class="row">
								<div class="input-field col s6">
									<table class="bordered">
										<tbody>
											<tr id="1013Meses">
												<td class="blue-text text-darken-2">
													102. A los 3 meses levanta la cabeza
												</td>
												<td>
													<input class="with-gap" type="radio" name="op3MesesLevantaCabeza" id="op3MesesLevantaCabezaSi" value="1">
													<label for="op3MesesLevantaCabezaSi">Si</label>
													<input class="with-gap" type="radio" name="op3MesesLevantaCabeza" id="op3MesesLevantaCabezaNo" value="0">
													<label for="op3MesesLevantaCabezaNo">No</label>
													<input class="with-gap" type="radio" name="op3MesesLevantaCabeza" id="op3MesesLevantaCabezaNA" value="2">
													<label for="op3MesesLevantaCabezaNA">N/A</label>
												</td>
											</tr>
											<tr id="1016Meses">
												<td class="blue-text text-darken-2">103. A los 6 meses se sienta con aoyo</td>
												<td>
													<input class="with-gap" type="radio" name="op6MesesSeSientaConApoyo" id="op6MesesSeSientaConApoyoSi" value="1">
													<label for="op6MesesSeSientaConApoyoSi">Si</label>
													<input class="with-gap" type="radio" name="op6MesesSeSientaConApoyo" id="op6MesesSeSientaConApoyoNo" value="0">
													<label for="op6MesesSeSientaConApoyoNo">No</label>
													<input class="with-gap" type="radio" name="op6MesesSeSientaConApoyo" id="op6MesesSeSientaConApoyoNA" value="2">
													<label for="op6MesesSeSientaConApoyoNA">N/A</label>
												</td>
											</tr>
											<tr id="1019Meses" >
												<td class="blue-text text-darken-2">104. A los 9 meses se sienta por si solo</td>
												<td>
													<input class="with-gap" type="radio" name="op9MesesSeSientaPorSiSolo" id="op9MesesSeSientaPorSiSoloSi" value="1">
													<label for="op9MesesSeSientaPorSiSoloSi">Si</label>
													<input class="with-gap" type="radio" name="op9MesesSeSientaPorSiSolo" id="op9MesesSeSientaPorSiSoloNo" value="0">
													<label for="op9MesesSeSientaPorSiSoloNo">No</label>
													<input class="with-gap" type="radio" name="op9MesesSeSientaPorSiSolo" id="op9MesesSeSientaPorSiSoloNA" value="2">
													<label for="op9MesesSeSientaPorSiSoloNA">N/A</label>
												</td>
											</tr>
											<tr id="10112Meses" >
												<td class="blue-text text-darken-2">
													105. A los 12 meses camina por si solo
												</td>
												<td>
													<input class="with-gap" type="radio" name="op12MesesCaminaSolo" id="op12MesesCaminaSoloSi" value="1">
													<label for="op12MesesCaminaSoloSi">Si</label>
													<input class="with-gap" type="radio" name="op12MesesCaminaSolo" id="op12MesesCaminaSoloNo" value="0">
													<label for="op12MesesCaminaSoloNo">No</label>
													<input class="with-gap" type="radio" name="op12MesesCaminaSolo" id="op12MesesCaminaSoloNA" value="2">
													<label for="op12MesesCaminaSoloNA">N/A</label>
												</td>
											</tr>
										</tbody>
									</table>
									<table class="bordered">
										<tbody>
											<tr id="10116Meses">
												<td class="blue-text text-darken-2">106. A los 16 meses camina solo</td>
												<td>
													<input class="with-gap" type="radio" name="op16MesesCaminaSolo" id="op16MesesCaminaSoloSi" value="1">
													<label for="op16MesesCaminaSoloSi">Si</label>
													<input class="with-gap" type="radio" name="op16MesesCaminaSolo" id="op16MesesCaminaSoloNo" value="0">
													<label for="op16MesesCaminaSoloNo">No</label>
													<input class="with-gap" type="radio" name="op16MesesCaminaSolo" id="op16MesesCaminaSoloNA" value="2">
													<label for="op16MesesCaminaSoloNA">N/A</label>
												</td>
											</tr>
											<tr id="10120Meses">
												<td class="blue-text text-darken-2">107. A los 20 meses corre rápido</td>
												<td>
													<input class="with-gap" type="radio" name="op20MesesCorreRapido" id="op20MesesCorreRapidoSi" value="1">
													<label for="op20MesesCorreRapidoSi">Si</label>
													<input class="with-gap" type="radio" name="op20MesesCorreRapido" id="op20MesesCorreRapidoNo" value="0">
													<label for="op20MesesCorreRapidoNo">No</label>
													<input class="with-gap" type="radio" name="op20MesesCorreRapido" id="op20MesesCorreRapidoNA" value="2">
													<label for="op20MesesCorreRapidoNA">N/A</label>
												</td>
											</tr>
										</tbody>
									</table>
								</div>
								<div class="input-field col s6">
									<table>
										<tbody>
											<tr id="10124Meses">
												<td class="blue-text text-darken-2">108. A los 24 meses patea la pelota</td>
												<td>
													<input class="with-gap" type="radio" name="op24MesesPateaPelota" id="op24MesesPateaPelotaSi" value="1">
													<label for="op24MesesPateaPelotaSi">Si</label>
													<input class="with-gap" type="radio" name="op24MesesPateaPelota" id="op24MesesPateaPelotaNo" value="0">
													<label for="op24MesesPateaPelotaNo">No</label>
													<input class="with-gap" type="radio" name="op24MesesPateaPelota" id="op24MesesPateaPelotaNA" value="2">
													<label for="op24MesesPateaPelotaNA">N/A</label>
												</td>
											</tr>
											<tr id="10130Meses">
												<td class="blue-text text-darken-2">
													109. A los 30 meses se empina en ambos pies</td>
													<td>
														<input class="with-gap" type="radio" name="op30MesesSeEmpinaPies" id="op30MesesSeEmpinaPiesSi" value="1">
														<label for="op30MesesSeEmpinaPiesSi">Si</label>
														<input class="with-gap" type="radio" name="op30MesesSeEmpinaPies" id="op30MesesSeEmpinaPiesNo" value="0">
														<label for="op30MesesSeEmpinaPiesNo">No</label>
														<input class="with-gap" type="radio" name="op30MesesSeEmpinaPies" id="op30MesesSeEmpinaPiesNA" value="2">
														<label for="op30MesesSeEmpinaPiesNA">N/A</label>
													</td>
												</tr>
											</tbody>
										</table>
										<table class="bordered">
											<tbody>
												<tr id="10136Meses">
													<td class="blue-text text-darken-2">110. A los 36 meses sube/baja escaleras solo</td>
													<td>
														<input class="with-gap" type="radio" name="op36MesesSubeEscaleras" id="op36MesesSubeEscalerasSi" value="1">
														<label for="op36MesesSubeEscalerasSi">Si</label>
														<input class="with-gap" type="radio" name="op36MesesSubeEscaleras" id="op36MesesSubeEscalerasNo" value="0">
														<label for="op36MesesSubeEscalerasNo">No</label>
														<input class="with-gap" type="radio" name="op36MesesSubeEscaleras" id="op36MesesSubeEscalerasNA" value="2">
														<label for="op36MesesSubeEscalerasNA">N/A</label>
													</td>
												</tr>
												<tr id="10148Meses">
													<td class="blue-text text-darken-2">111. A los 48 meses lanza y atrapa la pelota</td>
													<td>
														<input class="with-gap" type="radio" name="op48MesesLanzaPelota" id="op48MesesLanzaPelotaSi" value="1">
														<label for="op48MesesLanzaPelotaSi">Si</label>
														<input class="with-gap" type="radio" name="op48MesesLanzaPelota" id="op48MesesLanzaPelotaNo" value="0">
														<label for="op48MesesLanzaPelotaNo">No</label>
														<input class="with-gap" type="radio" name="op48MesesLanzaPelota" id="op48MesesLanzaPelotaNA" value="2">
														<label for="op48MesesLanzaPelotaNA">N/A</label>
													</td>
												</tr>
												<tr id="10160Meses">
													<td class="blue-text text-darken-2" >112. A los 60 meses se para y salta en un pie</td>
													<td>
														<input class="with-gap" type="radio" name="op60MesesSeParaYSalta1Pie" id="op60MesesSeParaYSalta1PieSi" value="1">
														<label for="op60MesesSeParaYSalta1PieSi">Si</label>
														<input class="with-gap" type="radio" name="op60MesesSeParaYSalta1Pie" id="op60MesesSeParaYSalta1PieNo" value="0">
														<label for="op60MesesSeParaYSalta1PieNo">No</label>
														<input class="with-gap" type="radio" name="op60MesesSeParaYSalta1Pie" id="op60MesesSeParaYSalta1PieNA" value="2">
														<label for="op60MesesSeParaYSalta1PieNA">N/A</label>
													</td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</li>
						<li>
							<div class="collapsible-header blue white-text text-white">Evalue la aderencia al programa de crecimiento y desarrollo</div>
							<div class="collapsible-body">
								<div class="row">
									<div class="input-field col s6">
										<table>
											<tbody>
												<tr>
													<td WIDTH="500" colspan="2">
													<div class="input-field col s12">
															<input type="number" min="0" placeholder="Número de consultas" name="numConsultasCrecimiento" id="numConsultasCrecimiento">
															<label for="numConsultasCrecimiento" class="blue-text text-darken-2 active">113. Número de consultas de crecimiento y desarrollo</label>
														</div>
													</td>
												</tr>
												<tr id="divRecibiDesparacitacion">
													<td>114. Recibió desparacitación</td>
													<td >
													<div class="input-field col s12">
														<input class="with-gap" type="radio" name="opRecibioDesparacitacion" id="opRecibioDesparacitacionSi" value="1">
														<label for="opRecibioDesparacitacionSi">Si</label>
														<input class="with-gap" type="radio" name="opRecibioDesparacitacion" id="opRecibioDesparacitacionNo" value="0">
														<label for="opRecibioDesparacitacionNo">No</label>
														</div>
													</td>
												</tr>
												<tr id="divFechaRecibeDesparitacion">
													<td colspan="2">
														<div class="input-field col s12" id="fechaDeDesparacitacion">
															<input type="text" name="fechaDeDesparacitacion" id="fechaDeDesparacitacion" class="datepicker" placeholder="Seleccione fecha">
															<label for="fechaDeDesparacitacion" class="blue-text text-darken-2 active" >115. Fecha de desparacitación</label>
														</div>
													</td>
												</tr>
											</tbody>
										</table>
									</div>
									<div class="input-field col s6">
										<table>
											<tbody>
												<tr>
													<td>116. ¿El niño recibe micronutrientes?</td>
													<td>
													<div class="input-field col s12">
														<input class="with-gap" type="radio" name="opRecibeMicronutrientes" id="opRecibeMicronutrientesSi" value="1">
														<label for="opRecibeMicronutrientesSi">Si</label>
														<input class="with-gap" type="radio" name="opRecibeMicronutrientes" id="opRecibeMicronutrientesNo" value="0">
														<label for="opRecibeMicronutrientesNo">No</label>
														</div>
													</td>
												</tr>
												<tr>
													<td colspan="2">
														<div class="input-field col s12" id="descripcionMicronutrientes">
															<input type="text" name="descripcionMicronutrientes" id="descripcionMicronutrientes" placeholder="¿Cuales son?">
															<label for="descripcionMicronutrientes" class="blue-text text-darken-2 active">117. ¿Cuales son?</label>
														</div>
													</td>
												</tr>
												<tr>
													<td colspan="2">
														<div class="input-field" id="fechaEntregaMicronutrientes">
															<input type="text" name="fechaEntregaMicronutrientes" id="fechaEntregaMicronutrientes" class="datepicker" placeholder="Seleccione Fecha">
															<label for="fechaEntregaMicronutrientes" class="blue-text text-darken-2 active">118. Fecha de última entrega</label>
														</div>
													</td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</li>
						<li>
							<div class="collapsible-header blue white-text text-white">Evaluación del buen trato</div>
							<div class="collapsible-body">
								<div class="row">
									<div class="input-field col s4">
										<br>
										119. Le sonrien
										<br><br>
										120. Alzan o arrulla al niño(a)
										<br><br>
										121. Se preocupan por la higiene
										<br><br>
										122. Se preocupan por su salud
									</div>
									<div class="input-field col s2">
										<input class="with-gap" type="radio" name="opLeSonrien" id="opLeSonrienSi" value="1">
										<label for="opLeSonrienSi">Si</label>
										<input class="with-gap" type="radio" name="opLeSonrien" id="opLeSonrienNo" value="0">
										<label for="opLeSonrienNo">No</label>
										<br><br>
										<input class="with-gap" type="radio" name="opArrullan" id="opArrullanSi" value="1">
										<label for="opArrullanSi">Si</label>
										<input class="with-gap" type="radio" name="opArrullan" id="opArrullanNo" value="0">
										<label for="opArrullanNo">No</label>
										<br><br>
										<input class="with-gap" type="radio" name="opPreocupanPorLaHigiene" id="opPreocupanPorLaHigieneSi" value="1">
										<label for="opPreocupanPorLaHigieneSi">Si</label>
										<input class="with-gap" type="radio" name="opPreocupanPorLaHigiene" id="opPreocupanPorLaHigieneNo" value="0">
										<label for="opPreocupanPorLaHigieneNo">No</label>
										<br><br>
										<input class="with-gap" type="radio" name="opSePreocupanPorSalud" id="opSePreocupanPorSaludSi" value="1">
										<label for="opSePreocupanPorSaludSi">Si</label>
										<input class="with-gap" type="radio" name="opSePreocupanPorSalud" id="opSePreocupanPorSaludNo" value="0">
										<label for="opSePreocupanPorSaludNo">No</label>
									</div>
									<div class="input-field col s4">
										<br>
										123. Lo acompañan
										<br><br>
										124. Le juegan o permiten que juegue
										<br><br>
										125. Lo castigan con correa, palmadas, patadas o puños
										<br><br>
										126. Tiene accidentes frecuentes
									</div>
									<div class="input-field col s2">
										<input class="with-gap" type="radio" name="opLeAcompañan" id="opLeAcompañanSi" value="1">
										<label for="opLeAcompañanSi">Si</label>
										<input class="with-gap" type="radio" name="opLeAcompañan" id="opLeAcompañanNo" value="0">
										<label for="opLeAcompañanNo">No</label>
										<br><br>
										<input class="with-gap" type="radio" name="opJuegan" id="opJueganSi" value="1">
										<label for="opJueganSi">Si</label>
										<input class="with-gap" type="radio" name="opJuegan" id="opJueganNo" value="0">
										<label for="opJueganNo">No</label>
										<br><br><br>
										<input class="with-gap" type="radio" name="opCastigan" id="opCastiganSi" value="1">
										<label for="opCastiganSi">Si</label>
										<input class="with-gap" type="radio" name="opCastigan" id="opCastiganNo" value="0">
										<label for="opCastiganNo">No</label>
										<br><br>
										<input class="with-gap" type="radio" name="opAccidentesFrecuentes" id="opAccidentesFrecuentesSi" value="1">
										<label for="opAccidentesFrecuentesSi">Si</label>
										<input class="with-gap" type="radio" name="opAccidentesFrecuentes" id="opAccidentesFrecuentesNo" value="0">
										<label for="opAccidentesFrecuentesNo">No</label>
									</div>
								</div>
							</div>
						</li>
						<li>
							<div class="collapsible-header blue white-text text-white">Riesgos de accidentes en el hogar</div>
							<div class="collapsible-body">
								<div class="row">
									<div class="input-field col s6">
										<table class="bordered">
											<tbody>
												<tr>
													<td class="blue-text text-darken-2">127. Esta solo tomandose el tetero</td>
													<td>
														<input class="with-gap" type="radio" name="opSoloTomandoseTetero" id="opSoloTomandoseTeteroSi" value="1">
														<label for="opSoloTomandoseTeteroSi">Si</label>
														<input class="with-gap" type="radio" name="opSoloTomandoseTetero" id="opSoloTomandoseTeteroNo" value="0">
														<label for="opSoloTomandoseTeteroNo">No</label>
													</td>
												</tr>
												<tr>
													<td class="blue-text text-darken-2">128. Objetos pequeños al alcance de los niños</td>
													<td>
														<input class="with-gap" type="radio" name="opObjPequeñosAlAlcance" id="opObjPequeñosAlAlcanceSi" value="1">
														<label for="opObjPequeñosAlAlcanceSi">Si</label>
														<input class="with-gap" type="radio" name="opObjPequeñosAlAlcance" id="opObjPequeñosAlAlcanceNo" value="0">
														<label for="opObjPequeñosAlAlcanceNo">No</label>
													</td>
												</tr>
												<tr>
													<td class="blue-text text-darken-2">129. Niños en la cocina</td>
													<td>
														<input class="with-gap" type="radio" name="opNiñosEnCocina" id="opNiñosEnCocinaSi" value="1">
														<label for="opNiñosEnCocinaSi">Si</label>
														<input class="with-gap" type="radio" name="opNiñosEnCocina" id="opNiñosEnCocinaNo" value="0">
														<label for="opNiñosEnCocinaNo">No</label>
													</td>
												</tr>
												<tr>
													<td class="blue-text text-darken-2">130. Cuchillos, serruchos, tijeras al alcance de los niños</td>
													<td>
														<input class="with-gap" type="radio" name="opCuchillosAlAlcance" id="opCuchillosAlAlcanceSi" value="1">
														<label for="opCuchillosAlAlcanceSi">Si</label>
														<input class="with-gap" type="radio" name="opCuchillosAlAlcance" id="opCuchillosAlAlcanceNo" value="0">
														<label for="opCuchillosAlAlcanceNo">No</label>
													</td>
												</tr>
												<tr>
													<td class="blue-text text-darken-2">131. Medicamentos-insecticidas al alcance de los niños</td>
													<td>
														<input class="with-gap" type="radio" name="opMedicamentosAlAlcance" id="opMedicamentosAlAlcanceSi" value="1">
														<label for="opMedicamentosAlAlcanceSi">Si</label>
														<input class="with-gap" type="radio" name="opMedicamentosAlAlcance" id="opMedicamentosAlAlcanceNo" value="0">
														<label for="opMedicamentosAlAlcanceNo">No</label>
													</td>
												</tr>
											</tbody>
										</table>
									</div>
									<div class="input-field col s6">
										<table class="bordered">
											<tbody>
												<tr>
													<td class="blue-text text-darken-2">132. Escaleras-terrazas sin barandas-ventanas sin protección</td>
													<td>
														<input class="with-gap" type="radio" name="opEscalerasSinBarandas" id="opEscalerasSinBarandasSi" value="1">
														<label for="opEscalerasSinBarandasSi">Si</label>
														<input class="with-gap" type="radio" name="opEscalerasSinBarandas" id="opEscalerasSinBarandasNo" value="0">
														<label for="opEscalerasSinBarandasNo">No</label>
													</td>
												</tr>
												<tr>
													<td class="blue-text text-darken-2">133. Velas y fósforos al alcance de los niños</td>
													<td>
														<input class="with-gap" type="radio" name="opVelasAlAlcance" id="opVelasAlAlcanceSi" value="1">
														<label for="opVelasAlAlcanceSi">Si</label>
														<input class="with-gap" type="radio" name="opVelasAlAlcance" id="opVelasAlAlcanceNo" value="0">
														<label for="opVelasAlAlcanceNo">No</label>
													</td>
												</tr>
												<tr>
													<td class="blue-text text-darken-2">134. Agua almacenada sin tapa</td>
													<td>
														<input class="with-gap" type="radio" name="opAguaAlmacenadaSinTapa" id="opAguaAlmacenadaSinTapaSi" value="1">
														<label for="opAguaAlmacenadaSinTapaSi">Si</label>
														<input class="with-gap" type="radio" name="opAguaAlmacenadaSinTapa" id="opAguaAlmacenadaSinTapaNo" value="0">
														<label for="opAguaAlmacenadaSinTapaNo">No</label>
													</td>
												</tr>
												<tr>
													<td class="blue-text text-darken-2">135. Enchufes y cables descubiertos</td>
													<td>
														<input class="with-gap" type="radio" name="opCablesDescubieros" id="opCablesDescubierosSi" value="1">
														<label for="opCablesDescubierosSi">Si</label>
														<input class="with-gap" type="radio" name="opCablesDescubieros" id="opCablesDescubierosNo" value="0">
														<label for="opCablesDescubierosNo">No</label>
													</td>
												</tr>
												<tr>
													<td class="blue-text text-darken-2">136. Existen otros riesgos para el niño en el hogar</td>
													<td>
														<input class="with-gap" type="radio" name="opRiesgosEnElHogar" id="opRiesgosEnElHogarSi" value="1">
														<label for="opRiesgosEnElHogarSi">Si</label>
														<input class="with-gap" type="radio" name="opRiesgosEnElHogar" id="opRiesgosEnElHogarNo" value="0">
														<label for="opRiesgosEnElHogarNo">No</label>
													</td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</li>
						<li>
							<div class="collapsible-header blue white-text text-white">Problemas ambientales y de higiene</div>
							<div class="collapsible-body">
								<div class="row">
									<div class="input-field col s12" class="blue-text text-darken-2">
										137. Problemas ambientales y de higiene
									</div>
								</div>
								<div class="row">
									<div class="input-field col s4">
										<input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum1" id="problemaAbientalYHigieneNum1" value="542">
										<label for="problemaAbientalYHigieneNum1">Niños o adultos con ropa sucia</label>
										<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum2" id="problemaAbientalYHigieneNum2" value="543">
										<label for="problemaAbientalYHigieneNum2">Niños o adultos con manos y uñas sucias</label>
										<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum3" id="problemaAbientalYHigieneNum3" value="544">
										<label for="problemaAbientalYHigieneNum3">Niños descalzos</label>
										<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum4" id="problemaAbientalYHigieneNum4" value="545">
										<label for="problemaAbientalYHigieneNum4">Basura y desorden de la vivienda</label>
										<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum5" id="problemaAbientalYHigieneNum5" value="546">
										<label for="problemaAbientalYHigieneNum5">Alimentos sin almacenar y no cubiertos</label>
									</div>
									<div class="input-field col s4">
										<input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum6" id="problemaAbientalYHigieneNum6" value="547">
										<label for="problemaAbientalYHigieneNum6">Personas que fuman dentro de la vivienda</label>
										<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum7" id="problemaAbientalYHigieneNum7" value="548">
										<label for="problemaAbientalYHigieneNum7">No usan toldillo</label>
										<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum8" id="problemaAbientalYHigieneNum8" value="549">
										<label for="problemaAbientalYHigieneNum8">Insectos y ratones en la vivienda o alrededores</label>
										<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum9" id="problemaAbientalYHigieneNum9" value="550">
										<label for="problemaAbientalYHigieneNum9">Manejo adecuado de las Basuras/Recolección</label>
										<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum10" id="problemaAbientalYHigieneNum10" value="551">
										<label for="problemaAbientalYHigieneNum10">Se consume agua no potable</label>
									</div>
									<div class="input-field col s4">
										<input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum11" id="problemaAbientalYHigieneNum11" value="552">
										<label for="problemaAbientalYHigieneNum11">Estufa o brasero ubicado nn la habitacion</label>
										<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum12" id="problemaAbientalYHigieneNum12" value="553">
										<label for="problemaAbientalYHigieneNum12">Vivienda sin iluminación y ventilación</label>
										<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum13" id="problemaAbientalYHigieneNum13" value="554">
										<label for="problemaAbientalYHigieneNum13">Evitan cambios bruscos de temperatura</label>
										<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum14" id="problemaAbientalYHigieneNum14" value="555">
										<label for="problemaAbientalYHigieneNum14">Charcos, zanjas y objetos donde se acumula agua</label>
										<br><input type="checkbox" class="filled-in" name="problemaAbientalYHigieneNum15" id="problemaAbientalYHigieneNum15" value="556">
										<label for="problemaAbientalYHigieneNum15">Adultos con tos o gripa, que cuidan/alimentan al niño sin tapaboca</label>
									</div>
								</div>
							</div>
						</li>
					</ul>

					<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
						<a class="floating "><img src="<?php echo $_layoutParams['ruta_img']; ?>img.png"></a>
					</div>

					<br>
					<center>
						<button class="btn-large waves-effect waves-light blue" type="submit" name="action">Enviar
							<i class="material-icons right">send</i>
						</button>
					</center>
				</form>
				<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
			</div>
		</div>

<script>	
$('#l1 .collapsible-header').removeClass('blue');
$('#l1 .collapsible-header').addClass('visto');
$('li .collapsible-header').click(function(){
$(this).removeClass('blue');
$(this).addClass('visto');
});

	</script>
<style type="text/css">
   .visto{
   	background-color: #2e7d32;
   }
</style>
