<style type="text/css">
  #canvas{
    border: 1px solid  #000;
    box-shadow: 2px 2px 10px #333;
  }
</style>

<div class="container">
  <div class="row">
    <br>
    <div class="col s10 offset-s1">
      <div class="card white z-depth-2">
        <div class="card-content black-text">
         <center><span style="font-size: 45px; font-weight: normal;" class="card-title blue-text">REGISTRO DE NUEVO USUARIO</span></center>
         <br>

         <form name="form1" method="post" action="">
          <input type="hidden" value="1" name="enviar" />

          <div class="row">
            <div class="input-field col s6 ">
              <input id="nombre" type="text" class="validate" name="nombre" value="<?php if(isset($this->datos)) echo $this->datos['nombre']; ?>">
              <label for="nombre">Nombres</label>
            </div>

            <div class="input-field col s6 ">
              <input id="apellido" type="text" class="validate" name="apellido" value="<?php if(isset($this->datos)) echo $this->datos['apellido']; ?>">
              <label for="apellido">Apellidos</label>
            </div>
          </div>

          <div class="row">
            <div class="input-field col s6 ">
              <input id="documento" type="text" class="validate" name="documento" value="<?php if(isset($this->datos)) echo $this->datos['documento']; ?>">
              <label for="nombre">Identificaci&oacute;n</label>
            </div>

            <div class="">
              <div class="input-field col s6">
                <select id="rol" class="browser-default" class="validate" name="rol">
                  <option value="" disabled selected>Seleccione un rol</option>
                  <option value="ESPECIAL">Administrador</option>
                  <option value="USUARIO">Usuario</option>
                </select>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="input-field col s6 ">
              <input id="pass" type="password" class="validate" name="pass">
              <label for="pass">Contraseña</label>
            </div>

            <div class="input-field col s6 ">
              <input id="confirmar" type="password" class="validate" name="confirmar">
              <label for="confirmar">Confirmar contraseña</label>
            </div>
          </div>

          <script>  $('select').not('.disabled').material_select();   </script>
          <center>
          <div class="input-field col s6 ">
            <input id="firma" type="hidden" name="firma">
            <label for="firma">Firma:</label>
          </div>

          <div class="input-field">       
            <canvas id="canvas" width="400" height="200"></canvas>
            <img id="imagenFirma" src="" alt="">                      
          </div>

          <div class="switch">
            <div class="input-field col s5">
              <label>
                Desactivar
                <input type="checkbox" id="canvasSwitch" onchange="OnChangeCheckbox()">
                <span class="lever"></span>
                Activar
              </label>
            </div>
            
            <div class="input-field col s4">
              <input class="waves-effect waves-light btn" type="button" value="Guardar" onclick="openNewWindow();">
            </div>
            <div class="input-field col s3">
              <input class="waves-effect waves-light btn" type="button" value="Limpiar" onclick="limpiar();">
            </div>
          </div>
          </center>
          <br>
          <!--<div class="file-field input-field col s12">
            <div class="btn">
              <span>Foto:</span>
              <input name="foto" type="file">
            </div>
            <div class="file-path-wrapper">
              <input class="file-path validate" type="text">
            </div>
            <br>
          </div>-->
          <br>
          <center>
            <br><br><br>
            <input class="waves-effect waves-light btn-large blue" type="submit" value="REGISTRAR" />
          </center>
          <br>
        </form>
      </div>
    </div>
  </div>
</div>
</div>