<center><p class="titulo">Registro de Demanda Inducida</p></center>
<form id="form" method="post" action="<?php echo BASE_URL; ?>demanda_inducida/nuevo">
	<input type="hidden" name="guardar" value="1" />
	<div class="row">
		<div class="input-field col s5">
			<table class="highlight">
				<tbody>
					<tr>
						<td>
							<input type="checkbox" class="filled-in" name="selectDemanda1" id="selectDemanda1" value="1">
							<label for="selectDemanda1" class="black-text text-black"> Vacunaci&oacute;n</label>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" class="filled-in" name="selectDemanda2" id="selectDemanda2" value="1">
							<label for="selectDemanda2" class="black-text text-black"> Salud Oral (cada 6 meses)</label>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" class="filled-in" name="selectDemanda3" id="selectDemanda3" value="1">
							<label for="selectDemanda3" class="black-text text-black"> Planificaci&oacute;n Familiar</label>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" class="filled-in" name="selectDemanda4" id="selectDemanda4" value="1">
							<label for="selectDemanda4" class="black-text text-black"> Atenci&oacute;n del parto y reci&eacute;n nacido</label>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" class="filled-in" name="selectDemanda5" id="selectDemanda5" value="1">
							<label for="selectDemanda5" class="black-text text-black"> Control del Embarazo</label>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" class="filled-in" name="selectDemanda6" id="selectDemanda6" value="1">
							<label for="selectDemanda6" class="black-text text-black"> Atenci&oacute;n al joven (10 a 29 años)</label>
						</td>
					</tr>
				</tbody>
			</table>		
		</div>
		<div class="input-field col s6">
			<table class="highlight">
				<tbody>
					<tr>
						<td>
							<input type="checkbox" class="filled-in" name="selectDemanda7" id="selectDemanda7" value="1">
							<label for="selectDemanda7" class="black-text text-black"> Atenci&oacute;n al adulto (45-50-55-60-65-70-75-80 años)</label>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" class="filled-in" name="selectDemanda8" id="selectDemanda8" value="1">
							<label for="selectDemanda8" class="black-text text-black"> Crecimiento y desarrollo</label>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" class="filled-in" name="selectDemanda9" id="selectDemanda9" value="1">
							<label for="selectDemanda9" class="black-text text-black"> Toma de citolog&iacute;a</label>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" class="filled-in" name="selectDemanda10" id="selectDemanda10" value="1">
							<label for="selectDemanda10" class="black-text text-black"> Examen de seno</label>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" class="filled-in" name="selectDemanda11" id="selectDemanda11" value="1">
							<label for="selectDemanda11" class="black-text text-black"> Atenci&oacute;n preconcepcional</label>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" class="filled-in" name="selectDemanda12" id="selectDemanda12" value="1">
							<label for="selectDemanda12" class="black-text text-black"> Tamizaje visual (4-11-16-45-55-65-70…5)</label>
						</td>
					</tr>
					<tr>
						<td>
							<input type="submit" class="waves-effect waves-light btn" value="Guardar" />
						</td>
					</tr>
				</tbody>
			</table>	
		</div>
		
	</div>
</form>