<a class="waves-effect waves-light btn" href="<?php echo BASE_URL . 'firma/nuevo'; ?>">Agregar firma</a>

<?php 
	//BORRAR CONTENIDO CARPETAL TEMPORAL
 	$dir = ROOT.'public\temp'; 
	foreach (scandir($dir) as $item) {
	if ($item == '.' || $item == '..') continue;
	unlink($dir.DIRECTORY_SEPARATOR.$item);
	}
?>

<ul id="firmas" class="dropdown-content">
	<?php if(isset($this->firmas)) : ?>
		<?php for($i = 0; $i < count($this->firmas); $i++): ?>
			
			<li><a href="<?php echo BASE_URL . 'firma/ver/' . $this->firmas[$i]['id']; ?>"><?php echo $this->firmas[$i]['id']; ?></a></li>
		 			  
		<?php endfor;?>
	<?php endif; ?>
</ul>
  <a class="btn dropdown-button" href="#!" data-activates="firmas">Ver<i class="mdi-navigation-arrow-drop-down right"></i></a>



